//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="AbsorbedDoseOfIonizingRadiation"/>, such as <see cref="AbsorbedDoseOfIonizingRadiationUnits.Gray"/>.
    /// </summary>
    public static class AbsorbedDoseOfIonizingRadiationUnits
    {
        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Centigray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Centigray = new("Centigray", "Centigrays", new BaseUnits(length: LengthUnit.Decimeter, time: DurationUnit.Second), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Decigray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Decigray = new("Decigray", "Decigrays", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Femtogray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Femtogray = new("Femtogray", "Femtograys", BaseUnits.Undefined, new QuantityValue(1, 1000000000000000));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Gigagray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Gigagray = new("Gigagray", "Gigagrays", BaseUnits.Undefined, 1000000000);

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Gray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Gray = new("Gray", "Grays", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Kilogray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Kilogray = new("Kilogray", "Kilograys", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Kilorad"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Kilorad = new("Kilorad", "Kilorads", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Megagray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Megagray = new("Megagray", "Megagrays", new BaseUnits(length: LengthUnit.Kilometer, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Megarad"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Megarad = new("Megarad", "Megarads", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Microgray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Microgray = new("Microgray", "Micrograys", new BaseUnits(length: LengthUnit.Millimeter, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Milligray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Milligray = new("Milligray", "Milligrays", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Millirad"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Millirad = new("Millirad", "Millirads", BaseUnits.Undefined, new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Nanogray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Nanogray = new("Nanogray", "Nanograys", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Petagray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Petagray = new("Petagray", "Petagrays", BaseUnits.Undefined, 1000000000000000);

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Picogray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Picogray = new("Picogray", "Picograys", new BaseUnits(length: LengthUnit.Micrometer, time: DurationUnit.Second), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Rad"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Rad = new("Rad", "Rads", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="AbsorbedDoseOfIonizingRadiationUnit.Teragray"/> unit of <see cref="AbsorbedDoseOfIonizingRadiation"/>.
        /// </summary>
        public static readonly UnitOf<AbsorbedDoseOfIonizingRadiation> Teragray = new("Teragray", "Teragrays", new BaseUnits(length: LengthUnit.Megameter, time: DurationUnit.Second), 1000000000000);
    }
}
