//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="AmountOfSubstance"/>, such as <see cref="AmountOfSubstanceUnits.Mole"/>.
    /// </summary>
    public static class AmountOfSubstanceUnits
    {
        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Centimole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Centimole = new("Centimole", "Centimoles", new BaseUnits(amount: AmountOfSubstanceUnit.Centimole), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.CentipoundMole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> CentipoundMole = new("CentipoundMole", "CentipoundMoles", new BaseUnits(amount: AmountOfSubstanceUnit.CentipoundMole), new QuantityValue(45359237, 10000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Decimole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Decimole = new("Decimole", "Decimoles", new BaseUnits(amount: AmountOfSubstanceUnit.Decimole), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.DecipoundMole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> DecipoundMole = new("DecipoundMole", "DecipoundMoles", new BaseUnits(amount: AmountOfSubstanceUnit.DecipoundMole), new QuantityValue(45359237, 1000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Femtomole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Femtomole = new("Femtomole", "Femtomoles", new BaseUnits(amount: AmountOfSubstanceUnit.Femtomole), new QuantityValue(1, 1000000000000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Kilomole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Kilomole = new("Kilomole", "Kilomoles", new BaseUnits(amount: AmountOfSubstanceUnit.Kilomole), 1000);

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.KilopoundMole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> KilopoundMole = new("KilopoundMole", "KilopoundMoles", new BaseUnits(amount: AmountOfSubstanceUnit.KilopoundMole), new QuantityValue(45359237, 100));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Megamole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Megamole = new("Megamole", "Megamoles", new BaseUnits(amount: AmountOfSubstanceUnit.Megamole), 1000000);

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Micromole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Micromole = new("Micromole", "Micromoles", new BaseUnits(amount: AmountOfSubstanceUnit.Micromole), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.MicropoundMole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> MicropoundMole = new("MicropoundMole", "MicropoundMoles", new BaseUnits(amount: AmountOfSubstanceUnit.MicropoundMole), new QuantityValue(45359237, 100000000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Millimole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Millimole = new("Millimole", "Millimoles", new BaseUnits(amount: AmountOfSubstanceUnit.Millimole), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.MillipoundMole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> MillipoundMole = new("MillipoundMole", "MillipoundMoles", new BaseUnits(amount: AmountOfSubstanceUnit.MillipoundMole), new QuantityValue(45359237, 100000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Mole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Mole = new("Mole", "Moles", new BaseUnits(amount: AmountOfSubstanceUnit.Mole), 1);

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Nanomole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Nanomole = new("Nanomole", "Nanomoles", new BaseUnits(amount: AmountOfSubstanceUnit.Nanomole), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.NanopoundMole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> NanopoundMole = new("NanopoundMole", "NanopoundMoles", new BaseUnits(amount: AmountOfSubstanceUnit.NanopoundMole), new QuantityValue(45359237, 100000000000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.Picomole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> Picomole = new("Picomole", "Picomoles", new BaseUnits(amount: AmountOfSubstanceUnit.Picomole), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="AmountOfSubstanceUnit.PoundMole"/> unit of <see cref="AmountOfSubstance"/>.
        /// </summary>
        public static readonly UnitOf<AmountOfSubstance> PoundMole = new("PoundMole", "PoundMoles", new BaseUnits(amount: AmountOfSubstanceUnit.PoundMole), new QuantityValue(45359237, 100000));
    }
}
