//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="AmplitudeRatio"/>, such as <see cref="AmplitudeRatioUnits.DecibelVolt"/>.
    /// </summary>
    public static class AmplitudeRatioUnits
    {
        /// <summary>
        ///     The <see cref="AmplitudeRatioUnit.DecibelMicrovolt"/> unit of <see cref="AmplitudeRatio"/>.
        /// </summary>
        public static readonly UnitOf<AmplitudeRatio> DecibelMicrovolt = new("DecibelMicrovolt", "DecibelMicrovolts", BaseUnits.Undefined,
            new ConversionExpression(coefficient: 1, constantTerm: 120),
            new ConversionExpression(coefficient: 1, constantTerm: -120));

        /// <summary>
        ///     The <see cref="AmplitudeRatioUnit.DecibelMillivolt"/> unit of <see cref="AmplitudeRatio"/>.
        /// </summary>
        public static readonly UnitOf<AmplitudeRatio> DecibelMillivolt = new("DecibelMillivolt", "DecibelMillivolts", BaseUnits.Undefined,
            new ConversionExpression(coefficient: 1, constantTerm: 60),
            new ConversionExpression(coefficient: 1, constantTerm: -60));

        /// <summary>
        ///     The <see cref="AmplitudeRatioUnit.DecibelUnloaded"/> unit of <see cref="AmplitudeRatio"/>.
        /// </summary>
        public static readonly UnitOf<AmplitudeRatio> DecibelUnloaded = new("DecibelUnloaded", "DecibelsUnloaded", BaseUnits.Undefined,
            new ConversionExpression(coefficient: 1, constantTerm: new QuantityValue(2218487499, 1000000000)),
            new ConversionExpression(coefficient: 1, constantTerm: new QuantityValue(-2218487499, 1000000000)));

        /// <summary>
        ///     The <see cref="AmplitudeRatioUnit.DecibelVolt"/> unit of <see cref="AmplitudeRatio"/>.
        /// </summary>
        public static readonly UnitOf<AmplitudeRatio> DecibelVolt = new("DecibelVolt", "DecibelVolts", BaseUnits.Undefined, 1);
    }
}
