//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Angle"/>, such as <see cref="AngleUnits.Radian"/>.
    /// </summary>
    public static class AngleUnits
    {
        /// <summary>
        ///     The <see cref="AngleUnit.Arcminute"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Arcminute = new("Arcminute", "Arcminutes", BaseUnits.Undefined, new QuantityValue(3141592653589793, new BigInteger(108) * QuantityValue.PowerOfTen(17)));

        /// <summary>
        ///     The <see cref="AngleUnit.Arcsecond"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Arcsecond = new("Arcsecond", "Arcseconds", BaseUnits.Undefined, new QuantityValue(3141592653589793, new BigInteger(648) * QuantityValue.PowerOfTen(18)));

        /// <summary>
        ///     The <see cref="AngleUnit.Centiradian"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Centiradian = new("Centiradian", "Centiradians", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="AngleUnit.Deciradian"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Deciradian = new("Deciradian", "Deciradians", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="AngleUnit.Degree"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Degree = new("Degree", "Degrees", BaseUnits.Undefined, new QuantityValue(3141592653589793, 180000000000000000));

        /// <summary>
        ///     The <see cref="AngleUnit.Gradian"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Gradian = new("Gradian", "Gradians", BaseUnits.Undefined, new QuantityValue(3141592653589793, 200000000000000000));

        /// <summary>
        ///     The <see cref="AngleUnit.Microdegree"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Microdegree = new("Microdegree", "Microdegrees", BaseUnits.Undefined, new QuantityValue(3141592653589793, new BigInteger(18) * QuantityValue.PowerOfTen(22)));

        /// <summary>
        ///     The <see cref="AngleUnit.Microradian"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Microradian = new("Microradian", "Microradians", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="AngleUnit.Millidegree"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Millidegree = new("Millidegree", "Millidegrees", BaseUnits.Undefined, new QuantityValue(3141592653589793, new BigInteger(18) * QuantityValue.PowerOfTen(19)));

        /// <summary>
        ///     The <see cref="AngleUnit.Milliradian"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Milliradian = new("Milliradian", "Milliradians", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="AngleUnit.Nanodegree"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Nanodegree = new("Nanodegree", "Nanodegrees", BaseUnits.Undefined, new QuantityValue(3141592653589793, new BigInteger(18) * QuantityValue.PowerOfTen(25)));

        /// <summary>
        ///     The <see cref="AngleUnit.Nanoradian"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Nanoradian = new("Nanoradian", "Nanoradians", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="AngleUnit.NatoMil"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> NatoMil = new("NatoMil", "NatoMils", BaseUnits.Undefined, new QuantityValue(3141592653589793, 3200000000000000000));

        /// <summary>
        ///     The <see cref="AngleUnit.Radian"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Radian = new("Radian", "Radians", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="AngleUnit.Revolution"/> unit of <see cref="Angle"/>.
        /// </summary>
        public static readonly UnitOf<Angle> Revolution = new("Revolution", "Revolutions", BaseUnits.Undefined, new QuantityValue(3141592653589793, 500000000000000));
    }
}
