//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="AreaMomentOfInertia"/>, such as <see cref="AreaMomentOfInertiaUnits.MeterToTheFourth"/>.
    /// </summary>
    public static class AreaMomentOfInertiaUnits
    {
        /// <summary>
        ///     The <see cref="AreaMomentOfInertiaUnit.CentimeterToTheFourth"/> unit of <see cref="AreaMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<AreaMomentOfInertia> CentimeterToTheFourth = new("CentimeterToTheFourth", "CentimetersToTheFourth", new BaseUnits(length: LengthUnit.Centimeter), new QuantityValue(1, 100000000));

        /// <summary>
        ///     The <see cref="AreaMomentOfInertiaUnit.DecimeterToTheFourth"/> unit of <see cref="AreaMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<AreaMomentOfInertia> DecimeterToTheFourth = new("DecimeterToTheFourth", "DecimetersToTheFourth", new BaseUnits(length: LengthUnit.Decimeter), new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="AreaMomentOfInertiaUnit.FootToTheFourth"/> unit of <see cref="AreaMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<AreaMomentOfInertia> FootToTheFourth = new("FootToTheFourth", "FeetToTheFourth", new BaseUnits(length: LengthUnit.Foot), new QuantityValue(21071715921, 2441406250000));

        /// <summary>
        ///     The <see cref="AreaMomentOfInertiaUnit.InchToTheFourth"/> unit of <see cref="AreaMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<AreaMomentOfInertia> InchToTheFourth = new("InchToTheFourth", "InchesToTheFourth", new BaseUnits(length: LengthUnit.Inch), new QuantityValue(260144641, 625000000000000));

        /// <summary>
        ///     The <see cref="AreaMomentOfInertiaUnit.MeterToTheFourth"/> unit of <see cref="AreaMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<AreaMomentOfInertia> MeterToTheFourth = new("MeterToTheFourth", "MetersToTheFourth", new BaseUnits(length: LengthUnit.Meter), 1);

        /// <summary>
        ///     The <see cref="AreaMomentOfInertiaUnit.MillimeterToTheFourth"/> unit of <see cref="AreaMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<AreaMomentOfInertia> MillimeterToTheFourth = new("MillimeterToTheFourth", "MillimetersToTheFourth", new BaseUnits(length: LengthUnit.Millimeter), new QuantityValue(1, 1000000000000));
    }
}
