//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="AreaPerLength"/>, such as <see cref="AreaPerLengthUnits.SquareMeterPerMeter"/>.
    /// </summary>
    public static class AreaPerLengthUnits
    {
        /// <summary>
        ///     The <see cref="AreaPerLengthUnit.SquareCentimeterPerMeter"/> unit of <see cref="AreaPerLength"/>.
        /// </summary>
        public static readonly UnitOf<AreaPerLength> SquareCentimeterPerMeter = new("SquareCentimeterPerMeter", "SquareCentimetersPerMeter", BaseUnits.Undefined, new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="AreaPerLengthUnit.SquareFootPerFoot"/> unit of <see cref="AreaPerLength"/>.
        /// </summary>
        public static readonly UnitOf<AreaPerLength> SquareFootPerFoot = new("SquareFootPerFoot", "SquareFeetPerFoot", BaseUnits.Undefined, new QuantityValue(381, 1250));

        /// <summary>
        ///     The <see cref="AreaPerLengthUnit.SquareInchPerFoot"/> unit of <see cref="AreaPerLength"/>.
        /// </summary>
        public static readonly UnitOf<AreaPerLength> SquareInchPerFoot = new("SquareInchPerFoot", "SquareInchesPerFoot", BaseUnits.Undefined, new QuantityValue(127, 60000));

        /// <summary>
        ///     The <see cref="AreaPerLengthUnit.SquareInchPerInch"/> unit of <see cref="AreaPerLength"/>.
        /// </summary>
        public static readonly UnitOf<AreaPerLength> SquareInchPerInch = new("SquareInchPerInch", "SquareInchesPerInch", BaseUnits.Undefined, new QuantityValue(127, 5000));

        /// <summary>
        ///     The <see cref="AreaPerLengthUnit.SquareMeterPerMeter"/> unit of <see cref="AreaPerLength"/>.
        /// </summary>
        public static readonly UnitOf<AreaPerLength> SquareMeterPerMeter = new("SquareMeterPerMeter", "SquareMetersPerMeter", new BaseUnits(length: LengthUnit.Meter), 1);

        /// <summary>
        ///     The <see cref="AreaPerLengthUnit.SquareMillimeterPerMeter"/> unit of <see cref="AreaPerLength"/>.
        /// </summary>
        public static readonly UnitOf<AreaPerLength> SquareMillimeterPerMeter = new("SquareMillimeterPerMeter", "SquareMillimetersPerMeter", BaseUnits.Undefined, new QuantityValue(1, 1000000));
    }
}
