//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="BitRate"/>, such as <see cref="BitRateUnits.BitPerSecond"/>.
    /// </summary>
    public static class BitRateUnits
    {
        /// <summary>
        ///     The <see cref="BitRateUnit.BitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> BitPerSecond = new("BitPerSecond", "BitsPerSecond", new BaseUnits(time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="BitRateUnit.BytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> BytePerSecond = new("BytePerSecond", "BytesPerSecond", BaseUnits.Undefined, 8);

        /// <summary>
        ///     The <see cref="BitRateUnit.ExabitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> ExabitPerSecond = new("ExabitPerSecond", "ExabitsPerSecond", BaseUnits.Undefined, 1000000000000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.ExabytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> ExabytePerSecond = new("ExabytePerSecond", "ExabytesPerSecond", BaseUnits.Undefined, 8000000000000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.ExaoctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> ExaoctetPerSecond = new("ExaoctetPerSecond", "ExaoctetsPerSecond", BaseUnits.Undefined, 8000000000000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.ExbibitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> ExbibitPerSecond = new("ExbibitPerSecond", "ExbibitsPerSecond", BaseUnits.Undefined, 1152921504606846976);

        /// <summary>
        ///     The <see cref="BitRateUnit.ExbibytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> ExbibytePerSecond = new("ExbibytePerSecond", "ExbibytesPerSecond", BaseUnits.Undefined, new QuantityValue(BigInteger.Pow(2, 63), 1));

        /// <summary>
        ///     The <see cref="BitRateUnit.ExbioctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> ExbioctetPerSecond = new("ExbioctetPerSecond", "ExbioctetsPerSecond", BaseUnits.Undefined, new QuantityValue(BigInteger.Pow(2, 63), 1));

        /// <summary>
        ///     The <see cref="BitRateUnit.GibibitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> GibibitPerSecond = new("GibibitPerSecond", "GibibitsPerSecond", BaseUnits.Undefined, 1073741824);

        /// <summary>
        ///     The <see cref="BitRateUnit.GibibytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> GibibytePerSecond = new("GibibytePerSecond", "GibibytesPerSecond", BaseUnits.Undefined, 8589934592);

        /// <summary>
        ///     The <see cref="BitRateUnit.GibioctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> GibioctetPerSecond = new("GibioctetPerSecond", "GibioctetsPerSecond", BaseUnits.Undefined, 8589934592);

        /// <summary>
        ///     The <see cref="BitRateUnit.GigabitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> GigabitPerSecond = new("GigabitPerSecond", "GigabitsPerSecond", new BaseUnits(time: DurationUnit.Nanosecond), 1000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.GigabytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> GigabytePerSecond = new("GigabytePerSecond", "GigabytesPerSecond", BaseUnits.Undefined, 8000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.GigaoctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> GigaoctetPerSecond = new("GigaoctetPerSecond", "GigaoctetsPerSecond", BaseUnits.Undefined, 8000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.KibibitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> KibibitPerSecond = new("KibibitPerSecond", "KibibitsPerSecond", BaseUnits.Undefined, 1024);

        /// <summary>
        ///     The <see cref="BitRateUnit.KibibytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> KibibytePerSecond = new("KibibytePerSecond", "KibibytesPerSecond", BaseUnits.Undefined, 8192);

        /// <summary>
        ///     The <see cref="BitRateUnit.KibioctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> KibioctetPerSecond = new("KibioctetPerSecond", "KibioctetsPerSecond", BaseUnits.Undefined, 8192);

        /// <summary>
        ///     The <see cref="BitRateUnit.KilobitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> KilobitPerSecond = new("KilobitPerSecond", "KilobitsPerSecond", new BaseUnits(time: DurationUnit.Millisecond), 1000);

        /// <summary>
        ///     The <see cref="BitRateUnit.KilobytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> KilobytePerSecond = new("KilobytePerSecond", "KilobytesPerSecond", BaseUnits.Undefined, 8000);

        /// <summary>
        ///     The <see cref="BitRateUnit.KilooctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> KilooctetPerSecond = new("KilooctetPerSecond", "KilooctetsPerSecond", BaseUnits.Undefined, 8000);

        /// <summary>
        ///     The <see cref="BitRateUnit.MebibitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> MebibitPerSecond = new("MebibitPerSecond", "MebibitsPerSecond", BaseUnits.Undefined, 1048576);

        /// <summary>
        ///     The <see cref="BitRateUnit.MebibytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> MebibytePerSecond = new("MebibytePerSecond", "MebibytesPerSecond", BaseUnits.Undefined, 8388608);

        /// <summary>
        ///     The <see cref="BitRateUnit.MebioctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> MebioctetPerSecond = new("MebioctetPerSecond", "MebioctetsPerSecond", BaseUnits.Undefined, 8388608);

        /// <summary>
        ///     The <see cref="BitRateUnit.MegabitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> MegabitPerSecond = new("MegabitPerSecond", "MegabitsPerSecond", new BaseUnits(time: DurationUnit.Microsecond), 1000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.MegabytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> MegabytePerSecond = new("MegabytePerSecond", "MegabytesPerSecond", BaseUnits.Undefined, 8000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.MegaoctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> MegaoctetPerSecond = new("MegaoctetPerSecond", "MegaoctetsPerSecond", BaseUnits.Undefined, 8000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.OctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> OctetPerSecond = new("OctetPerSecond", "OctetsPerSecond", BaseUnits.Undefined, 8);

        /// <summary>
        ///     The <see cref="BitRateUnit.PebibitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> PebibitPerSecond = new("PebibitPerSecond", "PebibitsPerSecond", BaseUnits.Undefined, 1125899906842624);

        /// <summary>
        ///     The <see cref="BitRateUnit.PebibytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> PebibytePerSecond = new("PebibytePerSecond", "PebibytesPerSecond", BaseUnits.Undefined, 9007199254740992);

        /// <summary>
        ///     The <see cref="BitRateUnit.PebioctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> PebioctetPerSecond = new("PebioctetPerSecond", "PebioctetsPerSecond", BaseUnits.Undefined, 9007199254740992);

        /// <summary>
        ///     The <see cref="BitRateUnit.PetabitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> PetabitPerSecond = new("PetabitPerSecond", "PetabitsPerSecond", BaseUnits.Undefined, 1000000000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.PetabytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> PetabytePerSecond = new("PetabytePerSecond", "PetabytesPerSecond", BaseUnits.Undefined, 8000000000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.PetaoctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> PetaoctetPerSecond = new("PetaoctetPerSecond", "PetaoctetsPerSecond", BaseUnits.Undefined, 8000000000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.TebibitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> TebibitPerSecond = new("TebibitPerSecond", "TebibitsPerSecond", BaseUnits.Undefined, 1099511627776);

        /// <summary>
        ///     The <see cref="BitRateUnit.TebibytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> TebibytePerSecond = new("TebibytePerSecond", "TebibytesPerSecond", BaseUnits.Undefined, 8796093022208);

        /// <summary>
        ///     The <see cref="BitRateUnit.TebioctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> TebioctetPerSecond = new("TebioctetPerSecond", "TebioctetsPerSecond", BaseUnits.Undefined, 8796093022208);

        /// <summary>
        ///     The <see cref="BitRateUnit.TerabitPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> TerabitPerSecond = new("TerabitPerSecond", "TerabitsPerSecond", new BaseUnits(time: DurationUnit.Picosecond), 1000000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.TerabytePerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> TerabytePerSecond = new("TerabytePerSecond", "TerabytesPerSecond", BaseUnits.Undefined, 8000000000000);

        /// <summary>
        ///     The <see cref="BitRateUnit.TeraoctetPerSecond"/> unit of <see cref="BitRate"/>.
        /// </summary>
        public static readonly UnitOf<BitRate> TeraoctetPerSecond = new("TeraoctetPerSecond", "TeraoctetsPerSecond", BaseUnits.Undefined, 8000000000000);
    }
}
