//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="CoefficientOfThermalExpansion"/>, such as <see cref="CoefficientOfThermalExpansionUnits.PerKelvin"/>.
    /// </summary>
    public static class CoefficientOfThermalExpansionUnits
    {
        /// <summary>
        ///     The <see cref="CoefficientOfThermalExpansionUnit.PerDegreeCelsius"/> unit of <see cref="CoefficientOfThermalExpansion"/>.
        /// </summary>
        public static readonly UnitOf<CoefficientOfThermalExpansion> PerDegreeCelsius = new("PerDegreeCelsius", "PerDegreeCelsius", new BaseUnits(temperature: TemperatureUnit.DegreeCelsius), 1);

        /// <summary>
        ///     The <see cref="CoefficientOfThermalExpansionUnit.PerDegreeFahrenheit"/> unit of <see cref="CoefficientOfThermalExpansion"/>.
        /// </summary>
        public static readonly UnitOf<CoefficientOfThermalExpansion> PerDegreeFahrenheit = new("PerDegreeFahrenheit", "PerDegreeFahrenheit", new BaseUnits(temperature: TemperatureUnit.DegreeFahrenheit), new QuantityValue(9, 5));

        /// <summary>
        ///     The <see cref="CoefficientOfThermalExpansionUnit.PerKelvin"/> unit of <see cref="CoefficientOfThermalExpansion"/>.
        /// </summary>
        public static readonly UnitOf<CoefficientOfThermalExpansion> PerKelvin = new("PerKelvin", "PerKelvin", new BaseUnits(temperature: TemperatureUnit.Kelvin), 1);

        /// <summary>
        ///     The <see cref="CoefficientOfThermalExpansionUnit.PpmPerDegreeCelsius"/> unit of <see cref="CoefficientOfThermalExpansion"/>.
        /// </summary>
        public static readonly UnitOf<CoefficientOfThermalExpansion> PpmPerDegreeCelsius = new("PpmPerDegreeCelsius", "PpmPerDegreeCelsius", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="CoefficientOfThermalExpansionUnit.PpmPerDegreeFahrenheit"/> unit of <see cref="CoefficientOfThermalExpansion"/>.
        /// </summary>
        public static readonly UnitOf<CoefficientOfThermalExpansion> PpmPerDegreeFahrenheit = new("PpmPerDegreeFahrenheit", "PpmPerDegreeFahrenheit", BaseUnits.Undefined, new QuantityValue(9, 5000000));

        /// <summary>
        ///     The <see cref="CoefficientOfThermalExpansionUnit.PpmPerKelvin"/> unit of <see cref="CoefficientOfThermalExpansion"/>.
        /// </summary>
        public static readonly UnitOf<CoefficientOfThermalExpansion> PpmPerKelvin = new("PpmPerKelvin", "PpmPerKelvin", BaseUnits.Undefined, new QuantityValue(1, 1000000));
    }
}
