//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Density"/>, such as <see cref="DensityUnits.KilogramPerCubicMeter"/>.
    /// </summary>
    public static class DensityUnits
    {
        /// <summary>
        ///     The <see cref="DensityUnit.CentigramPerDeciliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> CentigramPerDeciliter = new("CentigramPerDeciliter", "CentigramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="DensityUnit.CentigramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> CentigramPerLiter = new("CentigramPerLiter", "CentigramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Centigram), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="DensityUnit.CentigramPerMilliliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> CentigramPerMilliliter = new("CentigramPerMilliliter", "CentigramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Centigram), 10);

        /// <summary>
        ///     The <see cref="DensityUnit.DecigramPerDeciliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> DecigramPerDeciliter = new("DecigramPerDeciliter", "DecigramsPerDeciliter", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="DensityUnit.DecigramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> DecigramPerLiter = new("DecigramPerLiter", "DecigramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Decigram), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="DensityUnit.DecigramPerMilliliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> DecigramPerMilliliter = new("DecigramPerMilliliter", "DecigramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Decigram), 100);

        /// <summary>
        ///     The <see cref="DensityUnit.FemtogramPerDeciliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> FemtogramPerDeciliter = new("FemtogramPerDeciliter", "FemtogramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100000000000000));

        /// <summary>
        ///     The <see cref="DensityUnit.FemtogramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> FemtogramPerLiter = new("FemtogramPerLiter", "FemtogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Femtogram), new QuantityValue(1, 1000000000000000));

        /// <summary>
        ///     The <see cref="DensityUnit.FemtogramPerMilliliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> FemtogramPerMilliliter = new("FemtogramPerMilliliter", "FemtogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Femtogram), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="DensityUnit.GramPerCubicCentimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> GramPerCubicCentimeter = new("GramPerCubicCentimeter", "GramsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Gram), 1000);

        /// <summary>
        ///     The <see cref="DensityUnit.GramPerCubicFoot"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> GramPerCubicFoot = new("GramPerCubicFoot", "GramsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Gram), new QuantityValue(1953125, 55306341));

        /// <summary>
        ///     The <see cref="DensityUnit.GramPerCubicInch"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> GramPerCubicInch = new("GramPerCubicInch", "GramsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Gram), new QuantityValue(125000000, 2048383));

        /// <summary>
        ///     The <see cref="DensityUnit.GramPerCubicMeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> GramPerCubicMeter = new("GramPerCubicMeter", "GramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="DensityUnit.GramPerCubicMillimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> GramPerCubicMillimeter = new("GramPerCubicMillimeter", "GramsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Gram), 1000000);

        /// <summary>
        ///     The <see cref="DensityUnit.GramPerDeciliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> GramPerDeciliter = new("GramPerDeciliter", "GramsPerDeciliter", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="DensityUnit.GramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> GramPerLiter = new("GramPerLiter", "GramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Gram), 1);

        /// <summary>
        ///     The <see cref="DensityUnit.GramPerMilliliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> GramPerMilliliter = new("GramPerMilliliter", "GramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Gram), 1000);

        /// <summary>
        ///     The <see cref="DensityUnit.KilogramPerCubicCentimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> KilogramPerCubicCentimeter = new("KilogramPerCubicCentimeter", "KilogramsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Kilogram), 1000000);

        /// <summary>
        ///     The <see cref="DensityUnit.KilogramPerCubicMeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> KilogramPerCubicMeter = new("KilogramPerCubicMeter", "KilogramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram), 1);

        /// <summary>
        ///     The <see cref="DensityUnit.KilogramPerCubicMillimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> KilogramPerCubicMillimeter = new("KilogramPerCubicMillimeter", "KilogramsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram), 1000000000);

        /// <summary>
        ///     The <see cref="DensityUnit.KilogramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> KilogramPerLiter = new("KilogramPerLiter", "KilogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilogram), 1000);

        /// <summary>
        ///     The <see cref="DensityUnit.KilopoundPerCubicFoot"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> KilopoundPerCubicFoot = new("KilopoundPerCubicFoot", "KilopoundsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Kilopound), new QuantityValue(3543690390625, 221225364));

        /// <summary>
        ///     The <see cref="DensityUnit.KilopoundPerCubicInch"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> KilopoundPerCubicInch = new("KilopoundPerCubicInch", "KilopoundsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Kilopound), new QuantityValue(56699046250000, 2048383));

        /// <summary>
        ///     The <see cref="DensityUnit.KilopoundPerCubicYard"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> KilopoundPerCubicYard = new("KilopoundPerCubicYard", "KilopoundsPerCubicYard", new BaseUnits(length: LengthUnit.Yard, mass: MassUnit.Kilopound), new QuantityValue(3543690390625, 5973084828));

        /// <summary>
        ///     The <see cref="DensityUnit.MicrogramPerCubicMeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> MicrogramPerCubicMeter = new("MicrogramPerCubicMeter", "MicrogramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="DensityUnit.MicrogramPerDeciliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> MicrogramPerDeciliter = new("MicrogramPerDeciliter", "MicrogramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="DensityUnit.MicrogramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> MicrogramPerLiter = new("MicrogramPerLiter", "MicrogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Microgram), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="DensityUnit.MicrogramPerMilliliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> MicrogramPerMilliliter = new("MicrogramPerMilliliter", "MicrogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Microgram), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="DensityUnit.MilligramPerCubicMeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> MilligramPerCubicMeter = new("MilligramPerCubicMeter", "MilligramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="DensityUnit.MilligramPerDeciliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> MilligramPerDeciliter = new("MilligramPerDeciliter", "MilligramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="DensityUnit.MilligramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> MilligramPerLiter = new("MilligramPerLiter", "MilligramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Milligram), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="DensityUnit.MilligramPerMilliliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> MilligramPerMilliliter = new("MilligramPerMilliliter", "MilligramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Milligram), 1);

        /// <summary>
        ///     The <see cref="DensityUnit.NanogramPerDeciliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> NanogramPerDeciliter = new("NanogramPerDeciliter", "NanogramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100000000));

        /// <summary>
        ///     The <see cref="DensityUnit.NanogramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> NanogramPerLiter = new("NanogramPerLiter", "NanogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Nanogram), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="DensityUnit.NanogramPerMilliliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> NanogramPerMilliliter = new("NanogramPerMilliliter", "NanogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Nanogram), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="DensityUnit.PicogramPerDeciliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PicogramPerDeciliter = new("PicogramPerDeciliter", "PicogramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100000000000));

        /// <summary>
        ///     The <see cref="DensityUnit.PicogramPerLiter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PicogramPerLiter = new("PicogramPerLiter", "PicogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Picogram), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="DensityUnit.PicogramPerMilliliter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PicogramPerMilliliter = new("PicogramPerMilliliter", "PicogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Picogram), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="DensityUnit.PoundPerCubicCentimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PoundPerCubicCentimeter = new("PoundPerCubicCentimeter", "PoundsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Pound), new QuantityValue(45359237, 100));

        /// <summary>
        ///     The <see cref="DensityUnit.PoundPerCubicFoot"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PoundPerCubicFoot = new("PoundPerCubicFoot", "PoundsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Pound), new QuantityValue(28349523125, 1769802912));

        /// <summary>
        ///     The <see cref="DensityUnit.PoundPerCubicInch"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PoundPerCubicInch = new("PoundPerCubicInch", "PoundsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Pound), new QuantityValue(56699046250, 2048383));

        /// <summary>
        ///     The <see cref="DensityUnit.PoundPerCubicMeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PoundPerCubicMeter = new("PoundPerCubicMeter", "PoundsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Pound), new QuantityValue(45359237, 100000000));

        /// <summary>
        ///     The <see cref="DensityUnit.PoundPerCubicMillimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PoundPerCubicMillimeter = new("PoundPerCubicMillimeter", "PoundsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Pound), 453592370);

        /// <summary>
        ///     The <see cref="DensityUnit.PoundPerCubicYard"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PoundPerCubicYard = new("PoundPerCubicYard", "PoundsPerCubicYard", new BaseUnits(length: LengthUnit.Yard, mass: MassUnit.Pound), new QuantityValue(28349523125, 47784678624));

        /// <summary>
        ///     The <see cref="DensityUnit.PoundPerImperialGallon"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PoundPerImperialGallon = new("PoundPerImperialGallon", "PoundsPerImperialGallon", BaseUnits.Undefined, new QuantityValue(45359237, 454609));

        /// <summary>
        ///     The <see cref="DensityUnit.PoundPerUSGallon"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> PoundPerUSGallon = new("PoundPerUSGallon", "PoundsPerUSGallon", BaseUnits.Undefined, new QuantityValue(736351250, 6145149));

        /// <summary>
        ///     The <see cref="DensityUnit.SlugPerCubicCentimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> SlugPerCubicCentimeter = new("SlugPerCubicCentimeter", "SlugsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Slug), new QuantityValue(8896443230521, 609600));

        /// <summary>
        ///     The <see cref="DensityUnit.SlugPerCubicFoot"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> SlugPerCubicFoot = new("SlugPerCubicFoot", "SlugsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Slug), new QuantityValue(5560277019075625, 10788718551552));

        /// <summary>
        ///     The <see cref="DensityUnit.SlugPerCubicInch"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> SlugPerCubicInch = new("SlugPerCubicInch", "SlugsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Slug), new QuantityValue(5560277019075625, 6243471384));

        /// <summary>
        ///     The <see cref="DensityUnit.SlugPerCubicMeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> SlugPerCubicMeter = new("SlugPerCubicMeter", "SlugsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Slug), new QuantityValue(8896443230521, 609600000000));

        /// <summary>
        ///     The <see cref="DensityUnit.SlugPerCubicMillimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> SlugPerCubicMillimeter = new("SlugPerCubicMillimeter", "SlugsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Slug), new QuantityValue(44482216152605, 3048));

        /// <summary>
        ///     The <see cref="DensityUnit.TonnePerCubicCentimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> TonnePerCubicCentimeter = new("TonnePerCubicCentimeter", "TonnesPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Tonne), 1000000000);

        /// <summary>
        ///     The <see cref="DensityUnit.TonnePerCubicFoot"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> TonnePerCubicFoot = new("TonnePerCubicFoot", "TonnesPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Tonne), new QuantityValue(1953125000000, 55306341));

        /// <summary>
        ///     The <see cref="DensityUnit.TonnePerCubicInch"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> TonnePerCubicInch = new("TonnePerCubicInch", "TonnesPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Tonne), new QuantityValue(125000000000000, 2048383));

        /// <summary>
        ///     The <see cref="DensityUnit.TonnePerCubicMeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> TonnePerCubicMeter = new("TonnePerCubicMeter", "TonnesPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Tonne), 1000);

        /// <summary>
        ///     The <see cref="DensityUnit.TonnePerCubicMillimeter"/> unit of <see cref="Density"/>.
        /// </summary>
        public static readonly UnitOf<Density> TonnePerCubicMillimeter = new("TonnePerCubicMillimeter", "TonnesPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Tonne), 1000000000000);
    }
}
