//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="DoseAreaProduct"/>, such as <see cref="DoseAreaProductUnits.GraySquareMeter"/>.
    /// </summary>
    public static class DoseAreaProductUnits
    {
        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.CentigraySquareCentimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> CentigraySquareCentimeter = new("CentigraySquareCentimeter", "CentigraySquareCentimeters", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.CentigraySquareDecimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> CentigraySquareDecimeter = new("CentigraySquareDecimeter", "CentigraySquareDecimeters", BaseUnits.Undefined, new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.CentigraySquareMeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> CentigraySquareMeter = new("CentigraySquareMeter", "CentigraySquareMeters", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.CentigraySquareMicrometer"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> CentigraySquareMicrometer = new("CentigraySquareMicrometer", "CentigraySquareMicrometers", BaseUnits.Undefined, new QuantityValue(1, 100000000000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.CentigraySquareMillimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> CentigraySquareMillimeter = new("CentigraySquareMillimeter", "CentigraySquareMillimeters", BaseUnits.Undefined, new QuantityValue(1, 100000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.DecigraySquareCentimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> DecigraySquareCentimeter = new("DecigraySquareCentimeter", "DecigraySquareCentimeters", BaseUnits.Undefined, new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.DecigraySquareDecimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> DecigraySquareDecimeter = new("DecigraySquareDecimeter", "DecigraySquareDecimeters", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.DecigraySquareMeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> DecigraySquareMeter = new("DecigraySquareMeter", "DecigraySquareMeters", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.DecigraySquareMicrometer"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> DecigraySquareMicrometer = new("DecigraySquareMicrometer", "DecigraySquareMicrometers", BaseUnits.Undefined, new QuantityValue(1, 10000000000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.DecigraySquareMillimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> DecigraySquareMillimeter = new("DecigraySquareMillimeter", "DecigraySquareMillimeters", BaseUnits.Undefined, new QuantityValue(1, 10000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.GraySquareCentimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> GraySquareCentimeter = new("GraySquareCentimeter", "GraySquareCentimeters", BaseUnits.Undefined, new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.GraySquareDecimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> GraySquareDecimeter = new("GraySquareDecimeter", "GraySquareDecimeters", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.GraySquareMeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> GraySquareMeter = new("GraySquareMeter", "GraySquareMeters", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.GraySquareMicrometer"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> GraySquareMicrometer = new("GraySquareMicrometer", "GraySquareMicrometers", BaseUnits.Undefined, new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.GraySquareMillimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> GraySquareMillimeter = new("GraySquareMillimeter", "GraySquareMillimeters", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MicrograySquareCentimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MicrograySquareCentimeter = new("MicrograySquareCentimeter", "MicrograySquareCentimeters", BaseUnits.Undefined, new QuantityValue(1, 10000000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MicrograySquareDecimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MicrograySquareDecimeter = new("MicrograySquareDecimeter", "MicrograySquareDecimeters", BaseUnits.Undefined, new QuantityValue(1, 100000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MicrograySquareMeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MicrograySquareMeter = new("MicrograySquareMeter", "MicrograySquareMeters", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MicrograySquareMicrometer"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MicrograySquareMicrometer = new("MicrograySquareMicrometer", "MicrograySquareMicrometers", BaseUnits.Undefined, new QuantityValue(1, 1000000000000000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MicrograySquareMillimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MicrograySquareMillimeter = new("MicrograySquareMillimeter", "MicrograySquareMillimeters", BaseUnits.Undefined, new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MilligraySquareCentimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MilligraySquareCentimeter = new("MilligraySquareCentimeter", "MilligraySquareCentimeters", BaseUnits.Undefined, new QuantityValue(1, 10000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MilligraySquareDecimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MilligraySquareDecimeter = new("MilligraySquareDecimeter", "MilligraySquareDecimeters", BaseUnits.Undefined, new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MilligraySquareMeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MilligraySquareMeter = new("MilligraySquareMeter", "MilligraySquareMeters", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MilligraySquareMicrometer"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MilligraySquareMicrometer = new("MilligraySquareMicrometer", "MilligraySquareMicrometers", BaseUnits.Undefined, new QuantityValue(1, 1000000000000000));

        /// <summary>
        ///     The <see cref="DoseAreaProductUnit.MilligraySquareMillimeter"/> unit of <see cref="DoseAreaProduct"/>.
        /// </summary>
        public static readonly UnitOf<DoseAreaProduct> MilligraySquareMillimeter = new("MilligraySquareMillimeter", "MilligraySquareMillimeters", BaseUnits.Undefined, new QuantityValue(1, 1000000000));
    }
}
