//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Duration"/>, such as <see cref="DurationUnits.Second"/>.
    /// </summary>
    public static class DurationUnits
    {
        /// <summary>
        ///     The <see cref="DurationUnit.Day"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Day = new("Day", "Days", new BaseUnits(time: DurationUnit.Day), 86400);

        /// <summary>
        ///     The <see cref="DurationUnit.Hour"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Hour = new("Hour", "Hours", new BaseUnits(time: DurationUnit.Hour), 3600);

        /// <summary>
        ///     The <see cref="DurationUnit.JulianYear"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> JulianYear = new("JulianYear", "JulianYears", new BaseUnits(time: DurationUnit.JulianYear), 31557600);

        /// <summary>
        ///     The <see cref="DurationUnit.Microsecond"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Microsecond = new("Microsecond", "Microseconds", new BaseUnits(time: DurationUnit.Microsecond), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="DurationUnit.Millisecond"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Millisecond = new("Millisecond", "Milliseconds", new BaseUnits(time: DurationUnit.Millisecond), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="DurationUnit.Minute"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Minute = new("Minute", "Minutes", new BaseUnits(time: DurationUnit.Minute), 60);

        /// <summary>
        ///     The <see cref="DurationUnit.Month30"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Month30 = new("Month30", "Months30", new BaseUnits(time: DurationUnit.Month30), 2592000);

        /// <summary>
        ///     The <see cref="DurationUnit.Nanosecond"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Nanosecond = new("Nanosecond", "Nanoseconds", new BaseUnits(time: DurationUnit.Nanosecond), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="DurationUnit.Picosecond"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Picosecond = new("Picosecond", "Picoseconds", new BaseUnits(time: DurationUnit.Picosecond), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="DurationUnit.Second"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Second = new("Second", "Seconds", new BaseUnits(time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="DurationUnit.Sol"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Sol = new("Sol", "Sols", new BaseUnits(time: DurationUnit.Sol), new QuantityValue(22193811, 250));

        /// <summary>
        ///     The <see cref="DurationUnit.Week"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Week = new("Week", "Weeks", new BaseUnits(time: DurationUnit.Week), 604800);

        /// <summary>
        ///     The <see cref="DurationUnit.Year365"/> unit of <see cref="Duration"/>.
        /// </summary>
        public static readonly UnitOf<Duration> Year365 = new("Year365", "Years365", new BaseUnits(time: DurationUnit.Year365), 31536000);
    }
}
