//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricCurrentGradient"/>, such as <see cref="ElectricCurrentGradientUnits.AmperePerSecond"/>.
    /// </summary>
    public static class ElectricCurrentGradientUnits
    {
        /// <summary>
        ///     The <see cref="ElectricCurrentGradientUnit.AmperePerMicrosecond"/> unit of <see cref="ElectricCurrentGradient"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentGradient> AmperePerMicrosecond = new("AmperePerMicrosecond", "AmperesPerMicrosecond", new BaseUnits(time: DurationUnit.Microsecond, current: ElectricCurrentUnit.Ampere), 1000000);

        /// <summary>
        ///     The <see cref="ElectricCurrentGradientUnit.AmperePerMillisecond"/> unit of <see cref="ElectricCurrentGradient"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentGradient> AmperePerMillisecond = new("AmperePerMillisecond", "AmperesPerMillisecond", new BaseUnits(time: DurationUnit.Millisecond, current: ElectricCurrentUnit.Ampere), 1000);

        /// <summary>
        ///     The <see cref="ElectricCurrentGradientUnit.AmperePerMinute"/> unit of <see cref="ElectricCurrentGradient"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentGradient> AmperePerMinute = new("AmperePerMinute", "AmperesPerMinute", new BaseUnits(time: DurationUnit.Minute, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 60));

        /// <summary>
        ///     The <see cref="ElectricCurrentGradientUnit.AmperePerNanosecond"/> unit of <see cref="ElectricCurrentGradient"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentGradient> AmperePerNanosecond = new("AmperePerNanosecond", "AmperesPerNanosecond", new BaseUnits(time: DurationUnit.Nanosecond, current: ElectricCurrentUnit.Ampere), 1000000000);

        /// <summary>
        ///     The <see cref="ElectricCurrentGradientUnit.AmperePerSecond"/> unit of <see cref="ElectricCurrentGradient"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentGradient> AmperePerSecond = new("AmperePerSecond", "AmperesPerSecond", new BaseUnits(time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1);

        /// <summary>
        ///     The <see cref="ElectricCurrentGradientUnit.MilliamperePerMinute"/> unit of <see cref="ElectricCurrentGradient"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentGradient> MilliamperePerMinute = new("MilliamperePerMinute", "MilliamperesPerMinute", new BaseUnits(time: DurationUnit.Minute, current: ElectricCurrentUnit.Milliampere), new QuantityValue(1, 60000));

        /// <summary>
        ///     The <see cref="ElectricCurrentGradientUnit.MilliamperePerSecond"/> unit of <see cref="ElectricCurrentGradient"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentGradient> MilliamperePerSecond = new("MilliamperePerSecond", "MilliamperesPerSecond", new BaseUnits(time: DurationUnit.Second, current: ElectricCurrentUnit.Milliampere), new QuantityValue(1, 1000));
    }
}
