//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricPotential"/>, such as <see cref="ElectricPotentialUnits.Volt"/>.
    /// </summary>
    public static class ElectricPotentialUnits
    {
        /// <summary>
        ///     The <see cref="ElectricPotentialUnit.Kilovolt"/> unit of <see cref="ElectricPotential"/>.
        /// </summary>
        public static readonly UnitOf<ElectricPotential> Kilovolt = new("Kilovolt", "Kilovolts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Milliampere), 1000);

        /// <summary>
        ///     The <see cref="ElectricPotentialUnit.Megavolt"/> unit of <see cref="ElectricPotential"/>.
        /// </summary>
        public static readonly UnitOf<ElectricPotential> Megavolt = new("Megavolt", "Megavolts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Microampere), 1000000);

        /// <summary>
        ///     The <see cref="ElectricPotentialUnit.Microvolt"/> unit of <see cref="ElectricPotential"/>.
        /// </summary>
        public static readonly UnitOf<ElectricPotential> Microvolt = new("Microvolt", "Microvolts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ElectricPotentialUnit.Millivolt"/> unit of <see cref="ElectricPotential"/>.
        /// </summary>
        public static readonly UnitOf<ElectricPotential> Millivolt = new("Millivolt", "Millivolts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ElectricPotentialUnit.Nanovolt"/> unit of <see cref="ElectricPotential"/>.
        /// </summary>
        public static readonly UnitOf<ElectricPotential> Nanovolt = new("Nanovolt", "Nanovolts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="ElectricPotentialUnit.Volt"/> unit of <see cref="ElectricPotential"/>.
        /// </summary>
        public static readonly UnitOf<ElectricPotential> Volt = new("Volt", "Volts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1);
    }
}
