//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricCurrent"/>, such as <see cref="ElectricCurrentUnits.Ampere"/>.
    /// </summary>
    public static class ElectricCurrentUnits
    {
        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Ampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Ampere = new("Ampere", "Amperes", new BaseUnits(current: ElectricCurrentUnit.Ampere), 1);

        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Centiampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Centiampere = new("Centiampere", "Centiamperes", new BaseUnits(current: ElectricCurrentUnit.Centiampere), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Femtoampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Femtoampere = new("Femtoampere", "Femtoamperes", new BaseUnits(current: ElectricCurrentUnit.Femtoampere), new QuantityValue(1, 1000000000000000));

        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Kiloampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Kiloampere = new("Kiloampere", "Kiloamperes", new BaseUnits(current: ElectricCurrentUnit.Kiloampere), 1000);

        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Megaampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Megaampere = new("Megaampere", "Megaamperes", new BaseUnits(current: ElectricCurrentUnit.Megaampere), 1000000);

        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Microampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Microampere = new("Microampere", "Microamperes", new BaseUnits(current: ElectricCurrentUnit.Microampere), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Milliampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Milliampere = new("Milliampere", "Milliamperes", new BaseUnits(current: ElectricCurrentUnit.Milliampere), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Nanoampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Nanoampere = new("Nanoampere", "Nanoamperes", new BaseUnits(current: ElectricCurrentUnit.Nanoampere), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="ElectricCurrentUnit.Picoampere"/> unit of <see cref="ElectricCurrent"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrent> Picoampere = new("Picoampere", "Picoamperes", new BaseUnits(current: ElectricCurrentUnit.Picoampere), new QuantityValue(1, 1000000000000));
    }
}
