//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricInductance"/>, such as <see cref="ElectricInductanceUnits.Henry"/>.
    /// </summary>
    public static class ElectricInductanceUnits
    {
        /// <summary>
        ///     The <see cref="ElectricInductanceUnit.Henry"/> unit of <see cref="ElectricInductance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricInductance> Henry = new("Henry", "Henries", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1);

        /// <summary>
        ///     The <see cref="ElectricInductanceUnit.Microhenry"/> unit of <see cref="ElectricInductance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricInductance> Microhenry = new("Microhenry", "Microhenries", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ElectricInductanceUnit.Millihenry"/> unit of <see cref="ElectricInductance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricInductance> Millihenry = new("Millihenry", "Millihenries", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ElectricInductanceUnit.Nanohenry"/> unit of <see cref="ElectricInductance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricInductance> Nanohenry = new("Nanohenry", "Nanohenries", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="ElectricInductanceUnit.Picohenry"/> unit of <see cref="ElectricInductance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricInductance> Picohenry = new("Picohenry", "Picohenries", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Nanogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000000000));
    }
}
