//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricCurrentDensity"/>, such as <see cref="ElectricCurrentDensityUnits.AmperePerSquareMeter"/>.
    /// </summary>
    public static class ElectricCurrentDensityUnits
    {
        /// <summary>
        ///     The <see cref="ElectricCurrentDensityUnit.AmperePerSquareFoot"/> unit of <see cref="ElectricCurrentDensity"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentDensity> AmperePerSquareFoot = new("AmperePerSquareFoot", "AmperesPerSquareFoot", new BaseUnits(length: LengthUnit.Foot, current: ElectricCurrentUnit.Ampere), new QuantityValue(1562500, 145161));

        /// <summary>
        ///     The <see cref="ElectricCurrentDensityUnit.AmperePerSquareInch"/> unit of <see cref="ElectricCurrentDensity"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentDensity> AmperePerSquareInch = new("AmperePerSquareInch", "AmperesPerSquareInch", new BaseUnits(length: LengthUnit.Inch, current: ElectricCurrentUnit.Ampere), new QuantityValue(25000000, 16129));

        /// <summary>
        ///     The <see cref="ElectricCurrentDensityUnit.AmperePerSquareMeter"/> unit of <see cref="ElectricCurrentDensity"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCurrentDensity> AmperePerSquareMeter = new("AmperePerSquareMeter", "AmperesPerSquareMeter", new BaseUnits(length: LengthUnit.Meter, current: ElectricCurrentUnit.Ampere), 1);
    }
}
