//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricReactiveEnergy"/>, such as <see cref="ElectricReactiveEnergyUnits.VoltampereReactiveHour"/>.
    /// </summary>
    public static class ElectricReactiveEnergyUnits
    {
        /// <summary>
        ///     The <see cref="ElectricReactiveEnergyUnit.KilovoltampereReactiveHour"/> unit of <see cref="ElectricReactiveEnergy"/>.
        /// </summary>
        public static readonly UnitOf<ElectricReactiveEnergy> KilovoltampereReactiveHour = new("KilovoltampereReactiveHour", "KilovoltampereReactiveHours", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="ElectricReactiveEnergyUnit.MegavoltampereReactiveHour"/> unit of <see cref="ElectricReactiveEnergy"/>.
        /// </summary>
        public static readonly UnitOf<ElectricReactiveEnergy> MegavoltampereReactiveHour = new("MegavoltampereReactiveHour", "MegavoltampereReactiveHours", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="ElectricReactiveEnergyUnit.VoltampereReactiveHour"/> unit of <see cref="ElectricReactiveEnergy"/>.
        /// </summary>
        public static readonly UnitOf<ElectricReactiveEnergy> VoltampereReactiveHour = new("VoltampereReactiveHour", "VoltampereReactiveHours", BaseUnits.Undefined, 1);
    }
}
