//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricApparentPower"/>, such as <see cref="ElectricApparentPowerUnits.Voltampere"/>.
    /// </summary>
    public static class ElectricApparentPowerUnits
    {
        /// <summary>
        ///     The <see cref="ElectricApparentPowerUnit.Gigavoltampere"/> unit of <see cref="ElectricApparentPower"/>.
        /// </summary>
        public static readonly UnitOf<ElectricApparentPower> Gigavoltampere = new("Gigavoltampere", "Gigavoltamperes", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Millisecond), 1000000000);

        /// <summary>
        ///     The <see cref="ElectricApparentPowerUnit.Kilovoltampere"/> unit of <see cref="ElectricApparentPower"/>.
        /// </summary>
        public static readonly UnitOf<ElectricApparentPower> Kilovoltampere = new("Kilovoltampere", "Kilovoltamperes", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="ElectricApparentPowerUnit.Megavoltampere"/> unit of <see cref="ElectricApparentPower"/>.
        /// </summary>
        public static readonly UnitOf<ElectricApparentPower> Megavoltampere = new("Megavoltampere", "Megavoltamperes", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="ElectricApparentPowerUnit.Microvoltampere"/> unit of <see cref="ElectricApparentPower"/>.
        /// </summary>
        public static readonly UnitOf<ElectricApparentPower> Microvoltampere = new("Microvoltampere", "Microvoltamperes", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ElectricApparentPowerUnit.Millivoltampere"/> unit of <see cref="ElectricApparentPower"/>.
        /// </summary>
        public static readonly UnitOf<ElectricApparentPower> Millivoltampere = new("Millivoltampere", "Millivoltamperes", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ElectricApparentPowerUnit.Voltampere"/> unit of <see cref="ElectricApparentPower"/>.
        /// </summary>
        public static readonly UnitOf<ElectricApparentPower> Voltampere = new("Voltampere", "Voltamperes", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);
    }
}
