//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricCapacitance"/>, such as <see cref="ElectricCapacitanceUnits.Farad"/>.
    /// </summary>
    public static class ElectricCapacitanceUnits
    {
        /// <summary>
        ///     The <see cref="ElectricCapacitanceUnit.Farad"/> unit of <see cref="ElectricCapacitance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCapacitance> Farad = new("Farad", "Farads", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1);

        /// <summary>
        ///     The <see cref="ElectricCapacitanceUnit.Kilofarad"/> unit of <see cref="ElectricCapacitance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCapacitance> Kilofarad = new("Kilofarad", "Kilofarads", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1000);

        /// <summary>
        ///     The <see cref="ElectricCapacitanceUnit.Megafarad"/> unit of <see cref="ElectricCapacitance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCapacitance> Megafarad = new("Megafarad", "Megafarads", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1000000);

        /// <summary>
        ///     The <see cref="ElectricCapacitanceUnit.Microfarad"/> unit of <see cref="ElectricCapacitance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCapacitance> Microfarad = new("Microfarad", "Microfarads", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Milliampere), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ElectricCapacitanceUnit.Millifarad"/> unit of <see cref="ElectricCapacitance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCapacitance> Millifarad = new("Millifarad", "Millifarads", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ElectricCapacitanceUnit.Nanofarad"/> unit of <see cref="ElectricCapacitance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCapacitance> Nanofarad = new("Nanofarad", "Nanofarads", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="ElectricCapacitanceUnit.Picofarad"/> unit of <see cref="ElectricCapacitance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricCapacitance> Picofarad = new("Picofarad", "Picofarads", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Microampere), new QuantityValue(1, 1000000000000));
    }
}
