//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ElectricResistance"/>, such as <see cref="ElectricResistanceUnits.Ohm"/>.
    /// </summary>
    public static class ElectricResistanceUnits
    {
        /// <summary>
        ///     The <see cref="ElectricResistanceUnit.Gigaohm"/> unit of <see cref="ElectricResistance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricResistance> Gigaohm = new("Gigaohm", "Gigaohms", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Millisecond, current: ElectricCurrentUnit.Ampere), 1000000000);

        /// <summary>
        ///     The <see cref="ElectricResistanceUnit.Kiloohm"/> unit of <see cref="ElectricResistance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricResistance> Kiloohm = new("Kiloohm", "Kiloohms", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="ElectricResistanceUnit.Megaohm"/> unit of <see cref="ElectricResistance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricResistance> Megaohm = new("Megaohm", "Megaohms", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1000000);

        /// <summary>
        ///     The <see cref="ElectricResistanceUnit.Microohm"/> unit of <see cref="ElectricResistance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricResistance> Microohm = new("Microohm", "Microohms", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ElectricResistanceUnit.Milliohm"/> unit of <see cref="ElectricResistance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricResistance> Milliohm = new("Milliohm", "Milliohms", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ElectricResistanceUnit.Nanoohm"/> unit of <see cref="ElectricResistance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricResistance> Nanoohm = new("Nanoohm", "Nanoohms", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="ElectricResistanceUnit.Ohm"/> unit of <see cref="ElectricResistance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricResistance> Ohm = new("Ohm", "Ohms", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1);

        /// <summary>
        ///     The <see cref="ElectricResistanceUnit.Teraohm"/> unit of <see cref="ElectricResistance"/>.
        /// </summary>
        public static readonly UnitOf<ElectricResistance> Teraohm = new("Teraohm", "Teraohms", new BaseUnits(length: LengthUnit.Megameter, mass: MassUnit.Kilogram, time: DurationUnit.Second, current: ElectricCurrentUnit.Ampere), 1000000000000);
    }
}
