//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Energy"/>, such as <see cref="EnergyUnits.Joule"/>.
    /// </summary>
    public static class EnergyUnits
    {
        /// <summary>
        ///     The <see cref="EnergyUnit.BritishThermalUnit"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> BritishThermalUnit = new("BritishThermalUnit", "BritishThermalUnits", BaseUnits.Undefined, new QuantityValue(52752792631, 50000000));

        /// <summary>
        ///     The <see cref="EnergyUnit.Calorie"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Calorie = new("Calorie", "Calories", BaseUnits.Undefined, new QuantityValue(523, 125));

        /// <summary>
        ///     The <see cref="EnergyUnit.DecathermEc"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> DecathermEc = new("DecathermEc", "DecathermsEc", BaseUnits.Undefined, new QuantityValue(52752792631, 50));

        /// <summary>
        ///     The <see cref="EnergyUnit.DecathermImperial"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> DecathermImperial = new("DecathermImperial", "DecathermsImperial", BaseUnits.Undefined, new QuantityValue(26376396314337, 25000));

        /// <summary>
        ///     The <see cref="EnergyUnit.DecathermUs"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> DecathermUs = new("DecathermUs", "DecathermsUs", BaseUnits.Undefined, 1054804000);

        /// <summary>
        ///     The <see cref="EnergyUnit.ElectronVolt"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> ElectronVolt = new("ElectronVolt", "ElectronVolts", BaseUnits.Undefined, new QuantityValue(801088317, new BigInteger(5) * QuantityValue.PowerOfTen(27)));

        /// <summary>
        ///     The <see cref="EnergyUnit.Erg"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Erg = new("Erg", "Ergs", BaseUnits.Undefined, new QuantityValue(1, 10000000));

        /// <summary>
        ///     The <see cref="EnergyUnit.FootPound"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> FootPound = new("FootPound", "FootPounds", BaseUnits.Undefined, new QuantityValue(3389544870828501, 2500000000000000));

        /// <summary>
        ///     The <see cref="EnergyUnit.GigabritishThermalUnit"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> GigabritishThermalUnit = new("GigabritishThermalUnit", "GigabritishThermalUnits", BaseUnits.Undefined, 1055055852620);

        /// <summary>
        ///     The <see cref="EnergyUnit.GigaelectronVolt"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> GigaelectronVolt = new("GigaelectronVolt", "GigaelectronVolts", BaseUnits.Undefined, new QuantityValue(801088317, 5000000000000000000));

        /// <summary>
        ///     The <see cref="EnergyUnit.Gigajoule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Gigajoule = new("Gigajoule", "Gigajoules", BaseUnits.Undefined, 1000000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.GigawattDay"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> GigawattDay = new("GigawattDay", "GigawattDays", BaseUnits.Undefined, 86400000000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.GigawattHour"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> GigawattHour = new("GigawattHour", "GigawattHours", BaseUnits.Undefined, 3600000000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.HorsepowerHour"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> HorsepowerHour = new("HorsepowerHour", "HorsepowerHours", BaseUnits.Undefined, new QuantityValue(1342259768728053, 500000000));

        /// <summary>
        ///     The <see cref="EnergyUnit.Joule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Joule = new("Joule", "Joules", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="EnergyUnit.KilobritishThermalUnit"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> KilobritishThermalUnit = new("KilobritishThermalUnit", "KilobritishThermalUnits", BaseUnits.Undefined, new QuantityValue(52752792631, 50000));

        /// <summary>
        ///     The <see cref="EnergyUnit.Kilocalorie"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Kilocalorie = new("Kilocalorie", "Kilocalories", BaseUnits.Undefined, 4184);

        /// <summary>
        ///     The <see cref="EnergyUnit.KiloelectronVolt"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> KiloelectronVolt = new("KiloelectronVolt", "KiloelectronVolts", BaseUnits.Undefined, new QuantityValue(801088317, new BigInteger(5) * QuantityValue.PowerOfTen(24)));

        /// <summary>
        ///     The <see cref="EnergyUnit.Kilojoule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Kilojoule = new("Kilojoule", "Kilojoules", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="EnergyUnit.KilowattDay"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> KilowattDay = new("KilowattDay", "KilowattDays", BaseUnits.Undefined, 86400000);

        /// <summary>
        ///     The <see cref="EnergyUnit.KilowattHour"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> KilowattHour = new("KilowattHour", "KilowattHours", BaseUnits.Undefined, 3600000);

        /// <summary>
        ///     The <see cref="EnergyUnit.MegabritishThermalUnit"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> MegabritishThermalUnit = new("MegabritishThermalUnit", "MegabritishThermalUnits", BaseUnits.Undefined, new QuantityValue(52752792631, 50));

        /// <summary>
        ///     The <see cref="EnergyUnit.Megacalorie"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Megacalorie = new("Megacalorie", "Megacalories", BaseUnits.Undefined, 4184000);

        /// <summary>
        ///     The <see cref="EnergyUnit.MegaelectronVolt"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> MegaelectronVolt = new("MegaelectronVolt", "MegaelectronVolts", BaseUnits.Undefined, new QuantityValue(801088317, new BigInteger(5) * QuantityValue.PowerOfTen(21)));

        /// <summary>
        ///     The <see cref="EnergyUnit.Megajoule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Megajoule = new("Megajoule", "Megajoules", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.MegawattDay"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> MegawattDay = new("MegawattDay", "MegawattDays", BaseUnits.Undefined, 86400000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.MegawattHour"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> MegawattHour = new("MegawattHour", "MegawattHours", BaseUnits.Undefined, 3600000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.Microjoule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Microjoule = new("Microjoule", "Microjoules", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="EnergyUnit.Millijoule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Millijoule = new("Millijoule", "Millijoules", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="EnergyUnit.Nanojoule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Nanojoule = new("Nanojoule", "Nanojoules", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="EnergyUnit.Petajoule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Petajoule = new("Petajoule", "Petajoules", BaseUnits.Undefined, 1000000000000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.TeraelectronVolt"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> TeraelectronVolt = new("TeraelectronVolt", "TeraelectronVolts", BaseUnits.Undefined, new QuantityValue(801088317, 5000000000000000));

        /// <summary>
        ///     The <see cref="EnergyUnit.Terajoule"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> Terajoule = new("Terajoule", "Terajoules", new BaseUnits(length: LengthUnit.Megameter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.TerawattDay"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> TerawattDay = new("TerawattDay", "TerawattDays", BaseUnits.Undefined, 86400000000000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.TerawattHour"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> TerawattHour = new("TerawattHour", "TerawattHours", BaseUnits.Undefined, 3600000000000000);

        /// <summary>
        ///     The <see cref="EnergyUnit.ThermEc"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> ThermEc = new("ThermEc", "ThermsEc", BaseUnits.Undefined, new QuantityValue(52752792631, 500));

        /// <summary>
        ///     The <see cref="EnergyUnit.ThermImperial"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> ThermImperial = new("ThermImperial", "ThermsImperial", BaseUnits.Undefined, new QuantityValue(26376396314337, 250000));

        /// <summary>
        ///     The <see cref="EnergyUnit.ThermUs"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> ThermUs = new("ThermUs", "ThermsUs", BaseUnits.Undefined, 105480400);

        /// <summary>
        ///     The <see cref="EnergyUnit.WattDay"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> WattDay = new("WattDay", "WattDays", BaseUnits.Undefined, 86400);

        /// <summary>
        ///     The <see cref="EnergyUnit.WattHour"/> unit of <see cref="Energy"/>.
        /// </summary>
        public static readonly UnitOf<Energy> WattHour = new("WattHour", "WattHours", BaseUnits.Undefined, 3600);
    }
}
