//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="EnergyDensity"/>, such as <see cref="EnergyDensityUnits.JoulePerCubicMeter"/>.
    /// </summary>
    public static class EnergyDensityUnits
    {
        /// <summary>
        ///     The <see cref="EnergyDensityUnit.GigajoulePerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> GigajoulePerCubicMeter = new("GigajoulePerCubicMeter", "GigajoulesPerCubicMeter", new BaseUnits(length: LengthUnit.Nanometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.GigawattHourPerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> GigawattHourPerCubicMeter = new("GigawattHourPerCubicMeter", "GigawattHoursPerCubicMeter", BaseUnits.Undefined, 3600000000000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.JoulePerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> JoulePerCubicMeter = new("JoulePerCubicMeter", "JoulesPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.KilojoulePerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> KilojoulePerCubicMeter = new("KilojoulePerCubicMeter", "KilojoulesPerCubicMeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.KilowattHourPerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> KilowattHourPerCubicMeter = new("KilowattHourPerCubicMeter", "KilowattHoursPerCubicMeter", BaseUnits.Undefined, 3600000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.MegajoulePerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> MegajoulePerCubicMeter = new("MegajoulePerCubicMeter", "MegajoulesPerCubicMeter", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.MegawattHourPerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> MegawattHourPerCubicMeter = new("MegawattHourPerCubicMeter", "MegawattHoursPerCubicMeter", BaseUnits.Undefined, 3600000000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.PetajoulePerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> PetajoulePerCubicMeter = new("PetajoulePerCubicMeter", "PetajoulesPerCubicMeter", new BaseUnits(length: LengthUnit.Femtometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000000000000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.PetawattHourPerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> PetawattHourPerCubicMeter = new("PetawattHourPerCubicMeter", "PetawattHoursPerCubicMeter", BaseUnits.Undefined, 3600000000000000000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.TerajoulePerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> TerajoulePerCubicMeter = new("TerajoulePerCubicMeter", "TerajoulesPerCubicMeter", new BaseUnits(length: LengthUnit.Picometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000000000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.TerawattHourPerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> TerawattHourPerCubicMeter = new("TerawattHourPerCubicMeter", "TerawattHoursPerCubicMeter", BaseUnits.Undefined, 3600000000000000);

        /// <summary>
        ///     The <see cref="EnergyDensityUnit.WattHourPerCubicMeter"/> unit of <see cref="EnergyDensity"/>.
        /// </summary>
        public static readonly UnitOf<EnergyDensity> WattHourPerCubicMeter = new("WattHourPerCubicMeter", "WattHoursPerCubicMeter", BaseUnits.Undefined, 3600);
    }
}
