//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Entropy"/>, such as <see cref="EntropyUnits.JoulePerKelvin"/>.
    /// </summary>
    public static class EntropyUnits
    {
        /// <summary>
        ///     The <see cref="EntropyUnit.CaloriePerKelvin"/> unit of <see cref="Entropy"/>.
        /// </summary>
        public static readonly UnitOf<Entropy> CaloriePerKelvin = new("CaloriePerKelvin", "CaloriesPerKelvin", BaseUnits.Undefined, new QuantityValue(523, 125));

        /// <summary>
        ///     The <see cref="EntropyUnit.JoulePerDegreeCelsius"/> unit of <see cref="Entropy"/>.
        /// </summary>
        public static readonly UnitOf<Entropy> JoulePerDegreeCelsius = new("JoulePerDegreeCelsius", "JoulesPerDegreeCelsius", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.DegreeCelsius), 1);

        /// <summary>
        ///     The <see cref="EntropyUnit.JoulePerKelvin"/> unit of <see cref="Entropy"/>.
        /// </summary>
        public static readonly UnitOf<Entropy> JoulePerKelvin = new("JoulePerKelvin", "JoulesPerKelvin", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin), 1);

        /// <summary>
        ///     The <see cref="EntropyUnit.KilocaloriePerKelvin"/> unit of <see cref="Entropy"/>.
        /// </summary>
        public static readonly UnitOf<Entropy> KilocaloriePerKelvin = new("KilocaloriePerKelvin", "KilocaloriesPerKelvin", BaseUnits.Undefined, 4184);

        /// <summary>
        ///     The <see cref="EntropyUnit.KilojoulePerDegreeCelsius"/> unit of <see cref="Entropy"/>.
        /// </summary>
        public static readonly UnitOf<Entropy> KilojoulePerDegreeCelsius = new("KilojoulePerDegreeCelsius", "KilojoulesPerDegreeCelsius", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="EntropyUnit.KilojoulePerKelvin"/> unit of <see cref="Entropy"/>.
        /// </summary>
        public static readonly UnitOf<Entropy> KilojoulePerKelvin = new("KilojoulePerKelvin", "KilojoulesPerKelvin", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="EntropyUnit.MegajoulePerKelvin"/> unit of <see cref="Entropy"/>.
        /// </summary>
        public static readonly UnitOf<Entropy> MegajoulePerKelvin = new("MegajoulePerKelvin", "MegajoulesPerKelvin", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin), 1000000);
    }
}
