//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ForcePerLength"/>, such as <see cref="ForcePerLengthUnits.NewtonPerMeter"/>.
    /// </summary>
    public static class ForcePerLengthUnits
    {
        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.CentinewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> CentinewtonPerCentimeter = new("CentinewtonPerCentimeter", "CentinewtonsPerCentimeter", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.CentinewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> CentinewtonPerMeter = new("CentinewtonPerMeter", "CentinewtonsPerMeter", new BaseUnits(mass: MassUnit.Decagram, time: DurationUnit.Second), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.CentinewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> CentinewtonPerMillimeter = new("CentinewtonPerMillimeter", "CentinewtonsPerMillimeter", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.DecanewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> DecanewtonPerCentimeter = new("DecanewtonPerCentimeter", "DecanewtonsPerCentimeter", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.DecanewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> DecanewtonPerMeter = new("DecanewtonPerMeter", "DecanewtonsPerMeter", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.DecanewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> DecanewtonPerMillimeter = new("DecanewtonPerMillimeter", "DecanewtonsPerMillimeter", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.DecinewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> DecinewtonPerCentimeter = new("DecinewtonPerCentimeter", "DecinewtonsPerCentimeter", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.DecinewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> DecinewtonPerMeter = new("DecinewtonPerMeter", "DecinewtonsPerMeter", new BaseUnits(mass: MassUnit.Hectogram, time: DurationUnit.Second), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.DecinewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> DecinewtonPerMillimeter = new("DecinewtonPerMillimeter", "DecinewtonsPerMillimeter", BaseUnits.Undefined, 100);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.KilogramForcePerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> KilogramForcePerCentimeter = new("KilogramForcePerCentimeter", "KilogramsForcePerCentimeter", BaseUnits.Undefined, new QuantityValue(196133, 200));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.KilogramForcePerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> KilogramForcePerMeter = new("KilogramForcePerMeter", "KilogramsForcePerMeter", BaseUnits.Undefined, new QuantityValue(196133, 20000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.KilogramForcePerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> KilogramForcePerMillimeter = new("KilogramForcePerMillimeter", "KilogramsForcePerMillimeter", BaseUnits.Undefined, new QuantityValue(196133, 20));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.KilonewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> KilonewtonPerCentimeter = new("KilonewtonPerCentimeter", "KilonewtonsPerCentimeter", BaseUnits.Undefined, 100000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.KilonewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> KilonewtonPerMeter = new("KilonewtonPerMeter", "KilonewtonsPerMeter", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.KilonewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> KilonewtonPerMillimeter = new("KilonewtonPerMillimeter", "KilonewtonsPerMillimeter", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.KilopoundForcePerFoot"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> KilopoundForcePerFoot = new("KilopoundForcePerFoot", "KilopoundsForcePerFoot", BaseUnits.Undefined, new QuantityValue(8896443230521, 609600000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.KilopoundForcePerInch"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> KilopoundForcePerInch = new("KilopoundForcePerInch", "KilopoundsForcePerInch", BaseUnits.Undefined, new QuantityValue(8896443230521, 50800000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MeganewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MeganewtonPerCentimeter = new("MeganewtonPerCentimeter", "MeganewtonsPerCentimeter", BaseUnits.Undefined, 100000000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MeganewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MeganewtonPerMeter = new("MeganewtonPerMeter", "MeganewtonsPerMeter", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Millisecond), 1000000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MeganewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MeganewtonPerMillimeter = new("MeganewtonPerMillimeter", "MeganewtonsPerMillimeter", BaseUnits.Undefined, 1000000000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MicronewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MicronewtonPerCentimeter = new("MicronewtonPerCentimeter", "MicronewtonsPerCentimeter", BaseUnits.Undefined, new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MicronewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MicronewtonPerMeter = new("MicronewtonPerMeter", "MicronewtonsPerMeter", new BaseUnits(mass: MassUnit.Milligram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MicronewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MicronewtonPerMillimeter = new("MicronewtonPerMillimeter", "MicronewtonsPerMillimeter", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MillinewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MillinewtonPerCentimeter = new("MillinewtonPerCentimeter", "MillinewtonsPerCentimeter", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MillinewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MillinewtonPerMeter = new("MillinewtonPerMeter", "MillinewtonsPerMeter", new BaseUnits(mass: MassUnit.Gram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.MillinewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> MillinewtonPerMillimeter = new("MillinewtonPerMillimeter", "MillinewtonsPerMillimeter", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.NanonewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> NanonewtonPerCentimeter = new("NanonewtonPerCentimeter", "NanonewtonsPerCentimeter", BaseUnits.Undefined, new QuantityValue(1, 10000000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.NanonewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> NanonewtonPerMeter = new("NanonewtonPerMeter", "NanonewtonsPerMeter", new BaseUnits(mass: MassUnit.Microgram, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.NanonewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> NanonewtonPerMillimeter = new("NanonewtonPerMillimeter", "NanonewtonsPerMillimeter", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.NewtonPerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> NewtonPerCentimeter = new("NewtonPerCentimeter", "NewtonsPerCentimeter", BaseUnits.Undefined, 100);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.NewtonPerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> NewtonPerMeter = new("NewtonPerMeter", "NewtonsPerMeter", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.NewtonPerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> NewtonPerMillimeter = new("NewtonPerMillimeter", "NewtonsPerMillimeter", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.PoundForcePerFoot"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> PoundForcePerFoot = new("PoundForcePerFoot", "PoundsForcePerFoot", BaseUnits.Undefined, new QuantityValue(8896443230521, 609600000000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.PoundForcePerInch"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> PoundForcePerInch = new("PoundForcePerInch", "PoundsForcePerInch", BaseUnits.Undefined, new QuantityValue(8896443230521, 50800000000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.PoundForcePerYard"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> PoundForcePerYard = new("PoundForcePerYard", "PoundsForcePerYard", BaseUnits.Undefined, new QuantityValue(8896443230521, 1828800000000));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.TonneForcePerCentimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> TonneForcePerCentimeter = new("TonneForcePerCentimeter", "TonnesForcePerCentimeter", BaseUnits.Undefined, 980665);

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.TonneForcePerMeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> TonneForcePerMeter = new("TonneForcePerMeter", "TonnesForcePerMeter", BaseUnits.Undefined, new QuantityValue(196133, 20));

        /// <summary>
        ///     The <see cref="ForcePerLengthUnit.TonneForcePerMillimeter"/> unit of <see cref="ForcePerLength"/>.
        /// </summary>
        public static readonly UnitOf<ForcePerLength> TonneForcePerMillimeter = new("TonneForcePerMillimeter", "TonnesForcePerMillimeter", BaseUnits.Undefined, 9806650);
    }
}
