//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Force"/>, such as <see cref="ForceUnits.Newton"/>.
    /// </summary>
    public static class ForceUnits
    {
        /// <summary>
        ///     The <see cref="ForceUnit.Decanewton"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Decanewton = new("Decanewton", "Decanewtons", new BaseUnits(length: LengthUnit.Decameter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 10);

        /// <summary>
        ///     The <see cref="ForceUnit.Dyn"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Dyn = new("Dyn", "Dyne", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Gram, time: DurationUnit.Second), new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="ForceUnit.GramForce"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> GramForce = new("GramForce", "GramsForce", BaseUnits.Undefined, new QuantityValue(196133, 20000000));

        /// <summary>
        ///     The <see cref="ForceUnit.KilogramForce"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> KilogramForce = new("KilogramForce", "KilogramsForce", BaseUnits.Undefined, new QuantityValue(196133, 20000));

        /// <summary>
        ///     The <see cref="ForceUnit.Kilonewton"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Kilonewton = new("Kilonewton", "Kilonewtons", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="ForceUnit.Kilopond"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Kilopond = new("Kilopond", "Kiloponds", BaseUnits.Undefined, new QuantityValue(196133, 20000));

        /// <summary>
        ///     The <see cref="ForceUnit.KilopoundForce"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> KilopoundForce = new("KilopoundForce", "KilopoundsForce", BaseUnits.Undefined, new QuantityValue(8896443230521, 2000000000));

        /// <summary>
        ///     The <see cref="ForceUnit.Meganewton"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Meganewton = new("Meganewton", "Meganewtons", new BaseUnits(length: LengthUnit.Megameter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="ForceUnit.Micronewton"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Micronewton = new("Micronewton", "Micronewtons", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ForceUnit.Millinewton"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Millinewton = new("Millinewton", "Millinewtons", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ForceUnit.Newton"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Newton = new("Newton", "Newtons", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="ForceUnit.OunceForce"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> OunceForce = new("OunceForce", "OunceForce", BaseUnits.Undefined, new QuantityValue(8896443230521, 32000000000000));

        /// <summary>
        ///     The <see cref="ForceUnit.Poundal"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> Poundal = new("Poundal", "Poundals", BaseUnits.Undefined, new QuantityValue(17281869297, 125000000000));

        /// <summary>
        ///     The <see cref="ForceUnit.PoundForce"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> PoundForce = new("PoundForce", "PoundsForce", BaseUnits.Undefined, new QuantityValue(8896443230521, 2000000000000));

        /// <summary>
        ///     The <see cref="ForceUnit.ShortTonForce"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> ShortTonForce = new("ShortTonForce", "ShortTonsForce", BaseUnits.Undefined, new QuantityValue(8896443230521, 1000000000));

        /// <summary>
        ///     The <see cref="ForceUnit.TonneForce"/> unit of <see cref="Force"/>.
        /// </summary>
        public static readonly UnitOf<Force> TonneForce = new("TonneForce", "TonnesForce", BaseUnits.Undefined, new QuantityValue(196133, 20));
    }
}
