//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="ForceChangeRate"/>, such as <see cref="ForceChangeRateUnits.NewtonPerSecond"/>.
    /// </summary>
    public static class ForceChangeRateUnits
    {
        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.CentinewtonPerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> CentinewtonPerSecond = new("CentinewtonPerSecond", "CentinewtonsPerSecond", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.DecanewtonPerMinute"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> DecanewtonPerMinute = new("DecanewtonPerMinute", "DecanewtonsPerMinute", BaseUnits.Undefined, new QuantityValue(1, 6));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.DecanewtonPerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> DecanewtonPerSecond = new("DecanewtonPerSecond", "DecanewtonsPerSecond", new BaseUnits(length: LengthUnit.Decameter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 10);

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.DecinewtonPerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> DecinewtonPerSecond = new("DecinewtonPerSecond", "DecinewtonsPerSecond", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.KilonewtonPerMinute"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> KilonewtonPerMinute = new("KilonewtonPerMinute", "KilonewtonsPerMinute", BaseUnits.Undefined, new QuantityValue(50, 3));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.KilonewtonPerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> KilonewtonPerSecond = new("KilonewtonPerSecond", "KilonewtonsPerSecond", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.KilopoundForcePerMinute"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> KilopoundForcePerMinute = new("KilopoundForcePerMinute", "KilopoundsForcePerMinute", BaseUnits.Undefined, new QuantityValue(8896443230521, 120000000000));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.KilopoundForcePerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> KilopoundForcePerSecond = new("KilopoundForcePerSecond", "KilopoundsForcePerSecond", BaseUnits.Undefined, new QuantityValue(8896443230521, 2000000000));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.MicronewtonPerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> MicronewtonPerSecond = new("MicronewtonPerSecond", "MicronewtonsPerSecond", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.MillinewtonPerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> MillinewtonPerSecond = new("MillinewtonPerSecond", "MillinewtonsPerSecond", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.NanonewtonPerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> NanonewtonPerSecond = new("NanonewtonPerSecond", "NanonewtonsPerSecond", new BaseUnits(length: LengthUnit.Nanometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.NewtonPerMinute"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> NewtonPerMinute = new("NewtonPerMinute", "NewtonsPerMinute", BaseUnits.Undefined, new QuantityValue(1, 60));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.NewtonPerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> NewtonPerSecond = new("NewtonPerSecond", "NewtonsPerSecond", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.PoundForcePerMinute"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> PoundForcePerMinute = new("PoundForcePerMinute", "PoundsForcePerMinute", BaseUnits.Undefined, new QuantityValue(8896443230521, 120000000000000));

        /// <summary>
        ///     The <see cref="ForceChangeRateUnit.PoundForcePerSecond"/> unit of <see cref="ForceChangeRate"/>.
        /// </summary>
        public static readonly UnitOf<ForceChangeRate> PoundForcePerSecond = new("PoundForcePerSecond", "PoundsForcePerSecond", BaseUnits.Undefined, new QuantityValue(8896443230521, 2000000000000));
    }
}
