//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Frequency"/>, such as <see cref="FrequencyUnits.Hertz"/>.
    /// </summary>
    public static class FrequencyUnits
    {
        /// <summary>
        ///     The <see cref="FrequencyUnit.BeatPerMinute"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> BeatPerMinute = new("BeatPerMinute", "BeatsPerMinute", new BaseUnits(time: DurationUnit.Minute), new QuantityValue(1, 60));

        /// <summary>
        ///     The <see cref="FrequencyUnit.CyclePerHour"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> CyclePerHour = new("CyclePerHour", "CyclesPerHour", new BaseUnits(time: DurationUnit.Hour), new QuantityValue(1, 3600));

        /// <summary>
        ///     The <see cref="FrequencyUnit.CyclePerMinute"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> CyclePerMinute = new("CyclePerMinute", "CyclesPerMinute", new BaseUnits(time: DurationUnit.Minute), new QuantityValue(1, 60));

        /// <summary>
        ///     The <see cref="FrequencyUnit.Gigahertz"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> Gigahertz = new("Gigahertz", "Gigahertz", new BaseUnits(time: DurationUnit.Nanosecond), 1000000000);

        /// <summary>
        ///     The <see cref="FrequencyUnit.Hertz"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> Hertz = new("Hertz", "Hertz", new BaseUnits(time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="FrequencyUnit.Kilohertz"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> Kilohertz = new("Kilohertz", "Kilohertz", new BaseUnits(time: DurationUnit.Millisecond), 1000);

        /// <summary>
        ///     The <see cref="FrequencyUnit.Megahertz"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> Megahertz = new("Megahertz", "Megahertz", new BaseUnits(time: DurationUnit.Microsecond), 1000000);

        /// <summary>
        ///     The <see cref="FrequencyUnit.Microhertz"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> Microhertz = new("Microhertz", "Microhertz", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="FrequencyUnit.Millihertz"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> Millihertz = new("Millihertz", "Millihertz", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="FrequencyUnit.PerSecond"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> PerSecond = new("PerSecond", "PerSecond", new BaseUnits(time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="FrequencyUnit.RadianPerSecond"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> RadianPerSecond = new("RadianPerSecond", "RadiansPerSecond", BaseUnits.Undefined, new QuantityValue(500000000000000, 3141592653589793));

        /// <summary>
        ///     The <see cref="FrequencyUnit.Terahertz"/> unit of <see cref="Frequency"/>.
        /// </summary>
        public static readonly UnitOf<Frequency> Terahertz = new("Terahertz", "Terahertz", new BaseUnits(time: DurationUnit.Picosecond), 1000000000000);
    }
}
