//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="FuelEfficiency"/>, such as <see cref="FuelEfficiencyUnits.KilometerPerLiter"/>.
    /// </summary>
    public static class FuelEfficiencyUnits
    {
        /// <summary>
        ///     The <see cref="FuelEfficiencyUnit.KilometerPerLiter"/> unit of <see cref="FuelEfficiency"/>.
        /// </summary>
        public static readonly UnitOf<FuelEfficiency> KilometerPerLiter = new("KilometerPerLiter", "KilometersPerLiter", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="FuelEfficiencyUnit.LiterPer100Kilometers"/> unit of <see cref="FuelEfficiency"/>.
        /// </summary>
        public static readonly UnitOf<FuelEfficiency> LiterPer100Kilometers = new("LiterPer100Kilometers", "LitersPer100Kilometers", BaseUnits.Undefined,
            new ConversionExpression(coefficient: 100, exponent: -1),
            new ConversionExpression(coefficient: 100, exponent: -1));

        /// <summary>
        ///     The <see cref="FuelEfficiencyUnit.MilePerUkGallon"/> unit of <see cref="FuelEfficiency"/>.
        /// </summary>
        public static readonly UnitOf<FuelEfficiency> MilePerUkGallon = new("MilePerUkGallon", "MilesPerUkGallon", BaseUnits.Undefined, new QuantityValue(804672, 2273045));

        /// <summary>
        ///     The <see cref="FuelEfficiencyUnit.MilePerUsGallon"/> unit of <see cref="FuelEfficiency"/>.
        /// </summary>
        public static readonly UnitOf<FuelEfficiency> MilePerUsGallon = new("MilePerUsGallon", "MilesPerUsGallon", BaseUnits.Undefined, new QuantityValue(48000, 112903));
    }
}
