//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="HeatTransferCoefficient"/>, such as <see cref="HeatTransferCoefficientUnits.WattPerSquareMeterKelvin"/>.
    /// </summary>
    public static class HeatTransferCoefficientUnits
    {
        /// <summary>
        ///     The <see cref="HeatTransferCoefficientUnit.BtuPerHourSquareFootDegreeFahrenheit"/> unit of <see cref="HeatTransferCoefficient"/>.
        /// </summary>
        public static readonly UnitOf<HeatTransferCoefficient> BtuPerHourSquareFootDegreeFahrenheit = new("BtuPerHourSquareFootDegreeFahrenheit", "BtusPerHourSquareFootDegreeFahrenheit", BaseUnits.Undefined, new QuantityValue(52752792631, 9290304000));

        /// <summary>
        ///     The <see cref="HeatTransferCoefficientUnit.BtuPerSecondSquareInchDegreeFahrenheit"/> unit of <see cref="HeatTransferCoefficient"/>.
        /// </summary>
        public static readonly UnitOf<HeatTransferCoefficient> BtuPerSecondSquareInchDegreeFahrenheit = new("BtuPerSecondSquareInchDegreeFahrenheit", "BtusPerSecondSquareInchDegreeFahrenheit", BaseUnits.Undefined, new QuantityValue(474775133679, 161290));

        /// <summary>
        ///     The <see cref="HeatTransferCoefficientUnit.CaloriePerHourSquareMeterDegreeCelsius"/> unit of <see cref="HeatTransferCoefficient"/>.
        /// </summary>
        public static readonly UnitOf<HeatTransferCoefficient> CaloriePerHourSquareMeterDegreeCelsius = new("CaloriePerHourSquareMeterDegreeCelsius", "CaloriesPerHourSquareMeterDegreeCelsius", BaseUnits.Undefined, new QuantityValue(523, 450000));

        /// <summary>
        ///     The <see cref="HeatTransferCoefficientUnit.KilocaloriePerHourSquareMeterDegreeCelsius"/> unit of <see cref="HeatTransferCoefficient"/>.
        /// </summary>
        public static readonly UnitOf<HeatTransferCoefficient> KilocaloriePerHourSquareMeterDegreeCelsius = new("KilocaloriePerHourSquareMeterDegreeCelsius", "KilocaloriesPerHourSquareMeterDegreeCelsius", BaseUnits.Undefined, new QuantityValue(523, 450));

        /// <summary>
        ///     The <see cref="HeatTransferCoefficientUnit.WattPerSquareMeterCelsius"/> unit of <see cref="HeatTransferCoefficient"/>.
        /// </summary>
        public static readonly UnitOf<HeatTransferCoefficient> WattPerSquareMeterCelsius = new("WattPerSquareMeterCelsius", "WattsPerSquareMeterCelsius", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.DegreeCelsius), 1);

        /// <summary>
        ///     The <see cref="HeatTransferCoefficientUnit.WattPerSquareMeterKelvin"/> unit of <see cref="HeatTransferCoefficient"/>.
        /// </summary>
        public static readonly UnitOf<HeatTransferCoefficient> WattPerSquareMeterKelvin = new("WattPerSquareMeterKelvin", "WattsPerSquareMeterKelvin", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin), 1);
    }
}
