//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Illuminance"/>, such as <see cref="IlluminanceUnits.Lux"/>.
    /// </summary>
    public static class IlluminanceUnits
    {
        /// <summary>
        ///     The <see cref="IlluminanceUnit.Kilolux"/> unit of <see cref="Illuminance"/>.
        /// </summary>
        public static readonly UnitOf<Illuminance> Kilolux = new("Kilolux", "Kilolux", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="IlluminanceUnit.Lux"/> unit of <see cref="Illuminance"/>.
        /// </summary>
        public static readonly UnitOf<Illuminance> Lux = new("Lux", "Lux", new BaseUnits(length: LengthUnit.Meter, luminousIntensity: LuminousIntensityUnit.Candela), 1);

        /// <summary>
        ///     The <see cref="IlluminanceUnit.Megalux"/> unit of <see cref="Illuminance"/>.
        /// </summary>
        public static readonly UnitOf<Illuminance> Megalux = new("Megalux", "Megalux", new BaseUnits(length: LengthUnit.Millimeter, luminousIntensity: LuminousIntensityUnit.Candela), 1000000);

        /// <summary>
        ///     The <see cref="IlluminanceUnit.Millilux"/> unit of <see cref="Illuminance"/>.
        /// </summary>
        public static readonly UnitOf<Illuminance> Millilux = new("Millilux", "Millilux", BaseUnits.Undefined, new QuantityValue(1, 1000));
    }
}
