//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Impulse"/>, such as <see cref="ImpulseUnits.NewtonSecond"/>.
    /// </summary>
    public static class ImpulseUnits
    {
        /// <summary>
        ///     The <see cref="ImpulseUnit.CentinewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> CentinewtonSecond = new("CentinewtonSecond", "CentinewtonSeconds", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="ImpulseUnit.DecanewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> DecanewtonSecond = new("DecanewtonSecond", "DecanewtonSeconds", new BaseUnits(length: LengthUnit.Decameter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 10);

        /// <summary>
        ///     The <see cref="ImpulseUnit.DecinewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> DecinewtonSecond = new("DecinewtonSecond", "DecinewtonSeconds", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="ImpulseUnit.KilogramMeterPerSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> KilogramMeterPerSecond = new("KilogramMeterPerSecond", "KilogramMetersPerSecond", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="ImpulseUnit.KilonewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> KilonewtonSecond = new("KilonewtonSecond", "KilonewtonSeconds", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="ImpulseUnit.MeganewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> MeganewtonSecond = new("MeganewtonSecond", "MeganewtonSeconds", new BaseUnits(length: LengthUnit.Megameter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="ImpulseUnit.MicronewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> MicronewtonSecond = new("MicronewtonSecond", "MicronewtonSeconds", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="ImpulseUnit.MillinewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> MillinewtonSecond = new("MillinewtonSecond", "MillinewtonSeconds", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="ImpulseUnit.NanonewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> NanonewtonSecond = new("NanonewtonSecond", "NanonewtonSeconds", new BaseUnits(length: LengthUnit.Nanometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="ImpulseUnit.NewtonSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> NewtonSecond = new("NewtonSecond", "NewtonSeconds", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="ImpulseUnit.PoundFootPerSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> PoundFootPerSecond = new("PoundFootPerSecond", "PoundFeetPerSecond", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Pound, time: DurationUnit.Second), new QuantityValue(17281869297, 125000000000));

        /// <summary>
        ///     The <see cref="ImpulseUnit.PoundForceSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> PoundForceSecond = new("PoundForceSecond", "PoundForceSeconds", BaseUnits.Undefined, new QuantityValue(8896443230521, 2000000000000));

        /// <summary>
        ///     The <see cref="ImpulseUnit.SlugFootPerSecond"/> unit of <see cref="Impulse"/>.
        /// </summary>
        public static readonly UnitOf<Impulse> SlugFootPerSecond = new("SlugFootPerSecond", "SlugFeetPerSecond", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Slug, time: DurationUnit.Second), new QuantityValue(8896443230521, 2000000000000));
    }
}
