//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Information"/>, such as <see cref="InformationUnits.Bit"/>.
    /// </summary>
    public static class InformationUnits
    {
        /// <summary>
        ///     The <see cref="InformationUnit.Bit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Bit = new("Bit", "Bits", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="InformationUnit.Byte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Byte = new("Byte", "Bytes", BaseUnits.Undefined, 8);

        /// <summary>
        ///     The <see cref="InformationUnit.Exabit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Exabit = new("Exabit", "Exabits", BaseUnits.Undefined, 1000000000000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Exabyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Exabyte = new("Exabyte", "Exabytes", BaseUnits.Undefined, 8000000000000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Exaoctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Exaoctet = new("Exaoctet", "Exaoctets", BaseUnits.Undefined, 8000000000000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Exbibit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Exbibit = new("Exbibit", "Exbibits", BaseUnits.Undefined, 1152921504606846976);

        /// <summary>
        ///     The <see cref="InformationUnit.Exbibyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Exbibyte = new("Exbibyte", "Exbibytes", BaseUnits.Undefined, new QuantityValue(BigInteger.Pow(2, 63), 1));

        /// <summary>
        ///     The <see cref="InformationUnit.Exbioctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Exbioctet = new("Exbioctet", "Exbioctets", BaseUnits.Undefined, new QuantityValue(BigInteger.Pow(2, 63), 1));

        /// <summary>
        ///     The <see cref="InformationUnit.Gibibit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Gibibit = new("Gibibit", "Gibibits", BaseUnits.Undefined, 1073741824);

        /// <summary>
        ///     The <see cref="InformationUnit.Gibibyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Gibibyte = new("Gibibyte", "Gibibytes", BaseUnits.Undefined, 8589934592);

        /// <summary>
        ///     The <see cref="InformationUnit.Gibioctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Gibioctet = new("Gibioctet", "Gibioctets", BaseUnits.Undefined, 8589934592);

        /// <summary>
        ///     The <see cref="InformationUnit.Gigabit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Gigabit = new("Gigabit", "Gigabits", BaseUnits.Undefined, 1000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Gigabyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Gigabyte = new("Gigabyte", "Gigabytes", BaseUnits.Undefined, 8000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Gigaoctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Gigaoctet = new("Gigaoctet", "Gigaoctets", BaseUnits.Undefined, 8000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Kibibit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Kibibit = new("Kibibit", "Kibibits", BaseUnits.Undefined, 1024);

        /// <summary>
        ///     The <see cref="InformationUnit.Kibibyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Kibibyte = new("Kibibyte", "Kibibytes", BaseUnits.Undefined, 8192);

        /// <summary>
        ///     The <see cref="InformationUnit.Kibioctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Kibioctet = new("Kibioctet", "Kibioctets", BaseUnits.Undefined, 8192);

        /// <summary>
        ///     The <see cref="InformationUnit.Kilobit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Kilobit = new("Kilobit", "Kilobits", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="InformationUnit.Kilobyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Kilobyte = new("Kilobyte", "Kilobytes", BaseUnits.Undefined, 8000);

        /// <summary>
        ///     The <see cref="InformationUnit.Kilooctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Kilooctet = new("Kilooctet", "Kilooctets", BaseUnits.Undefined, 8000);

        /// <summary>
        ///     The <see cref="InformationUnit.Mebibit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Mebibit = new("Mebibit", "Mebibits", BaseUnits.Undefined, 1048576);

        /// <summary>
        ///     The <see cref="InformationUnit.Mebibyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Mebibyte = new("Mebibyte", "Mebibytes", BaseUnits.Undefined, 8388608);

        /// <summary>
        ///     The <see cref="InformationUnit.Mebioctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Mebioctet = new("Mebioctet", "Mebioctets", BaseUnits.Undefined, 8388608);

        /// <summary>
        ///     The <see cref="InformationUnit.Megabit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Megabit = new("Megabit", "Megabits", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Megabyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Megabyte = new("Megabyte", "Megabytes", BaseUnits.Undefined, 8000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Megaoctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Megaoctet = new("Megaoctet", "Megaoctets", BaseUnits.Undefined, 8000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Octet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Octet = new("Octet", "Octets", BaseUnits.Undefined, 8);

        /// <summary>
        ///     The <see cref="InformationUnit.Pebibit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Pebibit = new("Pebibit", "Pebibits", BaseUnits.Undefined, 1125899906842624);

        /// <summary>
        ///     The <see cref="InformationUnit.Pebibyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Pebibyte = new("Pebibyte", "Pebibytes", BaseUnits.Undefined, 9007199254740992);

        /// <summary>
        ///     The <see cref="InformationUnit.Pebioctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Pebioctet = new("Pebioctet", "Pebioctets", BaseUnits.Undefined, 9007199254740992);

        /// <summary>
        ///     The <see cref="InformationUnit.Petabit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Petabit = new("Petabit", "Petabits", BaseUnits.Undefined, 1000000000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Petabyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Petabyte = new("Petabyte", "Petabytes", BaseUnits.Undefined, 8000000000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Petaoctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Petaoctet = new("Petaoctet", "Petaoctets", BaseUnits.Undefined, 8000000000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Tebibit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Tebibit = new("Tebibit", "Tebibits", BaseUnits.Undefined, 1099511627776);

        /// <summary>
        ///     The <see cref="InformationUnit.Tebibyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Tebibyte = new("Tebibyte", "Tebibytes", BaseUnits.Undefined, 8796093022208);

        /// <summary>
        ///     The <see cref="InformationUnit.Tebioctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Tebioctet = new("Tebioctet", "Tebioctets", BaseUnits.Undefined, 8796093022208);

        /// <summary>
        ///     The <see cref="InformationUnit.Terabit"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Terabit = new("Terabit", "Terabits", BaseUnits.Undefined, 1000000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Terabyte"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Terabyte = new("Terabyte", "Terabytes", BaseUnits.Undefined, 8000000000000);

        /// <summary>
        ///     The <see cref="InformationUnit.Teraoctet"/> unit of <see cref="Information"/>.
        /// </summary>
        public static readonly UnitOf<Information> Teraoctet = new("Teraoctet", "Teraoctets", BaseUnits.Undefined, 8000000000000);
    }
}
