//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Irradiance"/>, such as <see cref="IrradianceUnits.WattPerSquareMeter"/>.
    /// </summary>
    public static class IrradianceUnits
    {
        /// <summary>
        ///     The <see cref="IrradianceUnit.KilowattPerSquareCentimeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> KilowattPerSquareCentimeter = new("KilowattPerSquareCentimeter", "KilowattsPerSquareCentimeter", BaseUnits.Undefined, 10000000);

        /// <summary>
        ///     The <see cref="IrradianceUnit.KilowattPerSquareMeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> KilowattPerSquareMeter = new("KilowattPerSquareMeter", "KilowattsPerSquareMeter", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="IrradianceUnit.MegawattPerSquareCentimeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> MegawattPerSquareCentimeter = new("MegawattPerSquareCentimeter", "MegawattsPerSquareCentimeter", BaseUnits.Undefined, 10000000000);

        /// <summary>
        ///     The <see cref="IrradianceUnit.MegawattPerSquareMeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> MegawattPerSquareMeter = new("MegawattPerSquareMeter", "MegawattsPerSquareMeter", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="IrradianceUnit.MicrowattPerSquareCentimeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> MicrowattPerSquareCentimeter = new("MicrowattPerSquareCentimeter", "MicrowattsPerSquareCentimeter", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="IrradianceUnit.MicrowattPerSquareMeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> MicrowattPerSquareMeter = new("MicrowattPerSquareMeter", "MicrowattsPerSquareMeter", new BaseUnits(mass: MassUnit.Milligram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="IrradianceUnit.MilliwattPerSquareCentimeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> MilliwattPerSquareCentimeter = new("MilliwattPerSquareCentimeter", "MilliwattsPerSquareCentimeter", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="IrradianceUnit.MilliwattPerSquareMeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> MilliwattPerSquareMeter = new("MilliwattPerSquareMeter", "MilliwattsPerSquareMeter", new BaseUnits(mass: MassUnit.Gram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="IrradianceUnit.NanowattPerSquareCentimeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> NanowattPerSquareCentimeter = new("NanowattPerSquareCentimeter", "NanowattsPerSquareCentimeter", BaseUnits.Undefined, new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="IrradianceUnit.NanowattPerSquareMeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> NanowattPerSquareMeter = new("NanowattPerSquareMeter", "NanowattsPerSquareMeter", new BaseUnits(mass: MassUnit.Microgram, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="IrradianceUnit.PicowattPerSquareCentimeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> PicowattPerSquareCentimeter = new("PicowattPerSquareCentimeter", "PicowattsPerSquareCentimeter", BaseUnits.Undefined, new QuantityValue(1, 100000000));

        /// <summary>
        ///     The <see cref="IrradianceUnit.PicowattPerSquareMeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> PicowattPerSquareMeter = new("PicowattPerSquareMeter", "PicowattsPerSquareMeter", new BaseUnits(mass: MassUnit.Nanogram, time: DurationUnit.Second), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="IrradianceUnit.WattPerSquareCentimeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> WattPerSquareCentimeter = new("WattPerSquareCentimeter", "WattsPerSquareCentimeter", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="IrradianceUnit.WattPerSquareMeter"/> unit of <see cref="Irradiance"/>.
        /// </summary>
        public static readonly UnitOf<Irradiance> WattPerSquareMeter = new("WattPerSquareMeter", "WattsPerSquareMeter", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);
    }
}
