//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Irradiation"/>, such as <see cref="IrradiationUnits.JoulePerSquareMeter"/>.
    /// </summary>
    public static class IrradiationUnits
    {
        /// <summary>
        ///     The <see cref="IrradiationUnit.BtuPerSquareFoot"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> BtuPerSquareFoot = new("BtuPerSquareFoot", "BtusPerSquareFoot", BaseUnits.Undefined, new QuantityValue(52752792631, 4645152));

        /// <summary>
        ///     The <see cref="IrradiationUnit.JoulePerSquareCentimeter"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> JoulePerSquareCentimeter = new("JoulePerSquareCentimeter", "JoulesPerSquareCentimeter", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="IrradiationUnit.JoulePerSquareMeter"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> JoulePerSquareMeter = new("JoulePerSquareMeter", "JoulesPerSquareMeter", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="IrradiationUnit.JoulePerSquareMillimeter"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> JoulePerSquareMillimeter = new("JoulePerSquareMillimeter", "JoulesPerSquareMillimeter", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="IrradiationUnit.KilobtuPerSquareFoot"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> KilobtuPerSquareFoot = new("KilobtuPerSquareFoot", "KilobtusPerSquareFoot", BaseUnits.Undefined, new QuantityValue(6594099078875, 580644));

        /// <summary>
        ///     The <see cref="IrradiationUnit.KilojoulePerSquareMeter"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> KilojoulePerSquareMeter = new("KilojoulePerSquareMeter", "KilojoulesPerSquareMeter", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="IrradiationUnit.KilowattHourPerSquareMeter"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> KilowattHourPerSquareMeter = new("KilowattHourPerSquareMeter", "KilowattHoursPerSquareMeter", BaseUnits.Undefined, 3600000);

        /// <summary>
        ///     The <see cref="IrradiationUnit.MillijoulePerSquareCentimeter"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> MillijoulePerSquareCentimeter = new("MillijoulePerSquareCentimeter", "MillijoulesPerSquareCentimeter", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="IrradiationUnit.WattHourPerSquareMeter"/> unit of <see cref="Irradiation"/>.
        /// </summary>
        public static readonly UnitOf<Irradiation> WattHourPerSquareMeter = new("WattHourPerSquareMeter", "WattHoursPerSquareMeter", BaseUnits.Undefined, 3600);
    }
}
