//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="LeakRate"/>, such as <see cref="LeakRateUnits.PascalCubicMeterPerSecond"/>.
    /// </summary>
    public static class LeakRateUnits
    {
        /// <summary>
        ///     The <see cref="LeakRateUnit.AtmCubicCentimeterPerSecond"/> unit of <see cref="LeakRate"/>.
        /// </summary>
        public static readonly UnitOf<LeakRate> AtmCubicCentimeterPerSecond = new("AtmCubicCentimeterPerSecond", "AtmCubicCentimetersPerSecond", BaseUnits.Undefined, new QuantityValue(4053, 40000));

        /// <summary>
        ///     The <see cref="LeakRateUnit.MillibarLiterPerSecond"/> unit of <see cref="LeakRate"/>.
        /// </summary>
        public static readonly UnitOf<LeakRate> MillibarLiterPerSecond = new("MillibarLiterPerSecond", "MillibarLitersPerSecond", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="LeakRateUnit.PascalCubicMeterPerSecond"/> unit of <see cref="LeakRate"/>.
        /// </summary>
        public static readonly UnitOf<LeakRate> PascalCubicMeterPerSecond = new("PascalCubicMeterPerSecond", "PascalCubicMetersPerSecond", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="LeakRateUnit.TorrLiterPerSecond"/> unit of <see cref="LeakRate"/>.
        /// </summary>
        public static readonly UnitOf<LeakRate> TorrLiterPerSecond = new("TorrLiterPerSecond", "TorrLitersPerSecond", BaseUnits.Undefined, new QuantityValue(2, 15));
    }
}
