//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum LeakRateUnit
    {
        AtmCubicCentimeterPerSecond = 10,
        MillibarLiterPerSecond = 7,
        PascalCubicMeterPerSecond = 2,

        /// <summary>
        ///     A leak rate of one liter per second at a pressure of one torr. The torr is exactly 101325/760 pascals (1/760 of a standard atmosphere), so one torr liter per second is about 0.1333224 Pa·m³/s.
        /// </summary>
        /// <remarks>https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b8</remarks>
        TorrLiterPerSecond = 4,
    }

    #pragma warning restore 1591
}
