//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Luminance"/>, such as <see cref="LuminanceUnits.CandelaPerSquareMeter"/>.
    /// </summary>
    public static class LuminanceUnits
    {
        /// <summary>
        ///     The <see cref="LuminanceUnit.CandelaPerSquareFoot"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> CandelaPerSquareFoot = new("CandelaPerSquareFoot", "CandelasPerSquareFoot", BaseUnits.Undefined, new QuantityValue(1562500, 145161));

        /// <summary>
        ///     The <see cref="LuminanceUnit.CandelaPerSquareInch"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> CandelaPerSquareInch = new("CandelaPerSquareInch", "CandelasPerSquareInch", BaseUnits.Undefined, new QuantityValue(25000000, 16129));

        /// <summary>
        ///     The <see cref="LuminanceUnit.CandelaPerSquareMeter"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> CandelaPerSquareMeter = new("CandelaPerSquareMeter", "CandelasPerSquareMeter", new BaseUnits(length: LengthUnit.Meter, luminousIntensity: LuminousIntensityUnit.Candela), 1);

        /// <summary>
        ///     The <see cref="LuminanceUnit.CenticandelaPerSquareMeter"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> CenticandelaPerSquareMeter = new("CenticandelaPerSquareMeter", "CenticandelasPerSquareMeter", new BaseUnits(length: LengthUnit.Decameter, luminousIntensity: LuminousIntensityUnit.Candela), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="LuminanceUnit.DecicandelaPerSquareMeter"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> DecicandelaPerSquareMeter = new("DecicandelaPerSquareMeter", "DecicandelasPerSquareMeter", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="LuminanceUnit.KilocandelaPerSquareMeter"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> KilocandelaPerSquareMeter = new("KilocandelaPerSquareMeter", "KilocandelasPerSquareMeter", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="LuminanceUnit.MicrocandelaPerSquareMeter"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> MicrocandelaPerSquareMeter = new("MicrocandelaPerSquareMeter", "MicrocandelasPerSquareMeter", new BaseUnits(length: LengthUnit.Kilometer, luminousIntensity: LuminousIntensityUnit.Candela), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="LuminanceUnit.MillicandelaPerSquareMeter"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> MillicandelaPerSquareMeter = new("MillicandelaPerSquareMeter", "MillicandelasPerSquareMeter", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="LuminanceUnit.NanocandelaPerSquareMeter"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> NanocandelaPerSquareMeter = new("NanocandelaPerSquareMeter", "NanocandelasPerSquareMeter", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="LuminanceUnit.Nit"/> unit of <see cref="Luminance"/>.
        /// </summary>
        public static readonly UnitOf<Luminance> Nit = new("Nit", "Nits", BaseUnits.Undefined, 1);
    }
}
