//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Luminosity"/>, such as <see cref="LuminosityUnits.Watt"/>.
    /// </summary>
    public static class LuminosityUnits
    {
        /// <summary>
        ///     The <see cref="LuminosityUnit.Decawatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Decawatt = new("Decawatt", "Decawatts", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="LuminosityUnit.Deciwatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Deciwatt = new("Deciwatt", "Deciwatts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Hectogram, time: DurationUnit.Second), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="LuminosityUnit.Femtowatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Femtowatt = new("Femtowatt", "Femtowatts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Picogram, time: DurationUnit.Second), new QuantityValue(1, 1000000000000000));

        /// <summary>
        ///     The <see cref="LuminosityUnit.Gigawatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Gigawatt = new("Gigawatt", "Gigawatts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Millisecond), 1000000000);

        /// <summary>
        ///     The <see cref="LuminosityUnit.Kilowatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Kilowatt = new("Kilowatt", "Kilowatts", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="LuminosityUnit.Megawatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Megawatt = new("Megawatt", "Megawatts", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="LuminosityUnit.Microwatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Microwatt = new("Microwatt", "Microwatts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="LuminosityUnit.Milliwatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Milliwatt = new("Milliwatt", "Milliwatts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="LuminosityUnit.Nanowatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Nanowatt = new("Nanowatt", "Nanowatts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="LuminosityUnit.Petawatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Petawatt = new("Petawatt", "Petawatts", BaseUnits.Undefined, 1000000000000000);

        /// <summary>
        ///     The <see cref="LuminosityUnit.Picowatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Picowatt = new("Picowatt", "Picowatts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Nanogram, time: DurationUnit.Second), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="LuminosityUnit.SolarLuminosity"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> SolarLuminosity = new("SolarLuminosity", "SolarLuminosities", BaseUnits.Undefined, new QuantityValue(new BigInteger(3828) * QuantityValue.PowerOfTen(23), 1));

        /// <summary>
        ///     The <see cref="LuminosityUnit.Terawatt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Terawatt = new("Terawatt", "Terawatts", new BaseUnits(length: LengthUnit.Megameter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000000000);

        /// <summary>
        ///     The <see cref="LuminosityUnit.Watt"/> unit of <see cref="Luminosity"/>.
        /// </summary>
        public static readonly UnitOf<Luminosity> Watt = new("Watt", "Watts", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);
    }
}
