//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="MagneticField"/>, such as <see cref="MagneticFieldUnits.Tesla"/>.
    /// </summary>
    public static class MagneticFieldUnits
    {
        /// <summary>
        ///     The <see cref="MagneticFieldUnit.Gauss"/> unit of <see cref="MagneticField"/>.
        /// </summary>
        public static readonly UnitOf<MagneticField> Gauss = new("Gauss", "Gausses", BaseUnits.Undefined, new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="MagneticFieldUnit.Microtesla"/> unit of <see cref="MagneticField"/>.
        /// </summary>
        public static readonly UnitOf<MagneticField> Microtesla = new("Microtesla", "Microteslas", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MagneticFieldUnit.Milligauss"/> unit of <see cref="MagneticField"/>.
        /// </summary>
        public static readonly UnitOf<MagneticField> Milligauss = new("Milligauss", "Milligausses", BaseUnits.Undefined, new QuantityValue(1, 10000000));

        /// <summary>
        ///     The <see cref="MagneticFieldUnit.Millitesla"/> unit of <see cref="MagneticField"/>.
        /// </summary>
        public static readonly UnitOf<MagneticField> Millitesla = new("Millitesla", "Milliteslas", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MagneticFieldUnit.Nanotesla"/> unit of <see cref="MagneticField"/>.
        /// </summary>
        public static readonly UnitOf<MagneticField> Nanotesla = new("Nanotesla", "Nanoteslas", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram, current: ElectricCurrentUnit.Ampere), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MagneticFieldUnit.Tesla"/> unit of <see cref="MagneticField"/>.
        /// </summary>
        public static readonly UnitOf<MagneticField> Tesla = new("Tesla", "Teslas", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, current: ElectricCurrentUnit.Ampere), 1);
    }
}
