//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="MassConcentration"/>, such as <see cref="MassConcentrationUnits.KilogramPerCubicMeter"/>.
    /// </summary>
    public static class MassConcentrationUnits
    {
        /// <summary>
        ///     The <see cref="MassConcentrationUnit.CentigramPerDeciliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> CentigramPerDeciliter = new("CentigramPerDeciliter", "CentigramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.CentigramPerLiter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> CentigramPerLiter = new("CentigramPerLiter", "CentigramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Centigram), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.CentigramPerMicroliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> CentigramPerMicroliter = new("CentigramPerMicroliter", "CentigramsPerMicroliter", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.CentigramPerMilliliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> CentigramPerMilliliter = new("CentigramPerMilliliter", "CentigramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Centigram), 10);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.DecigramPerDeciliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> DecigramPerDeciliter = new("DecigramPerDeciliter", "DecigramsPerDeciliter", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.DecigramPerLiter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> DecigramPerLiter = new("DecigramPerLiter", "DecigramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Decigram), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.DecigramPerMicroliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> DecigramPerMicroliter = new("DecigramPerMicroliter", "DecigramsPerMicroliter", BaseUnits.Undefined, 100000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.DecigramPerMilliliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> DecigramPerMilliliter = new("DecigramPerMilliliter", "DecigramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Decigram), 100);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.GramPerCubicCentimeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> GramPerCubicCentimeter = new("GramPerCubicCentimeter", "GramsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Gram), 1000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.GramPerCubicMeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> GramPerCubicMeter = new("GramPerCubicMeter", "GramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.GramPerCubicMillimeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> GramPerCubicMillimeter = new("GramPerCubicMillimeter", "GramsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Gram), 1000000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.GramPerDeciliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> GramPerDeciliter = new("GramPerDeciliter", "GramsPerDeciliter", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.GramPerLiter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> GramPerLiter = new("GramPerLiter", "GramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Gram), 1);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.GramPerMicroliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> GramPerMicroliter = new("GramPerMicroliter", "GramsPerMicroliter", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.GramPerMilliliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> GramPerMilliliter = new("GramPerMilliliter", "GramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Gram), 1000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.KilogramPerCubicCentimeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> KilogramPerCubicCentimeter = new("KilogramPerCubicCentimeter", "KilogramsPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Kilogram), 1000000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.KilogramPerCubicMeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> KilogramPerCubicMeter = new("KilogramPerCubicMeter", "KilogramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram), 1);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.KilogramPerCubicMillimeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> KilogramPerCubicMillimeter = new("KilogramPerCubicMillimeter", "KilogramsPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram), 1000000000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.KilogramPerLiter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> KilogramPerLiter = new("KilogramPerLiter", "KilogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilogram), 1000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.KilopoundPerCubicFoot"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> KilopoundPerCubicFoot = new("KilopoundPerCubicFoot", "KilopoundsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Kilopound), new QuantityValue(3543690390625, 221225364));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.KilopoundPerCubicInch"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> KilopoundPerCubicInch = new("KilopoundPerCubicInch", "KilopoundsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Kilopound), new QuantityValue(56699046250000, 2048383));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MicrogramPerCubicMeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MicrogramPerCubicMeter = new("MicrogramPerCubicMeter", "MicrogramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MicrogramPerDeciliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MicrogramPerDeciliter = new("MicrogramPerDeciliter", "MicrogramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MicrogramPerLiter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MicrogramPerLiter = new("MicrogramPerLiter", "MicrogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Microgram), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MicrogramPerMicroliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MicrogramPerMicroliter = new("MicrogramPerMicroliter", "MicrogramsPerMicroliter", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MicrogramPerMilliliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MicrogramPerMilliliter = new("MicrogramPerMilliliter", "MicrogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Microgram), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MilligramPerCubicMeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MilligramPerCubicMeter = new("MilligramPerCubicMeter", "MilligramsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MilligramPerDeciliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MilligramPerDeciliter = new("MilligramPerDeciliter", "MilligramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MilligramPerLiter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MilligramPerLiter = new("MilligramPerLiter", "MilligramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Milligram), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MilligramPerMicroliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MilligramPerMicroliter = new("MilligramPerMicroliter", "MilligramsPerMicroliter", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.MilligramPerMilliliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> MilligramPerMilliliter = new("MilligramPerMilliliter", "MilligramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Milligram), 1);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.NanogramPerDeciliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> NanogramPerDeciliter = new("NanogramPerDeciliter", "NanogramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.NanogramPerLiter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> NanogramPerLiter = new("NanogramPerLiter", "NanogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Nanogram), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.NanogramPerMicroliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> NanogramPerMicroliter = new("NanogramPerMicroliter", "NanogramsPerMicroliter", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.NanogramPerMilliliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> NanogramPerMilliliter = new("NanogramPerMilliliter", "NanogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Nanogram), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.OuncePerImperialGallon"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> OuncePerImperialGallon = new("OuncePerImperialGallon", "OuncesPerImperialGallon", BaseUnits.Undefined, new QuantityValue(45359237, 7273744));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.OuncePerUSGallon"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> OuncePerUSGallon = new("OuncePerUSGallon", "OuncesPerUSGallon", BaseUnits.Undefined, new QuantityValue(368175625, 49161192));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.PicogramPerDeciliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> PicogramPerDeciliter = new("PicogramPerDeciliter", "PicogramsPerDeciliter", BaseUnits.Undefined, new QuantityValue(1, 100000000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.PicogramPerLiter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> PicogramPerLiter = new("PicogramPerLiter", "PicogramsPerLiter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Picogram), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.PicogramPerMicroliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> PicogramPerMicroliter = new("PicogramPerMicroliter", "PicogramsPerMicroliter", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.PicogramPerMilliliter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> PicogramPerMilliliter = new("PicogramPerMilliliter", "PicogramsPerMilliliter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Picogram), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.PoundPerCubicFoot"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> PoundPerCubicFoot = new("PoundPerCubicFoot", "PoundsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Pound), new QuantityValue(28349523125, 1769802912));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.PoundPerCubicInch"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> PoundPerCubicInch = new("PoundPerCubicInch", "PoundsPerCubicInch", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Pound), new QuantityValue(56699046250, 2048383));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.PoundPerImperialGallon"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> PoundPerImperialGallon = new("PoundPerImperialGallon", "PoundsPerImperialGallon", BaseUnits.Undefined, new QuantityValue(45359237, 454609));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.PoundPerUSGallon"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> PoundPerUSGallon = new("PoundPerUSGallon", "PoundsPerUSGallon", BaseUnits.Undefined, new QuantityValue(736351250, 6145149));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.SlugPerCubicFoot"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> SlugPerCubicFoot = new("SlugPerCubicFoot", "SlugsPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Slug), new QuantityValue(5560277019075625, 10788718551552));

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.TonnePerCubicCentimeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> TonnePerCubicCentimeter = new("TonnePerCubicCentimeter", "TonnesPerCubicCentimeter", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Tonne), 1000000000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.TonnePerCubicMeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> TonnePerCubicMeter = new("TonnePerCubicMeter", "TonnesPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Tonne), 1000);

        /// <summary>
        ///     The <see cref="MassConcentrationUnit.TonnePerCubicMillimeter"/> unit of <see cref="MassConcentration"/>.
        /// </summary>
        public static readonly UnitOf<MassConcentration> TonnePerCubicMillimeter = new("TonnePerCubicMillimeter", "TonnesPerCubicMillimeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Tonne), 1000000000000);
    }
}
