//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="MassFlow"/>, such as <see cref="MassFlowUnits.GramPerSecond"/>.
    /// </summary>
    public static class MassFlowUnits
    {
        /// <summary>
        ///     The <see cref="MassFlowUnit.CentigramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> CentigramPerDay = new("CentigramPerDay", "CentigramsPerDay", new BaseUnits(mass: MassUnit.Centigram, time: DurationUnit.Day), new QuantityValue(1, 8640000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.CentigramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> CentigramPerSecond = new("CentigramPerSecond", "CentigramsPerSecond", new BaseUnits(mass: MassUnit.Centigram, time: DurationUnit.Second), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="MassFlowUnit.DecagramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> DecagramPerDay = new("DecagramPerDay", "DecagramsPerDay", new BaseUnits(mass: MassUnit.Decagram, time: DurationUnit.Day), new QuantityValue(1, 8640));

        /// <summary>
        ///     The <see cref="MassFlowUnit.DecagramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> DecagramPerSecond = new("DecagramPerSecond", "DecagramsPerSecond", new BaseUnits(mass: MassUnit.Decagram, time: DurationUnit.Second), 10);

        /// <summary>
        ///     The <see cref="MassFlowUnit.DecigramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> DecigramPerDay = new("DecigramPerDay", "DecigramsPerDay", new BaseUnits(mass: MassUnit.Decigram, time: DurationUnit.Day), new QuantityValue(1, 864000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.DecigramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> DecigramPerSecond = new("DecigramPerSecond", "DecigramsPerSecond", new BaseUnits(mass: MassUnit.Decigram, time: DurationUnit.Second), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="MassFlowUnit.GramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> GramPerDay = new("GramPerDay", "GramsPerDay", new BaseUnits(mass: MassUnit.Gram, time: DurationUnit.Day), new QuantityValue(1, 86400));

        /// <summary>
        ///     The <see cref="MassFlowUnit.GramPerHour"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> GramPerHour = new("GramPerHour", "GramsPerHour", new BaseUnits(mass: MassUnit.Gram, time: DurationUnit.Hour), new QuantityValue(1, 3600));

        /// <summary>
        ///     The <see cref="MassFlowUnit.GramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> GramPerSecond = new("GramPerSecond", "GramsPerSecond", new BaseUnits(mass: MassUnit.Gram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="MassFlowUnit.HectogramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> HectogramPerDay = new("HectogramPerDay", "HectogramsPerDay", new BaseUnits(mass: MassUnit.Hectogram, time: DurationUnit.Day), new QuantityValue(1, 864));

        /// <summary>
        ///     The <see cref="MassFlowUnit.HectogramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> HectogramPerSecond = new("HectogramPerSecond", "HectogramsPerSecond", new BaseUnits(mass: MassUnit.Hectogram, time: DurationUnit.Second), 100);

        /// <summary>
        ///     The <see cref="MassFlowUnit.KilogramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> KilogramPerDay = new("KilogramPerDay", "KilogramsPerDay", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Day), new QuantityValue(5, 432));

        /// <summary>
        ///     The <see cref="MassFlowUnit.KilogramPerHour"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> KilogramPerHour = new("KilogramPerHour", "KilogramsPerHour", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Hour), new QuantityValue(5, 18));

        /// <summary>
        ///     The <see cref="MassFlowUnit.KilogramPerMinute"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> KilogramPerMinute = new("KilogramPerMinute", "KilogramsPerMinute", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Minute), new QuantityValue(50, 3));

        /// <summary>
        ///     The <see cref="MassFlowUnit.KilogramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> KilogramPerSecond = new("KilogramPerSecond", "KilogramsPerSecond", new BaseUnits(mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="MassFlowUnit.MegagramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MegagramPerDay = new("MegagramPerDay", "MegagramsPerDay", BaseUnits.Undefined, new QuantityValue(625, 54));

        /// <summary>
        ///     The <see cref="MassFlowUnit.MegapoundPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MegapoundPerDay = new("MegapoundPerDay", "MegapoundsPerDay", new BaseUnits(mass: MassUnit.Megapound, time: DurationUnit.Day), new QuantityValue(45359237, 8640));

        /// <summary>
        ///     The <see cref="MassFlowUnit.MegapoundPerHour"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MegapoundPerHour = new("MegapoundPerHour", "MegapoundsPerHour", new BaseUnits(mass: MassUnit.Megapound, time: DurationUnit.Hour), new QuantityValue(45359237, 360));

        /// <summary>
        ///     The <see cref="MassFlowUnit.MegapoundPerMinute"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MegapoundPerMinute = new("MegapoundPerMinute", "MegapoundsPerMinute", new BaseUnits(mass: MassUnit.Megapound, time: DurationUnit.Minute), new QuantityValue(45359237, 6));

        /// <summary>
        ///     The <see cref="MassFlowUnit.MegapoundPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MegapoundPerSecond = new("MegapoundPerSecond", "MegapoundsPerSecond", new BaseUnits(mass: MassUnit.Megapound, time: DurationUnit.Second), 453592370);

        /// <summary>
        ///     The <see cref="MassFlowUnit.MicrogramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MicrogramPerDay = new("MicrogramPerDay", "MicrogramsPerDay", new BaseUnits(mass: MassUnit.Microgram, time: DurationUnit.Day), new QuantityValue(1, 86400000000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.MicrogramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MicrogramPerSecond = new("MicrogramPerSecond", "MicrogramsPerSecond", new BaseUnits(mass: MassUnit.Microgram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.MilligramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MilligramPerDay = new("MilligramPerDay", "MilligramsPerDay", new BaseUnits(mass: MassUnit.Milligram, time: DurationUnit.Day), new QuantityValue(1, 86400000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.MilligramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> MilligramPerSecond = new("MilligramPerSecond", "MilligramsPerSecond", new BaseUnits(mass: MassUnit.Milligram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.NanogramPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> NanogramPerDay = new("NanogramPerDay", "NanogramsPerDay", new BaseUnits(mass: MassUnit.Nanogram, time: DurationUnit.Day), new QuantityValue(1, 86400000000000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.NanogramPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> NanogramPerSecond = new("NanogramPerSecond", "NanogramsPerSecond", new BaseUnits(mass: MassUnit.Nanogram, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.PoundPerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> PoundPerDay = new("PoundPerDay", "PoundsPerDay", new BaseUnits(mass: MassUnit.Pound, time: DurationUnit.Day), new QuantityValue(45359237, 8640000000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.PoundPerHour"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> PoundPerHour = new("PoundPerHour", "PoundsPerHour", new BaseUnits(mass: MassUnit.Pound, time: DurationUnit.Hour), new QuantityValue(45359237, 360000000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.PoundPerMinute"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> PoundPerMinute = new("PoundPerMinute", "PoundsPerMinute", new BaseUnits(mass: MassUnit.Pound, time: DurationUnit.Minute), new QuantityValue(45359237, 6000000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.PoundPerSecond"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> PoundPerSecond = new("PoundPerSecond", "PoundsPerSecond", new BaseUnits(mass: MassUnit.Pound, time: DurationUnit.Second), new QuantityValue(45359237, 100000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.ShortTonPerHour"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> ShortTonPerHour = new("ShortTonPerHour", "ShortTonsPerHour", new BaseUnits(mass: MassUnit.ShortTon, time: DurationUnit.Hour), new QuantityValue(45359237, 180000));

        /// <summary>
        ///     The <see cref="MassFlowUnit.TonnePerDay"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> TonnePerDay = new("TonnePerDay", "TonnesPerDay", new BaseUnits(mass: MassUnit.Tonne, time: DurationUnit.Day), new QuantityValue(625, 54));

        /// <summary>
        ///     The <see cref="MassFlowUnit.TonnePerHour"/> unit of <see cref="MassFlow"/>.
        /// </summary>
        public static readonly UnitOf<MassFlow> TonnePerHour = new("TonnePerHour", "TonnesPerHour", new BaseUnits(mass: MassUnit.Tonne, time: DurationUnit.Hour), new QuantityValue(2500, 9));
    }
}
