//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="MassMomentOfInertia"/>, such as <see cref="MassMomentOfInertiaUnits.KilogramSquareMeter"/>.
    /// </summary>
    public static class MassMomentOfInertiaUnits
    {
        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.GramSquareCentimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> GramSquareCentimeter = new("GramSquareCentimeter", "GramSquareCentimeters", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Gram), new QuantityValue(1, 10000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.GramSquareDecimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> GramSquareDecimeter = new("GramSquareDecimeter", "GramSquareDecimeters", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Gram), new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.GramSquareMeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> GramSquareMeter = new("GramSquareMeter", "GramSquareMeters", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.GramSquareMillimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> GramSquareMillimeter = new("GramSquareMillimeter", "GramSquareMillimeters", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Gram), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.KilogramSquareCentimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> KilogramSquareCentimeter = new("KilogramSquareCentimeter", "KilogramSquareCentimeters", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Kilogram), new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.KilogramSquareDecimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> KilogramSquareDecimeter = new("KilogramSquareDecimeter", "KilogramSquareDecimeters", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilogram), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.KilogramSquareMeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> KilogramSquareMeter = new("KilogramSquareMeter", "KilogramSquareMeters", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram), 1);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.KilogramSquareMillimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> KilogramSquareMillimeter = new("KilogramSquareMillimeter", "KilogramSquareMillimeters", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.KilotonneSquareCentimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> KilotonneSquareCentimeter = new("KilotonneSquareCentimeter", "KilotonneSquareCentimeters", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Kilotonne), 100);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.KilotonneSquareDecimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> KilotonneSquareDecimeter = new("KilotonneSquareDecimeter", "KilotonneSquareDecimeters", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilotonne), 10000);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.KilotonneSquareMeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> KilotonneSquareMeter = new("KilotonneSquareMeter", "KilotonneSquareMeters", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilotonne), 1000000);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.KilotonneSquareMillimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> KilotonneSquareMillimeter = new("KilotonneSquareMillimeter", "KilotonneSquareMillimeters", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilotonne), 1);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.MegatonneSquareCentimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> MegatonneSquareCentimeter = new("MegatonneSquareCentimeter", "MegatonneSquareCentimeters", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Megatonne), 100000);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.MegatonneSquareDecimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> MegatonneSquareDecimeter = new("MegatonneSquareDecimeter", "MegatonneSquareDecimeters", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Megatonne), 10000000);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.MegatonneSquareMeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> MegatonneSquareMeter = new("MegatonneSquareMeter", "MegatonneSquareMeters", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Megatonne), 1000000000);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.MegatonneSquareMillimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> MegatonneSquareMillimeter = new("MegatonneSquareMillimeter", "MegatonneSquareMillimeters", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Megatonne), 1000);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.MilligramSquareCentimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> MilligramSquareCentimeter = new("MilligramSquareCentimeter", "MilligramSquareCentimeters", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Milligram), new QuantityValue(1, 10000000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.MilligramSquareDecimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> MilligramSquareDecimeter = new("MilligramSquareDecimeter", "MilligramSquareDecimeters", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Milligram), new QuantityValue(1, 100000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.MilligramSquareMeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> MilligramSquareMeter = new("MilligramSquareMeter", "MilligramSquareMeters", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.MilligramSquareMillimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> MilligramSquareMillimeter = new("MilligramSquareMillimeter", "MilligramSquareMillimeters", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Milligram), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.PoundSquareFoot"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> PoundSquareFoot = new("PoundSquareFoot", "PoundSquareFeet", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Pound), new QuantityValue(6584392202157, 156250000000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.PoundSquareInch"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> PoundSquareInch = new("PoundSquareInch", "PoundSquareInches", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Pound), new QuantityValue(731599133573, 2500000000000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.SlugSquareFoot"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> SlugSquareFoot = new("SlugSquareFoot", "SlugSquareFeet", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Slug), new QuantityValue(3389544870828501, 2500000000000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.SlugSquareInch"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> SlugSquareInch = new("SlugSquareInch", "SlugSquareInches", new BaseUnits(length: LengthUnit.Inch, mass: MassUnit.Slug), new QuantityValue(1129848290276167, 120000000000000000));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.TonneSquareCentimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> TonneSquareCentimeter = new("TonneSquareCentimeter", "TonneSquareCentimeters", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Tonne), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.TonneSquareDecimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> TonneSquareDecimeter = new("TonneSquareDecimeter", "TonneSquareDecimeters", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Tonne), 10);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.TonneSquareMeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> TonneSquareMeter = new("TonneSquareMeter", "TonneSquareMeters", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Tonne), 1000);

        /// <summary>
        ///     The <see cref="MassMomentOfInertiaUnit.TonneSquareMillimeter"/> unit of <see cref="MassMomentOfInertia"/>.
        /// </summary>
        public static readonly UnitOf<MassMomentOfInertia> TonneSquareMillimeter = new("TonneSquareMillimeter", "TonneSquareMillimeters", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Tonne), new QuantityValue(1, 1000));
    }
}
