//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="MassFraction"/>, such as <see cref="MassFractionUnits.DecimalFraction"/>.
    /// </summary>
    public static class MassFractionUnits
    {
        /// <summary>
        ///     The <see cref="MassFractionUnit.CentigramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> CentigramPerGram = new("CentigramPerGram", "CentigramsPerGram", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="MassFractionUnit.CentigramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> CentigramPerKilogram = new("CentigramPerKilogram", "CentigramsPerKilogram", BaseUnits.Undefined, new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.DecagramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> DecagramPerGram = new("DecagramPerGram", "DecagramsPerGram", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="MassFractionUnit.DecagramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> DecagramPerKilogram = new("DecagramPerKilogram", "DecagramsPerKilogram", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="MassFractionUnit.DecigramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> DecigramPerGram = new("DecigramPerGram", "DecigramsPerGram", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="MassFractionUnit.DecigramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> DecigramPerKilogram = new("DecigramPerKilogram", "DecigramsPerKilogram", BaseUnits.Undefined, new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.DecimalFraction"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> DecimalFraction = new("DecimalFraction", "DecimalFractions", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="MassFractionUnit.GramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> GramPerGram = new("GramPerGram", "GramsPerGram", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="MassFractionUnit.GramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> GramPerKilogram = new("GramPerKilogram", "GramsPerKilogram", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.HectogramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> HectogramPerGram = new("HectogramPerGram", "HectogramsPerGram", BaseUnits.Undefined, 100);

        /// <summary>
        ///     The <see cref="MassFractionUnit.HectogramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> HectogramPerKilogram = new("HectogramPerKilogram", "HectogramsPerKilogram", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="MassFractionUnit.KilogramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> KilogramPerGram = new("KilogramPerGram", "KilogramsPerGram", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="MassFractionUnit.KilogramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> KilogramPerKilogram = new("KilogramPerKilogram", "KilogramsPerKilogram", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="MassFractionUnit.MicrogramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> MicrogramPerGram = new("MicrogramPerGram", "MicrogramsPerGram", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.MicrogramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> MicrogramPerKilogram = new("MicrogramPerKilogram", "MicrogramsPerKilogram", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.MilligramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> MilligramPerGram = new("MilligramPerGram", "MilligramsPerGram", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.MilligramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> MilligramPerKilogram = new("MilligramPerKilogram", "MilligramsPerKilogram", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.NanogramPerGram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> NanogramPerGram = new("NanogramPerGram", "NanogramsPerGram", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.NanogramPerKilogram"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> NanogramPerKilogram = new("NanogramPerKilogram", "NanogramsPerKilogram", BaseUnits.Undefined, new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.PartPerBillion"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> PartPerBillion = new("PartPerBillion", "PartsPerBillion", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.PartPerMillion"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> PartPerMillion = new("PartPerMillion", "PartsPerMillion", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.PartPerThousand"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> PartPerThousand = new("PartPerThousand", "PartsPerThousand", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.PartPerTrillion"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> PartPerTrillion = new("PartPerTrillion", "PartsPerTrillion", BaseUnits.Undefined, new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="MassFractionUnit.Percent"/> unit of <see cref="MassFraction"/>.
        /// </summary>
        public static readonly UnitOf<MassFraction> Percent = new("Percent", "Percent", BaseUnits.Undefined, new QuantityValue(1, 100));
    }
}
