//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="MolarEntropy"/>, such as <see cref="MolarEntropyUnits.JoulePerMoleKelvin"/>.
    /// </summary>
    public static class MolarEntropyUnits
    {
        /// <summary>
        ///     The <see cref="MolarEntropyUnit.JoulePerMoleKelvin"/> unit of <see cref="MolarEntropy"/>.
        /// </summary>
        public static readonly UnitOf<MolarEntropy> JoulePerMoleKelvin = new("JoulePerMoleKelvin", "JoulesPerMoleKelvin", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin, amount: AmountOfSubstanceUnit.Mole), 1);

        /// <summary>
        ///     The <see cref="MolarEntropyUnit.KilojoulePerMoleKelvin"/> unit of <see cref="MolarEntropy"/>.
        /// </summary>
        public static readonly UnitOf<MolarEntropy> KilojoulePerMoleKelvin = new("KilojoulePerMoleKelvin", "KilojoulesPerMoleKelvin", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin, amount: AmountOfSubstanceUnit.Millimole), 1000);

        /// <summary>
        ///     The <see cref="MolarEntropyUnit.MegajoulePerMoleKelvin"/> unit of <see cref="MolarEntropy"/>.
        /// </summary>
        public static readonly UnitOf<MolarEntropy> MegajoulePerMoleKelvin = new("MegajoulePerMoleKelvin", "MegajoulesPerMoleKelvin", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin, amount: AmountOfSubstanceUnit.Micromole), 1000000);
    }
}
