//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="MolarEnergy"/>, such as <see cref="MolarEnergyUnits.JoulePerMole"/>.
    /// </summary>
    public static class MolarEnergyUnits
    {
        /// <summary>
        ///     The <see cref="MolarEnergyUnit.JoulePerMole"/> unit of <see cref="MolarEnergy"/>.
        /// </summary>
        public static readonly UnitOf<MolarEnergy> JoulePerMole = new("JoulePerMole", "JoulesPerMole", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, amount: AmountOfSubstanceUnit.Mole), 1);

        /// <summary>
        ///     The <see cref="MolarEnergyUnit.KilojoulePerMole"/> unit of <see cref="MolarEnergy"/>.
        /// </summary>
        public static readonly UnitOf<MolarEnergy> KilojoulePerMole = new("KilojoulePerMole", "KilojoulesPerMole", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, amount: AmountOfSubstanceUnit.Millimole), 1000);

        /// <summary>
        ///     The <see cref="MolarEnergyUnit.MegajoulePerMole"/> unit of <see cref="MolarEnergy"/>.
        /// </summary>
        public static readonly UnitOf<MolarEnergy> MegajoulePerMole = new("MegajoulePerMole", "MegajoulesPerMole", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, amount: AmountOfSubstanceUnit.Micromole), 1000000);
    }
}
