//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Molarity"/>, such as <see cref="MolarityUnits.MolePerCubicMeter"/>.
    /// </summary>
    public static class MolarityUnits
    {
        /// <summary>
        ///     The <see cref="MolarityUnit.CentimolePerLiter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> CentimolePerLiter = new("CentimolePerLiter", "CentimolesPerLiter", new BaseUnits(length: LengthUnit.Decimeter, amount: AmountOfSubstanceUnit.Centimole), 10);

        /// <summary>
        ///     The <see cref="MolarityUnit.DecimolePerLiter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> DecimolePerLiter = new("DecimolePerLiter", "DecimolesPerLiter", new BaseUnits(length: LengthUnit.Decimeter, amount: AmountOfSubstanceUnit.Decimole), 100);

        /// <summary>
        ///     The <see cref="MolarityUnit.FemtomolePerLiter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> FemtomolePerLiter = new("FemtomolePerLiter", "FemtomolesPerLiter", new BaseUnits(length: LengthUnit.Decimeter, amount: AmountOfSubstanceUnit.Femtomole), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="MolarityUnit.KilomolePerCubicMeter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> KilomolePerCubicMeter = new("KilomolePerCubicMeter", "KilomolesPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, amount: AmountOfSubstanceUnit.Kilomole), 1000);

        /// <summary>
        ///     The <see cref="MolarityUnit.MicromolePerLiter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> MicromolePerLiter = new("MicromolePerLiter", "MicromolesPerLiter", new BaseUnits(length: LengthUnit.Decimeter, amount: AmountOfSubstanceUnit.Micromole), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MolarityUnit.MillimolePerLiter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> MillimolePerLiter = new("MillimolePerLiter", "MillimolesPerLiter", new BaseUnits(length: LengthUnit.Decimeter, amount: AmountOfSubstanceUnit.Millimole), 1);

        /// <summary>
        ///     The <see cref="MolarityUnit.MolePerCubicMeter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> MolePerCubicMeter = new("MolePerCubicMeter", "MolesPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, amount: AmountOfSubstanceUnit.Mole), 1);

        /// <summary>
        ///     The <see cref="MolarityUnit.MolePerLiter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> MolePerLiter = new("MolePerLiter", "MolesPerLiter", new BaseUnits(length: LengthUnit.Decimeter, amount: AmountOfSubstanceUnit.Mole), 1000);

        /// <summary>
        ///     The <see cref="MolarityUnit.NanomolePerLiter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> NanomolePerLiter = new("NanomolePerLiter", "NanomolesPerLiter", new BaseUnits(length: LengthUnit.Decimeter, amount: AmountOfSubstanceUnit.Nanomole), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="MolarityUnit.PicomolePerLiter"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> PicomolePerLiter = new("PicomolePerLiter", "PicomolesPerLiter", new BaseUnits(length: LengthUnit.Decimeter, amount: AmountOfSubstanceUnit.Picomole), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="MolarityUnit.PoundMolePerCubicFoot"/> unit of <see cref="Molarity"/>.
        /// </summary>
        public static readonly UnitOf<Molarity> PoundMolePerCubicFoot = new("PoundMolePerCubicFoot", "PoundMolesPerCubicFoot", new BaseUnits(length: LengthUnit.Foot, amount: AmountOfSubstanceUnit.PoundMole), new QuantityValue(3543690390625, 221225364));
    }
}
