//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Molality"/>, such as <see cref="MolalityUnits.MolePerKilogram"/>.
    /// </summary>
    public static class MolalityUnits
    {
        /// <summary>
        ///     The <see cref="MolalityUnit.MillimolePerKilogram"/> unit of <see cref="Molality"/>.
        /// </summary>
        public static readonly UnitOf<Molality> MillimolePerKilogram = new("MillimolePerKilogram", "MillimolesPerKilogram", new BaseUnits(mass: MassUnit.Kilogram, amount: AmountOfSubstanceUnit.Millimole), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="MolalityUnit.MolePerGram"/> unit of <see cref="Molality"/>.
        /// </summary>
        public static readonly UnitOf<Molality> MolePerGram = new("MolePerGram", "MolesPerGram", new BaseUnits(mass: MassUnit.Gram, amount: AmountOfSubstanceUnit.Mole), 1000);

        /// <summary>
        ///     The <see cref="MolalityUnit.MolePerKilogram"/> unit of <see cref="Molality"/>.
        /// </summary>
        public static readonly UnitOf<Molality> MolePerKilogram = new("MolePerKilogram", "MolesPerKilogram", new BaseUnits(mass: MassUnit.Kilogram, amount: AmountOfSubstanceUnit.Mole), 1);
    }
}
