//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="MolarFlow"/>, such as <see cref="MolarFlowUnits.MolePerSecond"/>.
    /// </summary>
    public static class MolarFlowUnits
    {
        /// <summary>
        ///     The <see cref="MolarFlowUnit.KilomolePerHour"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> KilomolePerHour = new("KilomolePerHour", "KilomolesPerHour", new BaseUnits(time: DurationUnit.Hour, amount: AmountOfSubstanceUnit.Kilomole), new QuantityValue(5, 18));

        /// <summary>
        ///     The <see cref="MolarFlowUnit.KilomolePerMinute"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> KilomolePerMinute = new("KilomolePerMinute", "KilomolesPerMinute", new BaseUnits(time: DurationUnit.Minute, amount: AmountOfSubstanceUnit.Kilomole), new QuantityValue(50, 3));

        /// <summary>
        ///     The <see cref="MolarFlowUnit.KilomolePerSecond"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> KilomolePerSecond = new("KilomolePerSecond", "KilomolesPerSecond", new BaseUnits(time: DurationUnit.Second, amount: AmountOfSubstanceUnit.Kilomole), 1000);

        /// <summary>
        ///     The <see cref="MolarFlowUnit.MolePerHour"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> MolePerHour = new("MolePerHour", "MolesPerHour", new BaseUnits(time: DurationUnit.Hour, amount: AmountOfSubstanceUnit.Mole), new QuantityValue(1, 3600));

        /// <summary>
        ///     The <see cref="MolarFlowUnit.MolePerMinute"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> MolePerMinute = new("MolePerMinute", "MolesPerMinute", new BaseUnits(time: DurationUnit.Minute, amount: AmountOfSubstanceUnit.Mole), new QuantityValue(1, 60));

        /// <summary>
        ///     The <see cref="MolarFlowUnit.MolePerSecond"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> MolePerSecond = new("MolePerSecond", "MolesPerSecond", new BaseUnits(time: DurationUnit.Second, amount: AmountOfSubstanceUnit.Mole), 1);

        /// <summary>
        ///     The <see cref="MolarFlowUnit.PoundMolePerHour"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> PoundMolePerHour = new("PoundMolePerHour", "PoundMolesPerHour", new BaseUnits(time: DurationUnit.Hour, amount: AmountOfSubstanceUnit.PoundMole), new QuantityValue(45359237, 360000000));

        /// <summary>
        ///     The <see cref="MolarFlowUnit.PoundMolePerMinute"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> PoundMolePerMinute = new("PoundMolePerMinute", "PoundMolesPerMinute", new BaseUnits(time: DurationUnit.Minute, amount: AmountOfSubstanceUnit.PoundMole), new QuantityValue(45359237, 6000000));

        /// <summary>
        ///     The <see cref="MolarFlowUnit.PoundMolePerSecond"/> unit of <see cref="MolarFlow"/>.
        /// </summary>
        public static readonly UnitOf<MolarFlow> PoundMolePerSecond = new("PoundMolePerSecond", "PoundMolesPerSecond", new BaseUnits(time: DurationUnit.Second, amount: AmountOfSubstanceUnit.PoundMole), new QuantityValue(45359237, 100000));
    }
}
