//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="PorousMediumPermeability"/>, such as <see cref="PorousMediumPermeabilityUnits.SquareMeter"/>.
    /// </summary>
    public static class PorousMediumPermeabilityUnits
    {
        /// <summary>
        ///     The <see cref="PorousMediumPermeabilityUnit.Darcy"/> unit of <see cref="PorousMediumPermeability"/>.
        /// </summary>
        public static readonly UnitOf<PorousMediumPermeability> Darcy = new("Darcy", "Darcys", BaseUnits.Undefined, new QuantityValue(9869233, QuantityValue.PowerOfTen(19)));

        /// <summary>
        ///     The <see cref="PorousMediumPermeabilityUnit.Microdarcy"/> unit of <see cref="PorousMediumPermeability"/>.
        /// </summary>
        public static readonly UnitOf<PorousMediumPermeability> Microdarcy = new("Microdarcy", "Microdarcys", BaseUnits.Undefined, new QuantityValue(9869233, QuantityValue.PowerOfTen(25)));

        /// <summary>
        ///     The <see cref="PorousMediumPermeabilityUnit.Millidarcy"/> unit of <see cref="PorousMediumPermeability"/>.
        /// </summary>
        public static readonly UnitOf<PorousMediumPermeability> Millidarcy = new("Millidarcy", "Millidarcys", BaseUnits.Undefined, new QuantityValue(9869233, QuantityValue.PowerOfTen(22)));

        /// <summary>
        ///     The <see cref="PorousMediumPermeabilityUnit.SquareCentimeter"/> unit of <see cref="PorousMediumPermeability"/>.
        /// </summary>
        public static readonly UnitOf<PorousMediumPermeability> SquareCentimeter = new("SquareCentimeter", "SquareCentimeters", new BaseUnits(length: LengthUnit.Centimeter), new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="PorousMediumPermeabilityUnit.SquareMeter"/> unit of <see cref="PorousMediumPermeability"/>.
        /// </summary>
        public static readonly UnitOf<PorousMediumPermeability> SquareMeter = new("SquareMeter", "SquareMeters", new BaseUnits(length: LengthUnit.Meter), 1);
    }
}
