//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="PowerDensity"/>, such as <see cref="PowerDensityUnits.WattPerCubicMeter"/>.
    /// </summary>
    public static class PowerDensityUnits
    {
        /// <summary>
        ///     The <see cref="PowerDensityUnit.BtuPerSecondCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> BtuPerSecondCubicFoot = new("BtuPerSecondCubicFoot", "BtusPerSecondCubicFoot", BaseUnits.Undefined, new QuantityValue(32970495394375, 884901456));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.BtuPerSecondCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> BtuPerSecondCubicInch = new("BtuPerSecondCubicInch", "BtusPerSecondCubicInch", BaseUnits.Undefined, new QuantityValue(131881981577500, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.DecawattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> DecawattPerCubicFoot = new("DecawattPerCubicFoot", "DecawattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(19531250000, 55306341));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.DecawattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> DecawattPerCubicInch = new("DecawattPerCubicInch", "DecawattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(1250000000000, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.DecawattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> DecawattPerCubicMeter = new("DecawattPerCubicMeter", "DecawattsPerCubicMeter", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 10);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.DecawattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> DecawattPerLiter = new("DecawattPerLiter", "DecawattsPerLiter", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.DeciwattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> DeciwattPerCubicFoot = new("DeciwattPerCubicFoot", "DeciwattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(195312500, 55306341));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.DeciwattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> DeciwattPerCubicInch = new("DeciwattPerCubicInch", "DeciwattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(12500000000, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.DeciwattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> DeciwattPerCubicMeter = new("DeciwattPerCubicMeter", "DeciwattsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Hectogram, time: DurationUnit.Second), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.DeciwattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> DeciwattPerLiter = new("DeciwattPerLiter", "DeciwattsPerLiter", BaseUnits.Undefined, 100);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.GigawattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> GigawattPerCubicFoot = new("GigawattPerCubicFoot", "GigawattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(1953125000000000000, 55306341));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.GigawattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> GigawattPerCubicInch = new("GigawattPerCubicInch", "GigawattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(new BigInteger(125) * QuantityValue.PowerOfTen(18), 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.GigawattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> GigawattPerCubicMeter = new("GigawattPerCubicMeter", "GigawattsPerCubicMeter", new BaseUnits(length: LengthUnit.Nanometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.GigawattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> GigawattPerLiter = new("GigawattPerLiter", "GigawattsPerLiter", BaseUnits.Undefined, 1000000000000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.KilowattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> KilowattPerCubicFoot = new("KilowattPerCubicFoot", "KilowattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(1953125000000, 55306341));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.KilowattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> KilowattPerCubicInch = new("KilowattPerCubicInch", "KilowattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(125000000000000, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.KilowattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> KilowattPerCubicMeter = new("KilowattPerCubicMeter", "KilowattsPerCubicMeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.KilowattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> KilowattPerLiter = new("KilowattPerLiter", "KilowattsPerLiter", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MegawattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MegawattPerCubicFoot = new("MegawattPerCubicFoot", "MegawattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(1953125000000000, 55306341));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MegawattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MegawattPerCubicInch = new("MegawattPerCubicInch", "MegawattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(125000000000000000, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MegawattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MegawattPerCubicMeter = new("MegawattPerCubicMeter", "MegawattsPerCubicMeter", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MegawattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MegawattPerLiter = new("MegawattPerLiter", "MegawattsPerLiter", BaseUnits.Undefined, 1000000000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MicrowattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MicrowattPerCubicFoot = new("MicrowattPerCubicFoot", "MicrowattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(15625, 442450728));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MicrowattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MicrowattPerCubicInch = new("MicrowattPerCubicInch", "MicrowattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(125000, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MicrowattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MicrowattPerCubicMeter = new("MicrowattPerCubicMeter", "MicrowattsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MicrowattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MicrowattPerLiter = new("MicrowattPerLiter", "MicrowattsPerLiter", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MilliwattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MilliwattPerCubicFoot = new("MilliwattPerCubicFoot", "MilliwattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(1953125, 55306341));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MilliwattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MilliwattPerCubicInch = new("MilliwattPerCubicInch", "MilliwattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(125000000, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MilliwattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MilliwattPerCubicMeter = new("MilliwattPerCubicMeter", "MilliwattsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.MilliwattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> MilliwattPerLiter = new("MilliwattPerLiter", "MilliwattsPerLiter", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.NanowattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> NanowattPerCubicFoot = new("NanowattPerCubicFoot", "NanowattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(125, 3539605824));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.NanowattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> NanowattPerCubicInch = new("NanowattPerCubicInch", "NanowattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(125, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.NanowattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> NanowattPerCubicMeter = new("NanowattPerCubicMeter", "NanowattsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Microgram, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.NanowattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> NanowattPerLiter = new("NanowattPerLiter", "NanowattsPerLiter", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.PicowattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> PicowattPerCubicFoot = new("PicowattPerCubicFoot", "PicowattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(1, 28316846592));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.PicowattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> PicowattPerCubicInch = new("PicowattPerCubicInch", "PicowattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(1, 16387064));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.PicowattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> PicowattPerCubicMeter = new("PicowattPerCubicMeter", "PicowattsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Nanogram, time: DurationUnit.Second), new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.PicowattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> PicowattPerLiter = new("PicowattPerLiter", "PicowattsPerLiter", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.TerawattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> TerawattPerCubicFoot = new("TerawattPerCubicFoot", "TerawattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(new BigInteger(1953125) * QuantityValue.PowerOfTen(15), 55306341));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.TerawattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> TerawattPerCubicInch = new("TerawattPerCubicInch", "TerawattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(new BigInteger(125) * QuantityValue.PowerOfTen(21), 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.TerawattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> TerawattPerCubicMeter = new("TerawattPerCubicMeter", "TerawattsPerCubicMeter", new BaseUnits(length: LengthUnit.Picometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000000000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.TerawattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> TerawattPerLiter = new("TerawattPerLiter", "TerawattsPerLiter", BaseUnits.Undefined, 1000000000000000);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.WattPerCubicFoot"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> WattPerCubicFoot = new("WattPerCubicFoot", "WattsPerCubicFoot", BaseUnits.Undefined, new QuantityValue(1953125000, 55306341));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.WattPerCubicInch"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> WattPerCubicInch = new("WattPerCubicInch", "WattsPerCubicInch", BaseUnits.Undefined, new QuantityValue(125000000000, 2048383));

        /// <summary>
        ///     The <see cref="PowerDensityUnit.WattPerCubicMeter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> WattPerCubicMeter = new("WattPerCubicMeter", "WattsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="PowerDensityUnit.WattPerLiter"/> unit of <see cref="PowerDensity"/>.
        /// </summary>
        public static readonly UnitOf<PowerDensity> WattPerLiter = new("WattPerLiter", "WattsPerLiter", BaseUnits.Undefined, 1000);
    }
}
