//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="PowerRatio"/>, such as <see cref="PowerRatioUnits.DecibelWatt"/>.
    /// </summary>
    public static class PowerRatioUnits
    {
        /// <summary>
        ///     The <see cref="PowerRatioUnit.DecibelMilliwatt"/> unit of <see cref="PowerRatio"/>.
        /// </summary>
        public static readonly UnitOf<PowerRatio> DecibelMilliwatt = new("DecibelMilliwatt", "DecibelMilliwatts", BaseUnits.Undefined,
            new ConversionExpression(coefficient: 1, constantTerm: 30),
            new ConversionExpression(coefficient: 1, constantTerm: -30));

        /// <summary>
        ///     The <see cref="PowerRatioUnit.DecibelWatt"/> unit of <see cref="PowerRatio"/>.
        /// </summary>
        public static readonly UnitOf<PowerRatio> DecibelWatt = new("DecibelWatt", "DecibelWatts", BaseUnits.Undefined, 1);
    }
}
