//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Pressure"/>, such as <see cref="PressureUnits.Pascal"/>.
    /// </summary>
    public static class PressureUnits
    {
        /// <summary>
        ///     The <see cref="PressureUnit.Atmosphere"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Atmosphere = new("Atmosphere", "Atmospheres", BaseUnits.Undefined, 101325);

        /// <summary>
        ///     The <see cref="PressureUnit.Bar"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Bar = new("Bar", "Bars", BaseUnits.Undefined, 100000);

        /// <summary>
        ///     The <see cref="PressureUnit.Centibar"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Centibar = new("Centibar", "Centibars", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="PressureUnit.CentimeterOfWaterColumn"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> CentimeterOfWaterColumn = new("CentimeterOfWaterColumn", "CentimetersOfWaterColumn", BaseUnits.Undefined, new QuantityValue(196133, 2000));

        /// <summary>
        ///     The <see cref="PressureUnit.Decapascal"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Decapascal = new("Decapascal", "Decapascals", new BaseUnits(length: LengthUnit.Decimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 10);

        /// <summary>
        ///     The <see cref="PressureUnit.Decibar"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Decibar = new("Decibar", "Decibars", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="PressureUnit.DynePerSquareCentimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> DynePerSquareCentimeter = new("DynePerSquareCentimeter", "DynesPerSquareCentimeter", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="PressureUnit.FootOfHead"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> FootOfHead = new("FootOfHead", "FeetOfHead", BaseUnits.Undefined, new QuantityValue(466922140449, 156250000));

        /// <summary>
        ///     The <see cref="PressureUnit.Gigapascal"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Gigapascal = new("Gigapascal", "Gigapascals", new BaseUnits(length: LengthUnit.Nanometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000000);

        /// <summary>
        ///     The <see cref="PressureUnit.Hectopascal"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Hectopascal = new("Hectopascal", "Hectopascals", new BaseUnits(length: LengthUnit.Centimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 100);

        /// <summary>
        ///     The <see cref="PressureUnit.InchOfMercury"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> InchOfMercury = new("InchOfMercury", "InchesOfMercury", BaseUnits.Undefined, new QuantityValue(3386388640341, 1000000000));

        /// <summary>
        ///     The <see cref="PressureUnit.InchOfWaterColumn"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> InchOfWaterColumn = new("InchOfWaterColumn", "InchesOfWaterColumn", BaseUnits.Undefined, new QuantityValue(24908891, 100000));

        /// <summary>
        ///     The <see cref="PressureUnit.Kilobar"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Kilobar = new("Kilobar", "Kilobars", BaseUnits.Undefined, 100000000);

        /// <summary>
        ///     The <see cref="PressureUnit.KilogramForcePerSquareCentimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilogramForcePerSquareCentimeter = new("KilogramForcePerSquareCentimeter", "KilogramsForcePerSquareCentimeter", BaseUnits.Undefined, new QuantityValue(196133, 2));

        /// <summary>
        ///     The <see cref="PressureUnit.KilogramForcePerSquareMeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilogramForcePerSquareMeter = new("KilogramForcePerSquareMeter", "KilogramsForcePerSquareMeter", BaseUnits.Undefined, new QuantityValue(196133, 20000));

        /// <summary>
        ///     The <see cref="PressureUnit.KilogramForcePerSquareMillimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilogramForcePerSquareMillimeter = new("KilogramForcePerSquareMillimeter", "KilogramsForcePerSquareMillimeter", BaseUnits.Undefined, 9806650);

        /// <summary>
        ///     The <see cref="PressureUnit.KilonewtonPerSquareCentimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilonewtonPerSquareCentimeter = new("KilonewtonPerSquareCentimeter", "KilonewtonsPerSquareCentimeter", BaseUnits.Undefined, 10000000);

        /// <summary>
        ///     The <see cref="PressureUnit.KilonewtonPerSquareMeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilonewtonPerSquareMeter = new("KilonewtonPerSquareMeter", "KilonewtonsPerSquareMeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="PressureUnit.KilonewtonPerSquareMillimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilonewtonPerSquareMillimeter = new("KilonewtonPerSquareMillimeter", "KilonewtonsPerSquareMillimeter", BaseUnits.Undefined, 1000000000);

        /// <summary>
        ///     The <see cref="PressureUnit.Kilopascal"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Kilopascal = new("Kilopascal", "Kilopascals", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="PressureUnit.KilopoundForcePerSquareFoot"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilopoundForcePerSquareFoot = new("KilopoundForcePerSquareFoot", "KilopoundsForcePerSquareFoot", BaseUnits.Undefined, new QuantityValue(8896443230521, 185806080));

        /// <summary>
        ///     The <see cref="PressureUnit.KilopoundForcePerSquareInch"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilopoundForcePerSquareInch = new("KilopoundForcePerSquareInch", "KilopoundsForcePerSquareInch", BaseUnits.Undefined, new QuantityValue(8896443230521, 1290320));

        /// <summary>
        ///     The <see cref="PressureUnit.KilopoundForcePerSquareMil"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> KilopoundForcePerSquareMil = new("KilopoundForcePerSquareMil", "KilopoundsForcePerSquareMil", BaseUnits.Undefined, new QuantityValue(111205540381512500, 16129));

        /// <summary>
        ///     The <see cref="PressureUnit.Megabar"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Megabar = new("Megabar", "Megabars", BaseUnits.Undefined, 100000000000);

        /// <summary>
        ///     The <see cref="PressureUnit.MeganewtonPerSquareMeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> MeganewtonPerSquareMeter = new("MeganewtonPerSquareMeter", "MeganewtonsPerSquareMeter", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="PressureUnit.Megapascal"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Megapascal = new("Megapascal", "Megapascals", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="PressureUnit.MeterOfHead"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> MeterOfHead = new("MeterOfHead", "MetersOfHead", BaseUnits.Undefined, new QuantityValue(1225517429, 125000));

        /// <summary>
        ///     The <see cref="PressureUnit.MeterOfWaterColumn"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> MeterOfWaterColumn = new("MeterOfWaterColumn", "MetersOfWaterColumn", BaseUnits.Undefined, new QuantityValue(196133, 20));

        /// <summary>
        ///     The <see cref="PressureUnit.Microbar"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Microbar = new("Microbar", "Microbars", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="PressureUnit.Micropascal"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Micropascal = new("Micropascal", "Micropascals", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Milligram, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="PressureUnit.Millibar"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Millibar = new("Millibar", "Millibars", BaseUnits.Undefined, 100);

        /// <summary>
        ///     The <see cref="PressureUnit.MilligramForcePerSquareFoot"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> MilligramForcePerSquareFoot = new("MilligramForcePerSquareFoot", "MilligramsForcePerSquareFoot", BaseUnits.Undefined, new QuantityValue(196133, 1858060800));

        /// <summary>
        ///     The <see cref="PressureUnit.MilligramForcePerSquareMeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> MilligramForcePerSquareMeter = new("MilligramForcePerSquareMeter", "MilligramsForcePerSquareMeter", BaseUnits.Undefined, new QuantityValue(196133, 20000000000));

        /// <summary>
        ///     The <see cref="PressureUnit.MillimeterOfMercury"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> MillimeterOfMercury = new("MillimeterOfMercury", "MillimetersOfMercury", BaseUnits.Undefined, new QuantityValue(26664477483, 200000000));

        /// <summary>
        ///     The <see cref="PressureUnit.MillimeterOfWaterColumn"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> MillimeterOfWaterColumn = new("MillimeterOfWaterColumn", "MillimetersOfWaterColumn", BaseUnits.Undefined, new QuantityValue(196133, 20000));

        /// <summary>
        ///     The <see cref="PressureUnit.Millipascal"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Millipascal = new("Millipascal", "Millipascals", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Gram, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="PressureUnit.Millitorr"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Millitorr = new("Millitorr", "Millitorrs", BaseUnits.Undefined, new QuantityValue(4053, 30400));

        /// <summary>
        ///     The <see cref="PressureUnit.NewtonPerSquareCentimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> NewtonPerSquareCentimeter = new("NewtonPerSquareCentimeter", "NewtonsPerSquareCentimeter", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="PressureUnit.NewtonPerSquareMeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> NewtonPerSquareMeter = new("NewtonPerSquareMeter", "NewtonsPerSquareMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="PressureUnit.NewtonPerSquareMillimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> NewtonPerSquareMillimeter = new("NewtonPerSquareMillimeter", "NewtonsPerSquareMillimeter", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="PressureUnit.Pascal"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Pascal = new("Pascal", "Pascals", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="PressureUnit.PoundForcePerSquareFoot"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> PoundForcePerSquareFoot = new("PoundForcePerSquareFoot", "PoundsForcePerSquareFoot", BaseUnits.Undefined, new QuantityValue(8896443230521, 185806080000));

        /// <summary>
        ///     The <see cref="PressureUnit.PoundForcePerSquareInch"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> PoundForcePerSquareInch = new("PoundForcePerSquareInch", "PoundsForcePerSquareInch", BaseUnits.Undefined, new QuantityValue(8896443230521, 1290320000));

        /// <summary>
        ///     The <see cref="PressureUnit.PoundForcePerSquareMil"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> PoundForcePerSquareMil = new("PoundForcePerSquareMil", "PoundsForcePerSquareMil", BaseUnits.Undefined, new QuantityValue(222411080763025, 32258));

        /// <summary>
        ///     The <see cref="PressureUnit.PoundPerInchSecondSquared"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> PoundPerInchSecondSquared = new("PoundPerInchSecondSquared", "PoundsPerInchSecondSquared", BaseUnits.Undefined, new QuantityValue(8896443230521, 498177842352));

        /// <summary>
        ///     The <see cref="PressureUnit.TechnicalAtmosphere"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> TechnicalAtmosphere = new("TechnicalAtmosphere", "TechnicalAtmospheres", BaseUnits.Undefined, new QuantityValue(196133, 2));

        /// <summary>
        ///     The <see cref="PressureUnit.TonneForcePerSquareCentimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> TonneForcePerSquareCentimeter = new("TonneForcePerSquareCentimeter", "TonnesForcePerSquareCentimeter", BaseUnits.Undefined, 98066500);

        /// <summary>
        ///     The <see cref="PressureUnit.TonneForcePerSquareMeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> TonneForcePerSquareMeter = new("TonneForcePerSquareMeter", "TonnesForcePerSquareMeter", BaseUnits.Undefined, new QuantityValue(196133, 20));

        /// <summary>
        ///     The <see cref="PressureUnit.TonneForcePerSquareMillimeter"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> TonneForcePerSquareMillimeter = new("TonneForcePerSquareMillimeter", "TonnesForcePerSquareMillimeter", BaseUnits.Undefined, 9806650000);

        /// <summary>
        ///     The <see cref="PressureUnit.Torr"/> unit of <see cref="Pressure"/>.
        /// </summary>
        public static readonly UnitOf<Pressure> Torr = new("Torr", "Torrs", BaseUnits.Undefined, new QuantityValue(20265, 152));
    }
}
