//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Radioactivity"/>, such as <see cref="RadioactivityUnits.Becquerel"/>.
    /// </summary>
    public static class RadioactivityUnits
    {
        /// <summary>
        ///     The <see cref="RadioactivityUnit.Becquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Becquerel = new("Becquerel", "Becquerels", new BaseUnits(time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Curie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Curie = new("Curie", "Curies", new BaseUnits(time: DurationUnit.Second), 37000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Exabecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Exabecquerel = new("Exabecquerel", "Exabecquerels", BaseUnits.Undefined, 1000000000000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Gigabecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Gigabecquerel = new("Gigabecquerel", "Gigabecquerels", new BaseUnits(time: DurationUnit.Nanosecond), 1000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Gigacurie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Gigacurie = new("Gigacurie", "Gigacuries", new BaseUnits(time: DurationUnit.Nanosecond), new QuantityValue(new BigInteger(37) * QuantityValue.PowerOfTen(18), 1));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Gigarutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Gigarutherford = new("Gigarutherford", "Gigarutherfords", new BaseUnits(time: DurationUnit.Nanosecond), 1000000000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Kilobecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Kilobecquerel = new("Kilobecquerel", "Kilobecquerels", new BaseUnits(time: DurationUnit.Millisecond), 1000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Kilocurie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Kilocurie = new("Kilocurie", "Kilocuries", new BaseUnits(time: DurationUnit.Millisecond), 37000000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Kilorutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Kilorutherford = new("Kilorutherford", "Kilorutherfords", new BaseUnits(time: DurationUnit.Millisecond), 1000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Megabecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Megabecquerel = new("Megabecquerel", "Megabecquerels", new BaseUnits(time: DurationUnit.Microsecond), 1000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Megacurie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Megacurie = new("Megacurie", "Megacuries", new BaseUnits(time: DurationUnit.Microsecond), 37000000000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Megarutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Megarutherford = new("Megarutherford", "Megarutherfords", new BaseUnits(time: DurationUnit.Microsecond), 1000000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Microbecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Microbecquerel = new("Microbecquerel", "Microbecquerels", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Microcurie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Microcurie = new("Microcurie", "Microcuries", BaseUnits.Undefined, 37000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Microrutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Microrutherford = new("Microrutherford", "Microrutherfords", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Millibecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Millibecquerel = new("Millibecquerel", "Millibecquerels", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Millicurie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Millicurie = new("Millicurie", "Millicuries", BaseUnits.Undefined, 37000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Millirutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Millirutherford = new("Millirutherford", "Millirutherfords", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Nanobecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Nanobecquerel = new("Nanobecquerel", "Nanobecquerels", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Nanocurie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Nanocurie = new("Nanocurie", "Nanocuries", BaseUnits.Undefined, 37);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Nanorutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Nanorutherford = new("Nanorutherford", "Nanorutherfords", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Petabecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Petabecquerel = new("Petabecquerel", "Petabecquerels", BaseUnits.Undefined, 1000000000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Picobecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Picobecquerel = new("Picobecquerel", "Picobecquerels", BaseUnits.Undefined, new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Picocurie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Picocurie = new("Picocurie", "Picocuries", BaseUnits.Undefined, new QuantityValue(37, 1000));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Picorutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Picorutherford = new("Picorutherford", "Picorutherfords", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Rutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Rutherford = new("Rutherford", "Rutherfords", new BaseUnits(time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Terabecquerel"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Terabecquerel = new("Terabecquerel", "Terabecquerels", new BaseUnits(time: DurationUnit.Picosecond), 1000000000000);

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Teracurie"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Teracurie = new("Teracurie", "Teracuries", new BaseUnits(time: DurationUnit.Picosecond), new QuantityValue(new BigInteger(37) * QuantityValue.PowerOfTen(21), 1));

        /// <summary>
        ///     The <see cref="RadioactivityUnit.Terarutherford"/> unit of <see cref="Radioactivity"/>.
        /// </summary>
        public static readonly UnitOf<Radioactivity> Terarutherford = new("Terarutherford", "Terarutherfords", new BaseUnits(time: DurationUnit.Picosecond), 1000000000000000000);
    }
}
