//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="RadiationEquivalentDoseRate"/>, such as <see cref="RadiationEquivalentDoseRateUnits.SievertPerSecond"/>.
    /// </summary>
    public static class RadiationEquivalentDoseRateUnits
    {
        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.MicrosievertPerHour"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> MicrosievertPerHour = new("MicrosievertPerHour", "MicrosievertsPerHour", BaseUnits.Undefined, new QuantityValue(1, 3600000000));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.MicrosievertPerSecond"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> MicrosievertPerSecond = new("MicrosievertPerSecond", "MicrosievertsPerSecond", new BaseUnits(length: LengthUnit.Millimeter, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.MilliroentgenEquivalentManPerHour"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> MilliroentgenEquivalentManPerHour = new("MilliroentgenEquivalentManPerHour", "MilliroentgensEquivalentManPerHour", BaseUnits.Undefined, new QuantityValue(1, 360000000));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.MillisievertPerHour"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> MillisievertPerHour = new("MillisievertPerHour", "MillisievertsPerHour", BaseUnits.Undefined, new QuantityValue(1, 3600000));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.MillisievertPerSecond"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> MillisievertPerSecond = new("MillisievertPerSecond", "MillisievertsPerSecond", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.NanosievertPerHour"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> NanosievertPerHour = new("NanosievertPerHour", "NanosievertsPerHour", BaseUnits.Undefined, new QuantityValue(1, 3600000000000));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.NanosievertPerSecond"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> NanosievertPerSecond = new("NanosievertPerSecond", "NanosievertsPerSecond", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.RoentgenEquivalentManPerHour"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> RoentgenEquivalentManPerHour = new("RoentgenEquivalentManPerHour", "RoentgensEquivalentManPerHour", BaseUnits.Undefined, new QuantityValue(1, 360000));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.SievertPerHour"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> SievertPerHour = new("SievertPerHour", "SievertsPerHour", BaseUnits.Undefined, new QuantityValue(1, 3600));

        /// <summary>
        ///     The <see cref="RadiationEquivalentDoseRateUnit.SievertPerSecond"/> unit of <see cref="RadiationEquivalentDoseRate"/>.
        /// </summary>
        public static readonly UnitOf<RadiationEquivalentDoseRate> SievertPerSecond = new("SievertPerSecond", "SievertsPerSecond", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Second), 1);
    }
}
