//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Ratio"/>, such as <see cref="RatioUnits.DecimalFraction"/>.
    /// </summary>
    public static class RatioUnits
    {
        /// <summary>
        ///     The <see cref="RatioUnit.DecimalFraction"/> unit of <see cref="Ratio"/>.
        /// </summary>
        public static readonly UnitOf<Ratio> DecimalFraction = new("DecimalFraction", "DecimalFractions", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="RatioUnit.PartPerBillion"/> unit of <see cref="Ratio"/>.
        /// </summary>
        public static readonly UnitOf<Ratio> PartPerBillion = new("PartPerBillion", "PartsPerBillion", BaseUnits.Undefined, new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="RatioUnit.PartPerMillion"/> unit of <see cref="Ratio"/>.
        /// </summary>
        public static readonly UnitOf<Ratio> PartPerMillion = new("PartPerMillion", "PartsPerMillion", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="RatioUnit.PartPerThousand"/> unit of <see cref="Ratio"/>.
        /// </summary>
        public static readonly UnitOf<Ratio> PartPerThousand = new("PartPerThousand", "PartsPerThousand", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="RatioUnit.PartPerTrillion"/> unit of <see cref="Ratio"/>.
        /// </summary>
        public static readonly UnitOf<Ratio> PartPerTrillion = new("PartPerTrillion", "PartsPerTrillion", BaseUnits.Undefined, new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="RatioUnit.Percent"/> unit of <see cref="Ratio"/>.
        /// </summary>
        public static readonly UnitOf<Ratio> Percent = new("Percent", "Percent", BaseUnits.Undefined, new QuantityValue(1, 100));
    }
}
