//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="RotationalStiffnessPerLength"/>, such as <see cref="RotationalStiffnessPerLengthUnits.NewtonMeterPerRadianPerMeter"/>.
    /// </summary>
    public static class RotationalStiffnessPerLengthUnits
    {
        /// <summary>
        ///     The <see cref="RotationalStiffnessPerLengthUnit.KilonewtonMeterPerRadianPerMeter"/> unit of <see cref="RotationalStiffnessPerLength"/>.
        /// </summary>
        public static readonly UnitOf<RotationalStiffnessPerLength> KilonewtonMeterPerRadianPerMeter = new("KilonewtonMeterPerRadianPerMeter", "KilonewtonMetersPerRadianPerMeter", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="RotationalStiffnessPerLengthUnit.KilopoundForceFootPerDegreesPerFoot"/> unit of <see cref="RotationalStiffnessPerLength"/>.
        /// </summary>
        public static readonly UnitOf<RotationalStiffnessPerLength> KilopoundForceFootPerDegreesPerFoot = new("KilopoundForceFootPerDegreesPerFoot", "KilopoundForceFeetPerDegreesPerFeet", BaseUnits.Undefined, new QuantityValue(QuantityValue.PowerOfTen(7) * new BigInteger(80067989074689), 3141592653589793));

        /// <summary>
        ///     The <see cref="RotationalStiffnessPerLengthUnit.MeganewtonMeterPerRadianPerMeter"/> unit of <see cref="RotationalStiffnessPerLength"/>.
        /// </summary>
        public static readonly UnitOf<RotationalStiffnessPerLength> MeganewtonMeterPerRadianPerMeter = new("MeganewtonMeterPerRadianPerMeter", "MeganewtonMetersPerRadianPerMeter", new BaseUnits(length: LengthUnit.Megameter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="RotationalStiffnessPerLengthUnit.NewtonMeterPerRadianPerMeter"/> unit of <see cref="RotationalStiffnessPerLength"/>.
        /// </summary>
        public static readonly UnitOf<RotationalStiffnessPerLength> NewtonMeterPerRadianPerMeter = new("NewtonMeterPerRadianPerMeter", "NewtonMetersPerRadianPerMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="RotationalStiffnessPerLengthUnit.PoundForceFootPerDegreesPerFoot"/> unit of <see cref="RotationalStiffnessPerLength"/>.
        /// </summary>
        public static readonly UnitOf<RotationalStiffnessPerLength> PoundForceFootPerDegreesPerFoot = new("PoundForceFootPerDegreesPerFoot", "PoundForceFeetPerDegreesPerFeet", BaseUnits.Undefined, new QuantityValue(800679890746890000, 3141592653589793));
    }
}
