//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="SpecificWeight"/>, such as <see cref="SpecificWeightUnits.NewtonPerCubicMeter"/>.
    /// </summary>
    public static class SpecificWeightUnits
    {
        /// <summary>
        ///     The <see cref="SpecificWeightUnit.KilogramForcePerCubicCentimeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> KilogramForcePerCubicCentimeter = new("KilogramForcePerCubicCentimeter", "KilogramsForcePerCubicCentimeter", BaseUnits.Undefined, 9806650);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.KilogramForcePerCubicMeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> KilogramForcePerCubicMeter = new("KilogramForcePerCubicMeter", "KilogramsForcePerCubicMeter", BaseUnits.Undefined, new QuantityValue(196133, 20000));

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.KilogramForcePerCubicMillimeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> KilogramForcePerCubicMillimeter = new("KilogramForcePerCubicMillimeter", "KilogramsForcePerCubicMillimeter", BaseUnits.Undefined, 9806650000);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.KilonewtonPerCubicCentimeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> KilonewtonPerCubicCentimeter = new("KilonewtonPerCubicCentimeter", "KilonewtonsPerCubicCentimeter", BaseUnits.Undefined, 1000000000);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.KilonewtonPerCubicMeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> KilonewtonPerCubicMeter = new("KilonewtonPerCubicMeter", "KilonewtonsPerCubicMeter", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.KilonewtonPerCubicMillimeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> KilonewtonPerCubicMillimeter = new("KilonewtonPerCubicMillimeter", "KilonewtonsPerCubicMillimeter", BaseUnits.Undefined, 1000000000000);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.KilopoundForcePerCubicFoot"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> KilopoundForcePerCubicFoot = new("KilopoundForcePerCubicFoot", "KilopoundsForcePerCubicFoot", BaseUnits.Undefined, new QuantityValue(1112055403815125, 7079211648));

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.KilopoundForcePerCubicInch"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> KilopoundForcePerCubicInch = new("KilopoundForcePerCubicInch", "KilopoundsForcePerCubicInch", BaseUnits.Undefined, new QuantityValue(1112055403815125, 4096766));

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.MeganewtonPerCubicMeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> MeganewtonPerCubicMeter = new("MeganewtonPerCubicMeter", "MeganewtonsPerCubicMeter", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.NewtonPerCubicCentimeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> NewtonPerCubicCentimeter = new("NewtonPerCubicCentimeter", "NewtonsPerCubicCentimeter", BaseUnits.Undefined, 1000000);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.NewtonPerCubicMeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> NewtonPerCubicMeter = new("NewtonPerCubicMeter", "NewtonsPerCubicMeter", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.NewtonPerCubicMillimeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> NewtonPerCubicMillimeter = new("NewtonPerCubicMillimeter", "NewtonsPerCubicMillimeter", BaseUnits.Undefined, 1000000000);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.PoundForcePerCubicFoot"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> PoundForcePerCubicFoot = new("PoundForcePerCubicFoot", "PoundsForcePerCubicFoot", BaseUnits.Undefined, new QuantityValue(8896443230521, 56633693184));

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.PoundForcePerCubicInch"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> PoundForcePerCubicInch = new("PoundForcePerCubicInch", "PoundsForcePerCubicInch", BaseUnits.Undefined, new QuantityValue(8896443230521, 32774128));

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.TonneForcePerCubicCentimeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> TonneForcePerCubicCentimeter = new("TonneForcePerCubicCentimeter", "TonnesForcePerCubicCentimeter", BaseUnits.Undefined, 9806650000);

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.TonneForcePerCubicMeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> TonneForcePerCubicMeter = new("TonneForcePerCubicMeter", "TonnesForcePerCubicMeter", BaseUnits.Undefined, new QuantityValue(196133, 20));

        /// <summary>
        ///     The <see cref="SpecificWeightUnit.TonneForcePerCubicMillimeter"/> unit of <see cref="SpecificWeight"/>.
        /// </summary>
        public static readonly UnitOf<SpecificWeight> TonneForcePerCubicMillimeter = new("TonneForcePerCubicMillimeter", "TonnesForcePerCubicMillimeter", BaseUnits.Undefined, 9806650000000);
    }
}
