//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="SpecificVolume"/>, such as <see cref="SpecificVolumeUnits.CubicMeterPerKilogram"/>.
    /// </summary>
    public static class SpecificVolumeUnits
    {
        /// <summary>
        ///     The <see cref="SpecificVolumeUnit.CubicFootPerPound"/> unit of <see cref="SpecificVolume"/>.
        /// </summary>
        public static readonly UnitOf<SpecificVolume> CubicFootPerPound = new("CubicFootPerPound", "CubicFeetPerPound", new BaseUnits(length: LengthUnit.Foot, mass: MassUnit.Pound), new QuantityValue(1769802912, 28349523125));

        /// <summary>
        ///     The <see cref="SpecificVolumeUnit.CubicMeterPerKilogram"/> unit of <see cref="SpecificVolume"/>.
        /// </summary>
        public static readonly UnitOf<SpecificVolume> CubicMeterPerKilogram = new("CubicMeterPerKilogram", "CubicMetersPerKilogram", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram), 1);

        /// <summary>
        ///     The <see cref="SpecificVolumeUnit.CubicMillimeterPerKilogram"/> unit of <see cref="SpecificVolume"/>.
        /// </summary>
        public static readonly UnitOf<SpecificVolume> CubicMillimeterPerKilogram = new("CubicMillimeterPerKilogram", "CubicMillimetersPerKilogram", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram), new QuantityValue(1, 1000000000));
    }
}
