//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="SpecificEnergy"/>, such as <see cref="SpecificEnergyUnits.JoulePerKilogram"/>.
    /// </summary>
    public static class SpecificEnergyUnits
    {
        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.BtuPerPound"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> BtuPerPound = new("BtuPerPound", "BtuPerPound", BaseUnits.Undefined, 2326);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.CaloriePerGram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> CaloriePerGram = new("CaloriePerGram", "CaloriesPerGram", BaseUnits.Undefined, 4184);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.GigawattDayPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> GigawattDayPerKilogram = new("GigawattDayPerKilogram", "GigawattDaysPerKilogram", BaseUnits.Undefined, 86400000000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.GigawattDayPerShortTon"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> GigawattDayPerShortTon = new("GigawattDayPerShortTon", "GigawattDaysPerShortTon", BaseUnits.Undefined, new QuantityValue(4320000000000000000, 45359237));

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.GigawattDayPerTonne"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> GigawattDayPerTonne = new("GigawattDayPerTonne", "GigawattDaysPerTonne", BaseUnits.Undefined, 86400000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.GigawattHourPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> GigawattHourPerKilogram = new("GigawattHourPerKilogram", "GigawattHoursPerKilogram", BaseUnits.Undefined, 3600000000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.GigawattHourPerPound"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> GigawattHourPerPound = new("GigawattHourPerPound", "GigawattHoursPerPound", BaseUnits.Undefined, 7936640000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.JoulePerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> JoulePerKilogram = new("JoulePerKilogram", "JoulesPerKilogram", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.KilocaloriePerGram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> KilocaloriePerGram = new("KilocaloriePerGram", "KilocaloriesPerGram", BaseUnits.Undefined, 4184000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.KilojoulePerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> KilojoulePerKilogram = new("KilojoulePerKilogram", "KilojoulesPerKilogram", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.KilowattDayPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> KilowattDayPerKilogram = new("KilowattDayPerKilogram", "KilowattDaysPerKilogram", BaseUnits.Undefined, 86400000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.KilowattDayPerShortTon"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> KilowattDayPerShortTon = new("KilowattDayPerShortTon", "KilowattDaysPerShortTon", BaseUnits.Undefined, new QuantityValue(4320000000000, 45359237));

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.KilowattDayPerTonne"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> KilowattDayPerTonne = new("KilowattDayPerTonne", "KilowattDaysPerTonne", BaseUnits.Undefined, 86400);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.KilowattHourPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> KilowattHourPerKilogram = new("KilowattHourPerKilogram", "KilowattHoursPerKilogram", BaseUnits.Undefined, 3600000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.KilowattHourPerPound"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> KilowattHourPerPound = new("KilowattHourPerPound", "KilowattHoursPerPound", BaseUnits.Undefined, 7936640);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.MegajoulePerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> MegajoulePerKilogram = new("MegajoulePerKilogram", "MegajoulesPerKilogram", new BaseUnits(length: LengthUnit.Kilometer, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.MegajoulePerTonne"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> MegajoulePerTonne = new("MegajoulePerTonne", "MegajoulesPerTonne", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.MegawattDayPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> MegawattDayPerKilogram = new("MegawattDayPerKilogram", "MegawattDaysPerKilogram", BaseUnits.Undefined, 86400000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.MegawattDayPerShortTon"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> MegawattDayPerShortTon = new("MegawattDayPerShortTon", "MegawattDaysPerShortTon", BaseUnits.Undefined, new QuantityValue(4320000000000000, 45359237));

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.MegawattDayPerTonne"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> MegawattDayPerTonne = new("MegawattDayPerTonne", "MegawattDaysPerTonne", BaseUnits.Undefined, 86400000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.MegawattHourPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> MegawattHourPerKilogram = new("MegawattHourPerKilogram", "MegawattHoursPerKilogram", BaseUnits.Undefined, 3600000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.MegawattHourPerPound"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> MegawattHourPerPound = new("MegawattHourPerPound", "MegawattHoursPerPound", BaseUnits.Undefined, 7936640000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.TerawattDayPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> TerawattDayPerKilogram = new("TerawattDayPerKilogram", "TerawattDaysPerKilogram", BaseUnits.Undefined, 86400000000000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.TerawattDayPerShortTon"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> TerawattDayPerShortTon = new("TerawattDayPerShortTon", "TerawattDaysPerShortTon", BaseUnits.Undefined, new QuantityValue(new BigInteger(432) * QuantityValue.PowerOfTen(19), 45359237));

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.TerawattDayPerTonne"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> TerawattDayPerTonne = new("TerawattDayPerTonne", "TerawattDaysPerTonne", BaseUnits.Undefined, 86400000000000);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.WattDayPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> WattDayPerKilogram = new("WattDayPerKilogram", "WattDaysPerKilogram", BaseUnits.Undefined, 86400);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.WattDayPerShortTon"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> WattDayPerShortTon = new("WattDayPerShortTon", "WattDaysPerShortTon", BaseUnits.Undefined, new QuantityValue(4320000000, 45359237));

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.WattDayPerTonne"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> WattDayPerTonne = new("WattDayPerTonne", "WattDaysPerTonne", BaseUnits.Undefined, new QuantityValue(432, 5));

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.WattHourPerKilogram"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> WattHourPerKilogram = new("WattHourPerKilogram", "WattHoursPerKilogram", BaseUnits.Undefined, 3600);

        /// <summary>
        ///     The <see cref="SpecificEnergyUnit.WattHourPerPound"/> unit of <see cref="SpecificEnergy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEnergy> WattHourPerPound = new("WattHourPerPound", "WattHoursPerPound", BaseUnits.Undefined, new QuantityValue(198416, 25));
    }
}
