//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="SpecificFuelConsumption"/>, such as <see cref="SpecificFuelConsumptionUnits.GramPerKilonewtonSecond"/>.
    /// </summary>
    public static class SpecificFuelConsumptionUnits
    {
        /// <summary>
        ///     The <see cref="SpecificFuelConsumptionUnit.GramPerKilonewtonSecond"/> unit of <see cref="SpecificFuelConsumption"/>.
        /// </summary>
        public static readonly UnitOf<SpecificFuelConsumption> GramPerKilonewtonSecond = new("GramPerKilonewtonSecond", "GramsPerKilonewtonSecond", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="SpecificFuelConsumptionUnit.KilogramPerKilogramForceHour"/> unit of <see cref="SpecificFuelConsumption"/>.
        /// </summary>
        public static readonly UnitOf<SpecificFuelConsumption> KilogramPerKilogramForceHour = new("KilogramPerKilogramForceHour", "KilogramsPerKilogramForceHour", BaseUnits.Undefined, new QuantityValue(50000000, 1765197));

        /// <summary>
        ///     The <see cref="SpecificFuelConsumptionUnit.KilogramPerKilonewtonSecond"/> unit of <see cref="SpecificFuelConsumption"/>.
        /// </summary>
        public static readonly UnitOf<SpecificFuelConsumption> KilogramPerKilonewtonSecond = new("KilogramPerKilonewtonSecond", "KilogramsPerKilonewtonSecond", new BaseUnits(length: LengthUnit.Millimeter, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="SpecificFuelConsumptionUnit.PoundMassPerPoundForceHour"/> unit of <see cref="SpecificFuelConsumption"/>.
        /// </summary>
        public static readonly UnitOf<SpecificFuelConsumption> PoundMassPerPoundForceHour = new("PoundMassPerPoundForceHour", "PoundsMassPerPoundForceHour", BaseUnits.Undefined, new QuantityValue(50000000, 1765197));
    }
}
