//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="SpecificEntropy"/>, such as <see cref="SpecificEntropyUnits.JoulePerKilogramKelvin"/>.
    /// </summary>
    public static class SpecificEntropyUnits
    {
        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.BtuPerPoundFahrenheit"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> BtuPerPoundFahrenheit = new("BtuPerPoundFahrenheit", "BtusPerPoundFahrenheit", BaseUnits.Undefined, new QuantityValue(20934, 5));

        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.CaloriePerGramKelvin"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> CaloriePerGramKelvin = new("CaloriePerGramKelvin", "CaloriesPerGramKelvin", BaseUnits.Undefined, 4184);

        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.JoulePerKilogramDegreeCelsius"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> JoulePerKilogramDegreeCelsius = new("JoulePerKilogramDegreeCelsius", "JoulesPerKilogramDegreeCelsius", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Second, temperature: TemperatureUnit.DegreeCelsius), 1);

        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.JoulePerKilogramKelvin"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> JoulePerKilogramKelvin = new("JoulePerKilogramKelvin", "JoulesPerKilogramKelvin", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin), 1);

        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.KilocaloriePerGramKelvin"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> KilocaloriePerGramKelvin = new("KilocaloriePerGramKelvin", "KilocaloriesPerGramKelvin", BaseUnits.Undefined, 4184000);

        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.KilojoulePerKilogramDegreeCelsius"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> KilojoulePerKilogramDegreeCelsius = new("KilojoulePerKilogramDegreeCelsius", "KilojoulesPerKilogramDegreeCelsius", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.KilojoulePerKilogramKelvin"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> KilojoulePerKilogramKelvin = new("KilojoulePerKilogramKelvin", "KilojoulesPerKilogramKelvin", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.MegajoulePerKilogramDegreeCelsius"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> MegajoulePerKilogramDegreeCelsius = new("MegajoulePerKilogramDegreeCelsius", "MegajoulesPerKilogramDegreeCelsius", new BaseUnits(length: LengthUnit.Kilometer, time: DurationUnit.Second, temperature: TemperatureUnit.DegreeCelsius), 1000000);

        /// <summary>
        ///     The <see cref="SpecificEntropyUnit.MegajoulePerKilogramKelvin"/> unit of <see cref="SpecificEntropy"/>.
        /// </summary>
        public static readonly UnitOf<SpecificEntropy> MegajoulePerKilogramKelvin = new("MegajoulePerKilogramKelvin", "MegajoulesPerKilogramKelvin", new BaseUnits(length: LengthUnit.Kilometer, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin), 1000000);
    }
}
