//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Speed"/>, such as <see cref="SpeedUnits.MeterPerSecond"/>.
    /// </summary>
    public static class SpeedUnits
    {
        /// <summary>
        ///     The <see cref="SpeedUnit.CentimeterPerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> CentimeterPerHour = new("CentimeterPerHour", "CentimetersPerHour", new BaseUnits(length: LengthUnit.Centimeter, time: DurationUnit.Hour), new QuantityValue(1, 360000));

        /// <summary>
        ///     The <see cref="SpeedUnit.CentimeterPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> CentimeterPerMinute = new("CentimeterPerMinute", "CentimetersPerMinute", new BaseUnits(length: LengthUnit.Centimeter, time: DurationUnit.Minute), new QuantityValue(1, 6000));

        /// <summary>
        ///     The <see cref="SpeedUnit.CentimeterPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> CentimeterPerSecond = new("CentimeterPerSecond", "CentimetersPerSecond", new BaseUnits(length: LengthUnit.Centimeter, time: DurationUnit.Second), new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="SpeedUnit.DecimeterPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> DecimeterPerMinute = new("DecimeterPerMinute", "DecimetersPerMinute", new BaseUnits(length: LengthUnit.Decimeter, time: DurationUnit.Minute), new QuantityValue(1, 600));

        /// <summary>
        ///     The <see cref="SpeedUnit.DecimeterPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> DecimeterPerSecond = new("DecimeterPerSecond", "DecimetersPerSecond", new BaseUnits(length: LengthUnit.Decimeter, time: DurationUnit.Second), new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="SpeedUnit.FootPerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> FootPerHour = new("FootPerHour", "FeetPerHour", new BaseUnits(length: LengthUnit.Foot, time: DurationUnit.Hour), new QuantityValue(127, 1500000));

        /// <summary>
        ///     The <see cref="SpeedUnit.FootPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> FootPerMinute = new("FootPerMinute", "FeetPerMinute", new BaseUnits(length: LengthUnit.Foot, time: DurationUnit.Minute), new QuantityValue(127, 25000));

        /// <summary>
        ///     The <see cref="SpeedUnit.FootPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> FootPerSecond = new("FootPerSecond", "FeetPerSecond", new BaseUnits(length: LengthUnit.Foot, time: DurationUnit.Second), new QuantityValue(381, 1250));

        /// <summary>
        ///     The <see cref="SpeedUnit.InchPerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> InchPerHour = new("InchPerHour", "InchesPerHour", new BaseUnits(length: LengthUnit.Inch, time: DurationUnit.Hour), new QuantityValue(127, 18000000));

        /// <summary>
        ///     The <see cref="SpeedUnit.InchPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> InchPerMinute = new("InchPerMinute", "InchesPerMinute", new BaseUnits(length: LengthUnit.Inch, time: DurationUnit.Minute), new QuantityValue(127, 300000));

        /// <summary>
        ///     The <see cref="SpeedUnit.InchPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> InchPerSecond = new("InchPerSecond", "InchesPerSecond", new BaseUnits(length: LengthUnit.Inch, time: DurationUnit.Second), new QuantityValue(127, 5000));

        /// <summary>
        ///     The <see cref="SpeedUnit.KilometerPerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> KilometerPerHour = new("KilometerPerHour", "KilometersPerHour", new BaseUnits(length: LengthUnit.Kilometer, time: DurationUnit.Hour), new QuantityValue(5, 18));

        /// <summary>
        ///     The <see cref="SpeedUnit.KilometerPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> KilometerPerMinute = new("KilometerPerMinute", "KilometersPerMinute", new BaseUnits(length: LengthUnit.Kilometer, time: DurationUnit.Minute), new QuantityValue(50, 3));

        /// <summary>
        ///     The <see cref="SpeedUnit.KilometerPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> KilometerPerSecond = new("KilometerPerSecond", "KilometersPerSecond", new BaseUnits(length: LengthUnit.Kilometer, time: DurationUnit.Second), 1000);

        /// <summary>
        ///     The <see cref="SpeedUnit.Knot"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> Knot = new("Knot", "Knots", new BaseUnits(length: LengthUnit.NauticalMile, time: DurationUnit.Hour), new QuantityValue(463, 900));

        /// <summary>
        ///     The <see cref="SpeedUnit.Mach"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> Mach = new("Mach", "Mach", BaseUnits.Undefined, new QuantityValue(34029, 100));

        /// <summary>
        ///     The <see cref="SpeedUnit.MeterPerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MeterPerHour = new("MeterPerHour", "MetersPerHour", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Hour), new QuantityValue(1, 3600));

        /// <summary>
        ///     The <see cref="SpeedUnit.MeterPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MeterPerMinute = new("MeterPerMinute", "MetersPerMinute", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Minute), new QuantityValue(1, 60));

        /// <summary>
        ///     The <see cref="SpeedUnit.MeterPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MeterPerSecond = new("MeterPerSecond", "MetersPerSecond", new BaseUnits(length: LengthUnit.Meter, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="SpeedUnit.MicrometerPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MicrometerPerMinute = new("MicrometerPerMinute", "MicrometersPerMinute", new BaseUnits(length: LengthUnit.Micrometer, time: DurationUnit.Minute), new QuantityValue(1, 60000000));

        /// <summary>
        ///     The <see cref="SpeedUnit.MicrometerPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MicrometerPerSecond = new("MicrometerPerSecond", "MicrometersPerSecond", new BaseUnits(length: LengthUnit.Micrometer, time: DurationUnit.Second), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="SpeedUnit.MilePerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MilePerHour = new("MilePerHour", "MilesPerHour", new BaseUnits(length: LengthUnit.Mile, time: DurationUnit.Hour), new QuantityValue(1397, 3125));

        /// <summary>
        ///     The <see cref="SpeedUnit.MillimeterPerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MillimeterPerHour = new("MillimeterPerHour", "MillimetersPerHour", new BaseUnits(length: LengthUnit.Millimeter, time: DurationUnit.Hour), new QuantityValue(1, 3600000));

        /// <summary>
        ///     The <see cref="SpeedUnit.MillimeterPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MillimeterPerMinute = new("MillimeterPerMinute", "MillimetersPerMinute", new BaseUnits(length: LengthUnit.Millimeter, time: DurationUnit.Minute), new QuantityValue(1, 60000));

        /// <summary>
        ///     The <see cref="SpeedUnit.MillimeterPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> MillimeterPerSecond = new("MillimeterPerSecond", "MillimetersPerSecond", new BaseUnits(length: LengthUnit.Millimeter, time: DurationUnit.Second), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="SpeedUnit.NanometerPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> NanometerPerMinute = new("NanometerPerMinute", "NanometersPerMinute", new BaseUnits(length: LengthUnit.Nanometer, time: DurationUnit.Minute), new QuantityValue(1, 60000000000));

        /// <summary>
        ///     The <see cref="SpeedUnit.NanometerPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> NanometerPerSecond = new("NanometerPerSecond", "NanometersPerSecond", new BaseUnits(length: LengthUnit.Nanometer, time: DurationUnit.Second), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="SpeedUnit.UsSurveyFootPerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> UsSurveyFootPerHour = new("UsSurveyFootPerHour", "UsSurveyFeetPerHour", new BaseUnits(length: LengthUnit.UsSurveyFoot, time: DurationUnit.Hour), new QuantityValue(1, 11811));

        /// <summary>
        ///     The <see cref="SpeedUnit.UsSurveyFootPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> UsSurveyFootPerMinute = new("UsSurveyFootPerMinute", "UsSurveyFeetPerMinute", new BaseUnits(length: LengthUnit.UsSurveyFoot, time: DurationUnit.Minute), new QuantityValue(20, 3937));

        /// <summary>
        ///     The <see cref="SpeedUnit.UsSurveyFootPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> UsSurveyFootPerSecond = new("UsSurveyFootPerSecond", "UsSurveyFeetPerSecond", new BaseUnits(length: LengthUnit.UsSurveyFoot, time: DurationUnit.Second), new QuantityValue(1200, 3937));

        /// <summary>
        ///     The <see cref="SpeedUnit.YardPerHour"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> YardPerHour = new("YardPerHour", "YardsPerHour", new BaseUnits(length: LengthUnit.Yard, time: DurationUnit.Hour), new QuantityValue(127, 500000));

        /// <summary>
        ///     The <see cref="SpeedUnit.YardPerMinute"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> YardPerMinute = new("YardPerMinute", "YardsPerMinute", new BaseUnits(length: LengthUnit.Yard, time: DurationUnit.Minute), new QuantityValue(381, 25000));

        /// <summary>
        ///     The <see cref="SpeedUnit.YardPerSecond"/> unit of <see cref="Speed"/>.
        /// </summary>
        public static readonly UnitOf<Speed> YardPerSecond = new("YardPerSecond", "YardsPerSecond", new BaseUnits(length: LengthUnit.Yard, time: DurationUnit.Second), new QuantityValue(1143, 1250));
    }
}
