//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="TemperatureDelta"/>, such as <see cref="TemperatureDeltaUnits.Kelvin"/>.
    /// </summary>
    public static class TemperatureDeltaUnits
    {
        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.DegreeCelsius"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> DegreeCelsius = new("DegreeCelsius", "DegreesCelsius", new BaseUnits(temperature: TemperatureUnit.DegreeCelsius), 1);

        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.DegreeDelisle"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> DegreeDelisle = new("DegreeDelisle", "DegreesDelisle", new BaseUnits(temperature: TemperatureUnit.DegreeDelisle), new QuantityValue(-2, 3));

        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.DegreeFahrenheit"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> DegreeFahrenheit = new("DegreeFahrenheit", "DegreesFahrenheit", new BaseUnits(temperature: TemperatureUnit.DegreeFahrenheit), new QuantityValue(5, 9));

        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.DegreeNewton"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> DegreeNewton = new("DegreeNewton", "DegreesNewton", new BaseUnits(temperature: TemperatureUnit.DegreeNewton), new QuantityValue(100, 33));

        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.DegreeRankine"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> DegreeRankine = new("DegreeRankine", "DegreesRankine", new BaseUnits(temperature: TemperatureUnit.DegreeRankine), new QuantityValue(5, 9));

        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.DegreeReaumur"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> DegreeReaumur = new("DegreeReaumur", "DegreesReaumur", new BaseUnits(temperature: TemperatureUnit.DegreeReaumur), new QuantityValue(5, 4));

        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.DegreeRoemer"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> DegreeRoemer = new("DegreeRoemer", "DegreesRoemer", new BaseUnits(temperature: TemperatureUnit.DegreeRoemer), new QuantityValue(40, 21));

        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.Kelvin"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> Kelvin = new("Kelvin", "Kelvins", new BaseUnits(temperature: TemperatureUnit.Kelvin), 1);

        /// <summary>
        ///     The <see cref="TemperatureDeltaUnit.MillidegreeCelsius"/> unit of <see cref="TemperatureDelta"/>.
        /// </summary>
        public static readonly UnitOf<TemperatureDelta> MillidegreeCelsius = new("MillidegreeCelsius", "MillidegreesCelsius", BaseUnits.Undefined, new QuantityValue(1, 1000));
    }
}
