//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    // Disable missing XML comment warnings for the generated unit enums.
    #pragma warning disable 1591

    public enum TemperatureUnit
    {
        DegreeCelsius = 1,
        DegreeDelisle = 2,
        DegreeFahrenheit = 3,
        DegreeNewton = 4,
        DegreeRankine = 5,
        DegreeReaumur = 6,
        DegreeRoemer = 7,
        Kelvin = 8,
        MillidegreeCelsius = 9,

        /// <summary>
        ///     The nominal solar effective temperature of 5772 K, adopted by IAU 2015 Resolution B3 as a conversion constant for expressing stellar temperatures.
        /// </summary>
        /// <remarks>https://arxiv.org/abs/1510.07674</remarks>
        SolarTemperature = 10,
    }

    #pragma warning restore 1591
}
