//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Torque"/>, such as <see cref="TorqueUnits.NewtonMeter"/>.
    /// </summary>
    public static class TorqueUnits
    {
        /// <summary>
        ///     The <see cref="TorqueUnit.GramForceCentimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> GramForceCentimeter = new("GramForceCentimeter", "GramForceCentimeters", BaseUnits.Undefined, new QuantityValue(196133, 2000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.GramForceMeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> GramForceMeter = new("GramForceMeter", "GramForceMeters", BaseUnits.Undefined, new QuantityValue(196133, 20000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.GramForceMillimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> GramForceMillimeter = new("GramForceMillimeter", "GramForceMillimeters", BaseUnits.Undefined, new QuantityValue(196133, 20000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.KilogramForceCentimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> KilogramForceCentimeter = new("KilogramForceCentimeter", "KilogramForceCentimeters", BaseUnits.Undefined, new QuantityValue(196133, 2000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.KilogramForceMeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> KilogramForceMeter = new("KilogramForceMeter", "KilogramForceMeters", BaseUnits.Undefined, new QuantityValue(196133, 20000));

        /// <summary>
        ///     The <see cref="TorqueUnit.KilogramForceMillimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> KilogramForceMillimeter = new("KilogramForceMillimeter", "KilogramForceMillimeters", BaseUnits.Undefined, new QuantityValue(196133, 20000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.KilonewtonCentimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> KilonewtonCentimeter = new("KilonewtonCentimeter", "KilonewtonCentimeters", BaseUnits.Undefined, 10);

        /// <summary>
        ///     The <see cref="TorqueUnit.KilonewtonMeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> KilonewtonMeter = new("KilonewtonMeter", "KilonewtonMeters", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="TorqueUnit.KilonewtonMillimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> KilonewtonMillimeter = new("KilonewtonMillimeter", "KilonewtonMillimeters", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="TorqueUnit.KilopoundForceFoot"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> KilopoundForceFoot = new("KilopoundForceFoot", "KilopoundForceFeet", BaseUnits.Undefined, new QuantityValue(3389544870828501, 2500000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.KilopoundForceInch"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> KilopoundForceInch = new("KilopoundForceInch", "KilopoundForceInches", BaseUnits.Undefined, new QuantityValue(1129848290276167, 10000000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.MeganewtonCentimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> MeganewtonCentimeter = new("MeganewtonCentimeter", "MeganewtonCentimeters", BaseUnits.Undefined, 10000);

        /// <summary>
        ///     The <see cref="TorqueUnit.MeganewtonMeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> MeganewtonMeter = new("MeganewtonMeter", "MeganewtonMeters", new BaseUnits(length: LengthUnit.Kilometer, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1000000);

        /// <summary>
        ///     The <see cref="TorqueUnit.MeganewtonMillimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> MeganewtonMillimeter = new("MeganewtonMillimeter", "MeganewtonMillimeters", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="TorqueUnit.MegapoundForceFoot"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> MegapoundForceFoot = new("MegapoundForceFoot", "MegapoundForceFeet", BaseUnits.Undefined, new QuantityValue(3389544870828501, 2500000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.MegapoundForceInch"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> MegapoundForceInch = new("MegapoundForceInch", "MegapoundForceInches", BaseUnits.Undefined, new QuantityValue(1129848290276167, 10000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.NewtonCentimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> NewtonCentimeter = new("NewtonCentimeter", "NewtonCentimeters", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="TorqueUnit.NewtonMeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> NewtonMeter = new("NewtonMeter", "NewtonMeters", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second), 1);

        /// <summary>
        ///     The <see cref="TorqueUnit.NewtonMillimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> NewtonMillimeter = new("NewtonMillimeter", "NewtonMillimeters", BaseUnits.Undefined, new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="TorqueUnit.OunceForceFoot"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> OunceForceFoot = new("OunceForceFoot", "OunceForceFeet", BaseUnits.Undefined, new QuantityValue(3389544870828501, 40000000000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.OunceForceInch"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> OunceForceInch = new("OunceForceInch", "OunceForceInches", BaseUnits.Undefined, new QuantityValue(1129848290276167, 160000000000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.PoundalFoot"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> PoundalFoot = new("PoundalFoot", "PoundalFeet", BaseUnits.Undefined, new QuantityValue(6584392202157, 156250000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.PoundForceFoot"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> PoundForceFoot = new("PoundForceFoot", "PoundForceFeet", BaseUnits.Undefined, new QuantityValue(3389544870828501, 2500000000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.PoundForceInch"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> PoundForceInch = new("PoundForceInch", "PoundForceInches", BaseUnits.Undefined, new QuantityValue(1129848290276167, 10000000000000000));

        /// <summary>
        ///     The <see cref="TorqueUnit.TonneForceCentimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> TonneForceCentimeter = new("TonneForceCentimeter", "TonneForceCentimeters", BaseUnits.Undefined, new QuantityValue(196133, 2000));

        /// <summary>
        ///     The <see cref="TorqueUnit.TonneForceMeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> TonneForceMeter = new("TonneForceMeter", "TonneForceMeters", BaseUnits.Undefined, new QuantityValue(196133, 20));

        /// <summary>
        ///     The <see cref="TorqueUnit.TonneForceMillimeter"/> unit of <see cref="Torque"/>.
        /// </summary>
        public static readonly UnitOf<Torque> TonneForceMillimeter = new("TonneForceMillimeter", "TonneForceMillimeters", BaseUnits.Undefined, new QuantityValue(196133, 20000));
    }
}
