//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="Volume"/>, such as <see cref="VolumeUnits.CubicMeter"/>.
    /// </summary>
    public static class VolumeUnits
    {
        /// <summary>
        ///     The <see cref="VolumeUnit.AcreFoot"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> AcreFoot = new("AcreFoot", "AcreFeet", BaseUnits.Undefined, new QuantityValue(60228605349, 48828125));

        /// <summary>
        ///     The <see cref="VolumeUnit.AuTablespoon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> AuTablespoon = new("AuTablespoon", "AuTablespoons", BaseUnits.Undefined, new QuantityValue(1, 50000));

        /// <summary>
        ///     The <see cref="VolumeUnit.BoardFoot"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> BoardFoot = new("BoardFoot", "BoardFeet", BaseUnits.Undefined, new QuantityValue(18435447, 7812500000));

        /// <summary>
        ///     The <see cref="VolumeUnit.Centiliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Centiliter = new("Centiliter", "Centiliters", BaseUnits.Undefined, new QuantityValue(1, 100000));

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicCentimeter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicCentimeter = new("CubicCentimeter", "CubicCentimeters", new BaseUnits(length: LengthUnit.Centimeter), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicDecimeter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicDecimeter = new("CubicDecimeter", "CubicDecimeters", new BaseUnits(length: LengthUnit.Decimeter), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicFoot"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicFoot = new("CubicFoot", "CubicFeet", new BaseUnits(length: LengthUnit.Foot), new QuantityValue(55306341, 1953125000));

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicHectometer"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicHectometer = new("CubicHectometer", "CubicHectometers", new BaseUnits(length: LengthUnit.Hectometer), 1000000);

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicInch"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicInch = new("CubicInch", "CubicInches", new BaseUnits(length: LengthUnit.Inch), new QuantityValue(2048383, 125000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicKilometer"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicKilometer = new("CubicKilometer", "CubicKilometers", new BaseUnits(length: LengthUnit.Kilometer), 1000000000);

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicMeter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicMeter = new("CubicMeter", "CubicMeters", new BaseUnits(length: LengthUnit.Meter), 1);

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicMicrometer"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicMicrometer = new("CubicMicrometer", "CubicMicrometers", new BaseUnits(length: LengthUnit.Micrometer), new QuantityValue(1, 1000000000000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicMile"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicMile = new("CubicMile", "CubicMiles", new BaseUnits(length: LengthUnit.Mile), new QuantityValue(8140980127813632, 1953125));

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicMillimeter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicMillimeter = new("CubicMillimeter", "CubicMillimeters", new BaseUnits(length: LengthUnit.Millimeter), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.CubicYard"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> CubicYard = new("CubicYard", "CubicYards", new BaseUnits(length: LengthUnit.Yard), new QuantityValue(1493271207, 1953125000));

        /// <summary>
        ///     The <see cref="VolumeUnit.Decaliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Decaliter = new("Decaliter", "Decaliters", BaseUnits.Undefined, new QuantityValue(1, 100));

        /// <summary>
        ///     The <see cref="VolumeUnit.DecausGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> DecausGallon = new("DecausGallon", "DecausGallons", BaseUnits.Undefined, new QuantityValue(473176473, 12500000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.Deciliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Deciliter = new("Deciliter", "Deciliters", BaseUnits.Undefined, new QuantityValue(1, 10000));

        /// <summary>
        ///     The <see cref="VolumeUnit.DeciusGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> DeciusGallon = new("DeciusGallon", "DeciusGallons", BaseUnits.Undefined, new QuantityValue(473176473, 1250000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.Hectoliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Hectoliter = new("Hectoliter", "Hectoliters", BaseUnits.Undefined, new QuantityValue(1, 10));

        /// <summary>
        ///     The <see cref="VolumeUnit.HectousGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> HectousGallon = new("HectousGallon", "HectousGallons", BaseUnits.Undefined, new QuantityValue(473176473, 1250000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.HundredCubicFoot"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> HundredCubicFoot = new("HundredCubicFoot", "HundredCubicFeet", BaseUnits.Undefined, new QuantityValue(55306341, 19531250));

        /// <summary>
        ///     The <see cref="VolumeUnit.ImperialBeerBarrel"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> ImperialBeerBarrel = new("ImperialBeerBarrel", "ImperialBeerBarrels", BaseUnits.Undefined, new QuantityValue(4091481, 25000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.ImperialGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> ImperialGallon = new("ImperialGallon", "ImperialGallons", BaseUnits.Undefined, new QuantityValue(454609, 100000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.ImperialOunce"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> ImperialOunce = new("ImperialOunce", "ImperialOunces", BaseUnits.Undefined, new QuantityValue(454609, 16000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.ImperialPint"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> ImperialPint = new("ImperialPint", "ImperialPints", BaseUnits.Undefined, new QuantityValue(454609, 800000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.ImperialQuart"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> ImperialQuart = new("ImperialQuart", "ImperialQuarts", BaseUnits.Undefined, new QuantityValue(454609, 400000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.KiloimperialGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> KiloimperialGallon = new("KiloimperialGallon", "KiloimperialGallons", BaseUnits.Undefined, new QuantityValue(454609, 100000));

        /// <summary>
        ///     The <see cref="VolumeUnit.Kiloliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Kiloliter = new("Kiloliter", "Kiloliters", new BaseUnits(length: LengthUnit.Meter), 1);

        /// <summary>
        ///     The <see cref="VolumeUnit.KilousGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> KilousGallon = new("KilousGallon", "KilousGallons", BaseUnits.Undefined, new QuantityValue(473176473, 125000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.Liter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Liter = new("Liter", "Liters", new BaseUnits(length: LengthUnit.Decimeter), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="VolumeUnit.MegaimperialGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> MegaimperialGallon = new("MegaimperialGallon", "MegaimperialGallons", BaseUnits.Undefined, new QuantityValue(454609, 100));

        /// <summary>
        ///     The <see cref="VolumeUnit.Megaliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Megaliter = new("Megaliter", "Megaliters", new BaseUnits(length: LengthUnit.Decameter), 1000);

        /// <summary>
        ///     The <see cref="VolumeUnit.MegausGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> MegausGallon = new("MegausGallon", "MegausGallons", BaseUnits.Undefined, new QuantityValue(473176473, 125000));

        /// <summary>
        ///     The <see cref="VolumeUnit.MetricCup"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> MetricCup = new("MetricCup", "MetricCups", BaseUnits.Undefined, new QuantityValue(1, 4000));

        /// <summary>
        ///     The <see cref="VolumeUnit.MetricTablespoon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> MetricTablespoon = new("MetricTablespoon", "MetricTablespoons", BaseUnits.Undefined, new QuantityValue(3, 200000));

        /// <summary>
        ///     The <see cref="VolumeUnit.MetricTeaspoon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> MetricTeaspoon = new("MetricTeaspoon", "MetricTeaspoons", BaseUnits.Undefined, new QuantityValue(1, 200000));

        /// <summary>
        ///     The <see cref="VolumeUnit.Microliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Microliter = new("Microliter", "Microliters", new BaseUnits(length: LengthUnit.Millimeter), new QuantityValue(1, 1000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.Milliliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Milliliter = new("Milliliter", "Milliliters", new BaseUnits(length: LengthUnit.Centimeter), new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.MillionCubicFoot"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> MillionCubicFoot = new("MillionCubicFoot", "MillionCubicFeet", BaseUnits.Undefined, new QuantityValue(442450728, 15625));

        /// <summary>
        ///     The <see cref="VolumeUnit.Nanoliter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> Nanoliter = new("Nanoliter", "Nanoliters", BaseUnits.Undefined, new QuantityValue(1, 1000000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.OilBarrel"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> OilBarrel = new("OilBarrel", "OilBarrels", BaseUnits.Undefined, new QuantityValue(9936705933, 62500000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.ThousandCubicFoot"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> ThousandCubicFoot = new("ThousandCubicFoot", "ThousandCubicFeet", BaseUnits.Undefined, new QuantityValue(55306341, 1953125));

        /// <summary>
        ///     The <see cref="VolumeUnit.ThousandCubicMeter"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> ThousandCubicMeter = new("ThousandCubicMeter", "ThousandCubicMeters", BaseUnits.Undefined, 1000);

        /// <summary>
        ///     The <see cref="VolumeUnit.UkTablespoon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UkTablespoon = new("UkTablespoon", "UkTablespoons", BaseUnits.Undefined, new QuantityValue(3, 200000));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsBeerBarrel"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsBeerBarrel = new("UsBeerBarrel", "UsBeerBarrels", BaseUnits.Undefined, new QuantityValue(14668470663, 125000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsCustomaryCup"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsCustomaryCup = new("UsCustomaryCup", "UsCustomaryCups", BaseUnits.Undefined, new QuantityValue(473176473, 2000000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsGallon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsGallon = new("UsGallon", "UsGallons", BaseUnits.Undefined, new QuantityValue(473176473, 125000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsLegalCup"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsLegalCup = new("UsLegalCup", "UsLegalCups", BaseUnits.Undefined, new QuantityValue(3, 12500));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsOunce"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsOunce = new("UsOunce", "UsOunces", BaseUnits.Undefined, new QuantityValue(473176473, 16000000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsPint"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsPint = new("UsPint", "UsPints", BaseUnits.Undefined, new QuantityValue(473176473, 1000000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsQuart"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsQuart = new("UsQuart", "UsQuarts", BaseUnits.Undefined, new QuantityValue(473176473, 500000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsTablespoon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsTablespoon = new("UsTablespoon", "UsTablespoons", BaseUnits.Undefined, new QuantityValue(473176473, 32000000000000));

        /// <summary>
        ///     The <see cref="VolumeUnit.UsTeaspoon"/> unit of <see cref="Volume"/>.
        /// </summary>
        public static readonly UnitOf<Volume> UsTeaspoon = new("UsTeaspoon", "UsTeaspoons", BaseUnits.Undefined, new QuantityValue(157725491, 32000000000000));
    }
}
