//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="VolumetricHeatCapacity"/>, such as <see cref="VolumetricHeatCapacityUnits.JoulePerCubicMeterKelvin"/>.
    /// </summary>
    public static class VolumetricHeatCapacityUnits
    {
        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.BtuPerCubicFootDegreeFahrenheit"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> BtuPerCubicFootDegreeFahrenheit = new("BtuPerCubicFootDegreeFahrenheit", "BtusPerCubicFootDegreeFahrenheit", BaseUnits.Undefined, new QuantityValue(6594099078875, 98322384));

        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.CaloriePerCubicCentimeterDegreeCelsius"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> CaloriePerCubicCentimeterDegreeCelsius = new("CaloriePerCubicCentimeterDegreeCelsius", "CaloriesPerCubicCentimeterDegreeCelsius", BaseUnits.Undefined, 4184000);

        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.JoulePerCubicMeterDegreeCelsius"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> JoulePerCubicMeterDegreeCelsius = new("JoulePerCubicMeterDegreeCelsius", "JoulesPerCubicMeterDegreeCelsius", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.DegreeCelsius), 1);

        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.JoulePerCubicMeterKelvin"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> JoulePerCubicMeterKelvin = new("JoulePerCubicMeterKelvin", "JoulesPerCubicMeterKelvin", new BaseUnits(length: LengthUnit.Meter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin), 1);

        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.KilocaloriePerCubicCentimeterDegreeCelsius"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> KilocaloriePerCubicCentimeterDegreeCelsius = new("KilocaloriePerCubicCentimeterDegreeCelsius", "KilocaloriesPerCubicCentimeterDegreeCelsius", BaseUnits.Undefined, 4184000000);

        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.KilojoulePerCubicMeterDegreeCelsius"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> KilojoulePerCubicMeterDegreeCelsius = new("KilojoulePerCubicMeterDegreeCelsius", "KilojoulesPerCubicMeterDegreeCelsius", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.DegreeCelsius), 1000);

        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.KilojoulePerCubicMeterKelvin"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> KilojoulePerCubicMeterKelvin = new("KilojoulePerCubicMeterKelvin", "KilojoulesPerCubicMeterKelvin", new BaseUnits(length: LengthUnit.Millimeter, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin), 1000);

        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.MegajoulePerCubicMeterDegreeCelsius"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> MegajoulePerCubicMeterDegreeCelsius = new("MegajoulePerCubicMeterDegreeCelsius", "MegajoulesPerCubicMeterDegreeCelsius", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.DegreeCelsius), 1000000);

        /// <summary>
        ///     The <see cref="VolumetricHeatCapacityUnit.MegajoulePerCubicMeterKelvin"/> unit of <see cref="VolumetricHeatCapacity"/>.
        /// </summary>
        public static readonly UnitOf<VolumetricHeatCapacity> MegajoulePerCubicMeterKelvin = new("MegajoulePerCubicMeterKelvin", "MegajoulesPerCubicMeterKelvin", new BaseUnits(length: LengthUnit.Micrometer, mass: MassUnit.Kilogram, time: DurationUnit.Second, temperature: TemperatureUnit.Kelvin), 1000000);
    }
}
