//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add UnitDefinitions\MyQuantity.json and run generate-code.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Licensed under MIT No Attribution, see LICENSE file at the root.
// Copyright 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com). Maintained at https://github.com/angularsen/UnitsNet.

// ReSharper disable once CheckNamespace
namespace UnitsNet.Units
{
    /// <summary>
    ///     The units of <see cref="VolumePerLength"/>, such as <see cref="VolumePerLengthUnits.CubicMeterPerMeter"/>.
    /// </summary>
    public static class VolumePerLengthUnits
    {
        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.CubicMeterPerMeter"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> CubicMeterPerMeter = new("CubicMeterPerMeter", "CubicMetersPerMeter", new BaseUnits(length: LengthUnit.Meter), 1);

        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.CubicYardPerFoot"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> CubicYardPerFoot = new("CubicYardPerFoot", "CubicYardsPerFoot", BaseUnits.Undefined, new QuantityValue(3919347, 1562500));

        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.CubicYardPerUsSurveyFoot"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> CubicYardPerUsSurveyFoot = new("CubicYardPerUsSurveyFoot", "CubicYardsPerUsSurveyFoot", BaseUnits.Undefined, new QuantityValue(1959669580653, 781250000000));

        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.ImperialGallonPerMile"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> ImperialGallonPerMile = new("ImperialGallonPerMile", "ImperialGallonsPerMile", BaseUnits.Undefined, new QuantityValue(454609, 160934400000));

        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.LiterPerKilometer"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> LiterPerKilometer = new("LiterPerKilometer", "LitersPerKilometer", BaseUnits.Undefined, new QuantityValue(1, 1000000));

        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.LiterPerMeter"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> LiterPerMeter = new("LiterPerMeter", "LitersPerMeter", new BaseUnits(length: LengthUnit.Decimeter), new QuantityValue(1, 1000));

        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.LiterPerMillimeter"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> LiterPerMillimeter = new("LiterPerMillimeter", "LitersPerMillimeter", BaseUnits.Undefined, 1);

        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.OilBarrelPerFoot"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> OilBarrelPerFoot = new("OilBarrelPerFoot", "OilBarrelsPerFoot", BaseUnits.Undefined, new QuantityValue(26080593, 50000000));

        /// <summary>
        ///     The <see cref="VolumePerLengthUnit.UsGallonPerMile"/> unit of <see cref="VolumePerLength"/>.
        /// </summary>
        public static readonly UnitOf<VolumePerLength> UsGallonPerMile = new("UsGallonPerMile", "UsGallonsPerMile", BaseUnits.Undefined, new QuantityValue(112903, 48000000000));
    }
}
